### ISSUE TITLE
Something went wrong: "TypeError: n.props.status is undefined" and the application can't recover.

### ISSUE THREAD

**Issue by Bestulo** [neo4j/neo4j-browser#1032]
- Neo4j version: 3.5.13 (Community)
- Operating system: Debian 9
- API/Driver: Browser App on http://localhost:7474/browser/

Going to the browser app on localhost, if you click Database, then go to Connected as and click the "user list", you'll get `Something went wrong: "TypeError: n.props.status is undefined" and the application can't recover.`

![image](https://user-images.githubusercontent.com/23301025/71394244-09c80d00-25e7-11ea-9be1-f435f4f67f93.png)

This is a new database & server.

Similarly, if you click "server user add", you'll get this:

![image](https://user-images.githubusercontent.com/23301025/71394376-a7234100-25e7-11ea-85f6-ef3f447a9b1d.png)
Transcription of the full error: ```Error: Unable to get roles list, There is no procedure with the name `dbms.security.listRoles` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.```

**Comment by oskarhane** [comment]
Thanks for reporting this @Bestulo.
This will be fixed in the next release of Neo4j 3.5.

**Comment by viveksacademia4git** [comment]
I am using Neo4j 3.5.14 (Community). This issue is still occurring.
