### ISSUE TITLE
What is related, and how -> ERROR There is no procedure with the name `db.schema` registered...

### ISSUE THREAD

**Issue by lqst** [neo4j/neo4j-browser#1033]
The `Favorites/Sample Scripts/Data Profiling/What is related, and how` query is not working for  neo4j server version 4.0.0-rc01.

Not sure if `db.schema()` is permanently moved to `db.schema.visualization()` on the server side.

https://github.com/neo4j/neo4j-browser/blob/38d7a31c89bae5fcc6f5ed7f39edd7b06c8fa590/src/shared/modules/favorites/staticScripts.js#L58

**Comment by oskarhane** [comment]
Thanks for reporting this @lqst. We'll get it fixed.
