### ISSUE TITLE
Unable to create database

### ISSUE THREAD

**Issue by usgdmarzan** [neo4j/neo4j-browser#1037]
### Description
Database failed to create
Distribution download error: No request found for id: undefined

### Reproduce Steps
Installed latest neo4j desktop for windows
using Neo4j 4.0.0

### Your Environment
Windows 10

| software name  | version
| ---------------|----------
 Neo4j               1.2.3

**Comment by usgdmarzan** [comment]
![neo4j-error-2020-01-07_13-06-05](https://user-images.githubusercontent.com/41127520/71917706-ae515f80-314e-11ea-9180-cfb8f659349b.png)

**Comment by oskarhane** [comment]
Hi and thanks for this report. This is not the right place for Neo4j Desktop issues, but this is a bug that will be fixed in next release of Neo4j Desktop (coming out very soon).
Here's the desktop repo where you can create issues: https://github.com/neo4j-apps/neo4j-desktop
