### ISSUE TITLE
Start, starts, start-prod scripts from package.json don't work on Windows

### ISSUE THREAD

**Issue by ZhekaAl** [neo4j/neo4j-browser#1039]
### Description
Start, starts, start-prod scripts from package.json don't work on Windows because of setting `NODE_ENV=\"development\"` . On Windows we should write `set NODE_ENV=development`

### Reproduce Steps

Clone this repo
Install yarn globally (not required but recommended): npm install -g yarn
Install project dependencies: yarn
yarn start (Windows PowerShell)

### Current Behavior
"NODE_ENV" is not internal or external
command, executable program or batch file.
error Command failed with exit code 1.
### Can you propose a solution?

Maybe we can write `cross-env NODE_ENV=development` 

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows 10 Pro 1809

**Comment by oskarhane** [comment]
Thanks for reporting @ZhekaAl 
Do you have the ability to open a PR to have this fixed you think?

That would be the fastest way to get this in.

**Comment by ZhekaAl** [comment]
Ok, I will open a PR
