### ISSUE TITLE
Interface does not connect automatically

### ISSUE THREAD

**Issue by mattorp** [neo4j/neo4j-browser#1046]
### Description
After upgrading to 4.0.2 I was presented with a blank browser, with a non-functioning connection to the db (no nodes, relations, props).
![Neo4j Desktop 2020-01-16 at 17 10 13](https://user-images.githubusercontent.com/26358815/72542363-515b5500-3884-11ea-90ef-e7eed9e1304a.png)

querying returned no connection, but server status returns connected
![Neo4j Desktop 2020-01-16 at 17 10 40](https://user-images.githubusercontent.com/26358815/72542381-591af980-3884-11ea-9309-4b961c42e5d1.png)

### Reproduce Steps
Open Neo4j Browser through the Neo4j Desktop interface. Restarting app and computer did not resolve it.

### Expected Behavior
The browser should connect automatically to the database.

### Current Behavior
See description 

### Can you propose a solution?
Disconnecting and reconnecting through the terminal resolved the issue, until closing and reopening the browser. Where the same bug appeared, and the same steps resolved it.

![Neo4j Desktop 2020-01-16 at 17 10 54](https://user-images.githubusercontent.com/26358815/72542434-6e902380-3884-11ea-990b-46dd8981a368.png)
![Neo4j Desktop 2020-01-16 at 17 11 06](https://user-images.githubusercontent.com/26358815/72542441-7223aa80-3884-11ea-87d8-3ab90da2b1e8.png)
![Neo4j Desktop 2020-01-16 at 17 11 13](https://user-images.githubusercontent.com/26358815/72542447-751e9b00-3884-11ea-96fa-f4245af55dff.png)
![Neo4j Desktop 2020-01-16 at 17 12 20](https://user-images.githubusercontent.com/26358815/72542455-78198b80-3884-11ea-9b98-6fdada0ce5f7.png)

### Your Environment
| software name  | version
| ---------------|----------
| OS             | macOs 10.15.2 (19C57)
| Neo4j Browser  | 4.0.2
| Neo4j          | 3.5.14

**Comment by oskarhane** [comment]
Thanks for this report @mattorp!
I suspect there's an error produced by Neo4j Desktop in the API side.
Could you, in Neo4j Desktop, enable "Development mode", then open Neo4j Browser again, click the "Open developer tools" in the Neo4j Browser window and see if you see any errors in the javascript console?

**Comment by mattorp** [comment]
Sadly, there's no console output.

![Neo4j Desktop 2020-01-19 at 14 07 04](https://user-images.githubusercontent.com/26358815/72681552-03815f80-3ac5-11ea-8bfa-af8894ba4f9a.png)


![Neo4j Desktop 2020-01-19 at 14 04 04](https://user-images.githubusercontent.com/26358815/72681524-c3ba7800-3ac4-11ea-82de-fc657553c7dd.png)

**Comment by mattorp** [comment]
Here's the output in relation to the first screenshot. There are no additional output through the process to reconnect as described above.

![Neo4j Desktop 2020-01-19 at 14 16 16](https://user-images.githubusercontent.com/26358815/72681713-8820ad80-3ac6-11ea-9f9e-32327a8349ae.png)

**Comment by oskarhane** [comment]
Thanks @mattorp 
What version of Neo4j Desktop do you have?
Please make sure that you're on 1.2.4.
We have currently paused auto updates for Mac from 1.2.3, so please manually download the latest front neo4j.com.
Sorry for the inconvenience.

**Comment by mattorp** [comment]
Thanks @oskarhane, sadly it does not seem to resolve it. The same problem persists with the same working workaround. Same for db version 4.0

**Comment by oskarhane** [comment]
If you are on Desktop 1.2.4 now @mattorp, could you do the whole development mode thing again and check the dev console of the neo4j browser window?
I suspect there's a different error now.

**Comment by mattorp** [comment]
@oskarhane Sorry for the late reply, but the issue have been resolved. Thanks!
