### ISSUE TITLE
Wierd behaviour in cypher property value

### ISSUE THREAD

**Issue by MortalFlesh** [neo4j/neo4j-browser#1049]
Hello,
I've discovered a wierd behaviour when using a `&` char in property value.

- Neo4j version: 1.2.1.1042
- Operating system: macOS Mojave (10.14.6)
- API/Driver: Cypher
- **Steps to reproduce**
```cypher
MERGE (:FOO { Id: 1, Property: "&currentabc"})
MERGE (:FOO { Id: 2, Property: "&current"})
MERGE (:FOO { Id: 3, Property: "&curren"})
MERGE (:FOO { Id: 4, Property: "&curre"})

match (n) return n
```
- Expected behavior
**Table** output
```
n
--
{   "Property": "&currentabc",   "Id": 1 }
{   "Property": "&current",   "Id": 2 }
{   "Property": "&curren",   "Id": 3 }
{   "Property": "&curre",   "Id": 4 }
```
- Actual behavior
**Table** output
```
n
--
{   "Property": "¤tabc",   "Id": 1 }
{   "Property": "¤t",   "Id": 2 }
{   "Property": "¤",   "Id": 3 }
{   "Property": "&curre",   "Id": 4 }
```

It is also wrong in the **Graph** output.

But it is correct in the **Text** output and in the matching.
```
╒═════════════════════════════════╕
│"n"                              │
╞═════════════════════════════════╡
│{"Property":"&currentabc","Id":1}│
├─────────────────────────────────┤
│{"Property":"&current","Id":2}   │
├─────────────────────────────────┤
│{"Property":"&curren","Id":3}    │
├─────────────────────────────────┤
│{"Property":"&curre","Id":4}     │
└─────────────────────────────────┘
```

**Comment by OskarDamkjaer** [comment]
Thanks for reporting this issue. I'm unable to reproduce it, could you confirm it's still present in the latest released browser ?
![bild](https://user-images.githubusercontent.com/10564538/96723842-620a9f80-13af-11eb-8177-ca78cdd3dc3b.png)
![bild](https://user-images.githubusercontent.com/10564538/96723810-57e8a100-13af-11eb-8800-2f1fd2d392cc.png)

**Comment by MortalFlesh** [comment]
Hello @OskarDamkjaer ,
sorry for a delay.. 

We have a new version of Neo4j and it's working as expected - so I guess it is no longer an issue.
