### ISSUE TITLE
In the Graph view, HTML properties are interpreted

### ISSUE THREAD

**Issue by sey** [neo4j/neo4j-browser#1050]
### Description
In the graph view, when you select a node you can see these properties in the status bar of the view. When node properties contain HTML, that HTML is interpreted. It already prevents `<script>` tags from being interpreted but they are stripped which means the real content of the property is not displayed. Other tags are interpreted and break the display.

### Reproduce Steps
Create a node with a property containing HTML.

### Expected Behavior
Do not interpret HTML and display HTML as-is (escaped).

### Current Behavior
HTML is interpreted.

### Can you propose a solution?
Use a `<pre>` tag or escape HTML but do not strip or interpret it.

### Your Environment
Neo4j Browser version: 3.2.26
Neo4j Server version: 3.5.14 (community)

**Comment by OskarDamkjaer** [comment]
Thanks for reporting this, the issue was resolved in #1164
