### ISSUE TITLE
URL param support for populating editor with Cypher does not work

### ISSUE THREAD

**Issue by achantavy** [neo4j/neo4j-browser#1070]
### Description
I followed the examples here: https://github.com/neo4j/neo4j-browser/pull/956
and cannot get neither Neo4j 3.5.16 Community nor  Neo4j 4.0.1 Community to populate the editor with Cypher.  The edit textbox remains empty in both Chrome and Safari.

### Reproduce Steps
1. Download of Neo4j 3.5.16 Community or 4.0.1 Community.
1. Run `~/neo4j-{version}/neo4j console`
1. Go to `http://localhost:7474/?cmd=edit&arg=RETURN%201;&arg=RETURN%20rand();` as described in https://github.com/neo4j/neo4j-browser/pull/956
1. Text field does not fill up with expected text.

### Expected Behavior
Text should fill up in the box as shown in #956.

### Current Behavior
Chrome and Safari route me to localhost:7474/browser and nothing is displayed in the text box.

### Your Environment
| software name  | version
| ---------------|----------
|                |  
| OS             |  OSX 10.14.16
| Web browser    |  Chrome 80.0.3987.132, Safari 13.0.5
| node.js        | N/A
| npm            | N/A
| yarn           | N/A
| Neo4j Browser  | 4.0.3 and 4.0.3
| Neo4j          | I tried out 3.5.16 Community and 4.0.1 Community

### Additional Information
Thanks for your help!

**Comment by achantavy** [comment]
cc: @oskarhane

**Comment by oskarhane** [comment]
What if you add the `/browser` path @achantavy ?
`http://localhost:7474/browser/?cmd=edit&arg=RETURN%201;&arg=RETURN%20rand();`

**Comment by jexp** [comment]
Does this work for you with Desktop?

`neo4j-desktop://graphapps/neo4j-browser/?cmd=edit&arg=RETURN%201`

try this with `/browser`

`http://localhost:7474/browser/?cmd=edit&arg=RETURN%201`

**Comment by jexp** [comment]
ping @achantavy

**Comment by achantavy** [comment]
Hey @oskarhane, @jexp,

adding `browser/` worked, thanks! Maybe you can add in an edit to the first comment of #956 to add in the browser path.
