### ISSUE TITLE
Movies database create character issue

### ISSUE THREAD

**Issue by dfgitn4j** [neo4j/neo4j-browser#1079]
### Description
tagline property on the Polar Express node has a pattern for the three dots in the text that can cause display issues when it is included in output from cypher-shell to a text file or pager.  

From `movie-graph.jsx`
```
CREATE (TheReplacements:Movie {title:'The Replacements', released:2000, tagline:'Pain heals, Chicks dig scars... Glory lasts forever'})

CREATE (ThePolarExpress:Movie {title:'The Polar Express', released:2004, tagline:'This Holiday Season… Believe'})
```
The hex character codes for the three 'dots' in the Polar Express tagline property are

  UTF-8 (comma delimited): `e2,80,a6`
  Unicode: `2026`

 While the (normal) three dots in The Replacements tagline property are: `2e,2e,2e` regardless of character encoding

Consistency if nothing else.

**Comment by OskarDamkjaer** [comment]
Thanks for reporting this! I'll go ahead and change the polar express to use three normal dots as well.
