### ISSUE TITLE
Browser interface doesn't load on neo4j:4.0.4 image on Chrome and Firefox.

### ISSUE THREAD

**Issue by alexluna7** [neo4j/neo4j-browser#1097]
After updating my neo4j Dockerfile to use image neo4j:4.0.4, the neo4j browser interface doesn’t load (I get a blank page) in Chrome and Firefox. I am reproducing below their console output. If I rollback the change to image neo4j:4.0.3, it loads properly.

On Safari v.13.0.5 (15608.5.11), Edge v.81.0.416.68 and Opera v.68.0.3618.63, it loads properly.

If I rollback the change to image neo4j:4.0.3, it loads properly.

I am using Docker Desktop v.2.2.0.5 (43884) on macOS v.10.15.3 (19D76).

**Chrome v.81.0.4044.138:**

neo4j-driver.chunkhash.bundle.js:1 Uncaught TypeError: r is not a function
    at Object.640 (neo4j-driver.chunkhash.bundle.js:1)
    at i (app-9364306….js:1)
    at Object.<anonymous> (app-9364306….js:641)
    at i (app-9364306….js:1)
    at Object.<anonymous> (app-9364306….js:104)
    at i (app-9364306….js:1)
    at Object.<anonymous> (app-9364306….js:421)
    at i (app-9364306….js:1)
    at Object.<anonymous> (app-9364306….js:344)
    at i (app-9364306….js:1)
640	@	neo4j-driver.chunkhash.bundle.js:1
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:641
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:104
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:421
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:344
i	@	app-9364306….js:1
2825	@	ui.chunkhash.bundle.js:1
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:122
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:21
i	@	app-9364306….js:1
335	@	neo4j-driver.chunkhash.bundle.js:1
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:436
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:436
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:436
(anonymous)	@	app-9364306….js:436
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:641
i	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:436
i	@	app-9364306….js:1
n	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:1
(anonymous)	@	app-9364306….js:1

**Firefox v.76.0:**
TypeError: r is not a function
neo4j-driver.chunkhash.bundle.js:1:146838
    640 https://neo4j.checkupinteligente.com.dev:7474/browser/neo4j-driver.chunkhash.bundle.js:1
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:641
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:104
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:421
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:344
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    2825 https://neo4j.checkupinteligente.com.dev:7474/browser/ui.chunkhash.bundle.js:1
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:122
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:21
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    335 https://neo4j.checkupinteligente.com.dev:7474/browser/neo4j-driver.chunkhash.bundle.js:1
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:436
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:436
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:436
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:436
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:641
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:436
    i https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    n https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1
    <anonymous> https://neo4j.checkupinteligente.com.dev:7474/browser/app-93643064413366ec583f.js:1

​

**Comment by oskarhane** [comment]
Thanks for the report @alexluna7. This looks like a aggressive web browser caching issue.
If you (in Chrome) open the web browser devtools, switch to the network tab, check the "disable cache" option and then reload the page with the devtools open it should work again.

I'm sure Firefox has a similar way for reloading with no cache.

**Comment by alexluna7** [comment]
Thank you for the response.
Clearing or disabling the cache in every browser fixed the issue with both neo4j images (4.0.3 and 4.0.4).

**Comment by oskarhane** [comment]
👍

**Comment by Mote-Z** [comment]
👍

**Comment by phhu** [comment]
I had same issue with v 4.1.1 - fixed in same way, by clearing cache.
