### ISSUE TITLE
Save state of graph layout in neo4j web interface. 

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#111]
_From @pumplerod on December 14, 2012 17:54_

It would be a HUGE help to be able to save the positional state of nodes in the visualization graph. 

I often write queries to change parameter values and because the values do not update I have to refresh the graph which causes everything to scramble again. 

What I'd love is to assemble nodes into a layout that works for me and then lock those nodes down so that when I refresh the only thing to change would be the label and parameter values. 

_Copied from original issue: neo4j/neo4j#371_

**Comment by vvavepacket** [comment]
Is it possible to save the layout arrangement after we arrange the nodes? When I refreshed the page, the arrangement of the nodes was lost, so we have to type again the query, and then drag the nodes to the arrangement that we like.

**Comment by oskarhane** [comment]
@vvavepacket for the time being we do not have this feature, no. We consider this ticket a feature request and will have that in mind when we continue to evolve our visualization and it's features.

**Comment by kadnan** [comment]
@oskarhane  Is this thing done yet? if note, how can I do it?

**Comment by oskarhane** [comment]
This is not something that Neo4j Browser will have.
