### ISSUE TITLE
Neo4J Desktop Cypher Query - Parts of Labels Registering as KeyWords 

### ISSUE THREAD

**Issue by teddylee123** [neo4j/neo4j-browser#1128]
Hi there,

First time poster and Neo4j Desktop User - trying to upload and convert a csv file but parts of my query keep registering in Cypher/DesktopQuery as keywords making my code unusable. Please see screenshot of both my code and example Neo4J code attached - neither of which work properly.
<img width="1147" alt="Screenshot 2020-06-23 at 21 00 25" src="https://user-images.githubusercontent.com/66165233/85454637-09f49580-b595-11ea-8ec9-80d36bcf877b.png">
<img width="1000" alt="Screenshot 2020-06-23 at 20 48 52" src="https://user-images.githubusercontent.com/66165233/85454917-4e803100-b595-11ea-898f-8e0f79b18247.png">

Please let me know what to change.

Thanks!

### Steps to reproduce
1. Type in code in the screenshot

### Expected behavior
1. Appropriate return of the values in the csv

### Actual behavior
1.  key words not registering as proper cypher code

**Comment by OskarDamkjaer** [comment]
Hello! Is this a purely visual problem? Do you get any errors when you try to run the query from your image?

**Comment by OskarDamkjaer** [comment]
The current syntax highlighting isn't smart enough not to highlight "count" in "country", the plan is to switch what editor is used and new do better highlighting then. If your issue is not purely visual, please re-open this issue
