### ISSUE TITLE
Movie data set should be inserted with MERGE

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#114]
_From @jakewins on December 9, 2013 10:23_

From @jexp 

To be idempotent in case people run the insert accidentally twice.

_Copied from original issue: neo4j/neo4j#1652_

**Comment by OskarDamkjaer** [comment]
Inserting the movie data set will be many users first time running a cypher query. I think it's worth the accidental duplication to show the CREATE rather than MERGE to avoid confusion. If you feel otherwise feel free to open a new issue
