### ISSUE TITLE
Support multiple cypher statements at a time in browser

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#115]
_From @jakewins on December 9, 2013 10:24_

From @jexp 

Separated by `;`

For create statements that don't return data only create one result frame.

For query statements that return data, either:
- one frame per result
- aggregate all results into one frame (one viz for all nodes) and concatinate tables for the tabular view

_Copied from original issue: neo4j/neo4j#1653_

**Comment by noumaans** [comment]
@oskarhane Not sure if this issue got fixed or rejected.

Here is a set of multiple queries being written in browser which fail in Browser 3.1.12, Neo Server 3.4.0.:
    CREATE CONSTRAINT ON (n:Foo) ASSERT exists(n.bar);
    CREATE CONSTRAINT ON (n:Foo) ASSERT exists(n.baz);

**Comment by BrenoMazieiro** [comment]
Any updates on that?

**Comment by vijji90** [comment]
Hi, Whether this issue is resolved?
