### ISSUE TITLE
how does Neo4j Browser implement graph visualization in browser

### ISSUE THREAD

**Issue by minicloudsky** [neo4j/neo4j-browser#1160]
## Guidelines

I want to implement neo4j data visualization in browser ,to show the neo4j data ,I found some solutions on github,however ,all of them does not match my demand , I want to implement neo4j data visualization as good as neo4j in browser client ,
so i want to know how does the neo4j browser client implemented the data visualizaion ,
 what should i do or which document should i read, any thinking is welcomed to come up , thanks in advance .

**Comment by OskarDamkjaer** [comment]
Feel free to fork the neo4j browser and adapt it to your needs! Our visualization is non-trivial so I won't go into it here, but you'll find relevant code here: https://github.com/neo4j/neo4j-browser/tree/master/src/browser/modules/D3Visualization

**Comment by minicloudsky** [comment]
> Feel free to fork the neo4j browser and adapt it to your needs! Our visualization is non-trivial so I won't go into it here, but you'll find relevant code here: https://github.com/neo4j/neo4j-browser/tree/master/src/browser/modules/D3Visualization

thank you very much, i try to adapt the neo4j for my needs .
