### ISSUE TITLE
RTL Text displayed outside of node

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j-browser#1173]
### Description
Nodes displaying a property in Arabic see their text mostly outside of the node.
Same with Hebrew.

Depending on the chosen color for the label, text might be displayed in white. 
Thus making it invisible on default background.
(for other label colors, same issue with dark mode : black on black )

### Reproduce Steps
CREATE (a:RTLTEST {text:'حرف جر'})
RETURN a

CREATE (a:RTLTEST {text:'פרצוף מחייך עם פה פתוח ועיניים מחייכות'})
RETURN a

### Expected Behavior
Text centered in/on node

### Current Behavior
 text shifted on the right

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  linux 
| Web browser    |  ffox
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 4.1.0
| Neo4j          | neo4j 4.1.1

**Comment by wadael** [comment]
Apologies for the duplicate

**Comment by OskarDamkjaer** [comment]
@wadael no worries! Better to be reported twice than never at all!
