### ISSUE TITLE
[Neo4j Desktop] [Browser Guide]

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j-browser#1191]
### Description

UI text is where it's not supposed to be, see screenshot

<img width="1198" alt="Screen Shot 2020-09-07 at 11 58 01 AM" src="https://user-images.githubusercontent.com/2731744/92404443-9842d700-f101-11ea-8004-1e3be25d764b.png">

### Reproduce Steps

* In Neo4j Desktop, start a fresh, brand new 4.1 database
* Once database is ready, press the 'Open' button to open the browser
* Paste in the play command for a graph guide that has title formatting in the body. 

For example, one that starts like this:
```
= Mahabharata =

The example graph consists of characters in Mahabharata - the Indian Epic.
Key nodes - Relations, Wars and their key actions

We'll go with key characters. There is great debate on Mahabharata genealogy, so we will stick to Wikipedia version for now
http://en.wikipedia.org/wiki/Mahabharata

```

here's an example in the wild
```
:play https://guides.neo4j.com/graph-examples/business-rule-recommendation-gist/graph_guide
```

See UI, text all over the place

### Expected Behavior

Text should appear where it's supposed to

### Can you propose a solution?

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Mac Catalina
| Web browser    |  Neo4j Desktop Electron App
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | Neo4j Desktop 1.3.3
| Neo4j          | 4.1.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.

**Comment by OskarDamkjaer** [comment]
Thanks for reporting this!
