### ISSUE TITLE
Provide progress to user 

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j-browser#1198]
### Description
I wrote a BIG load csv script. I takes forever despite all indexes, constraints being ok, and the source csv file being very reasonable.

As a user, I'd like to see which line# is being processed  to have visual feedback
Like 

Processing line #25 on 350

**Comment by OskarDamkjaer** [comment]
Thanks for this feature request! We're looking into ways of providing better progress/performance reporting currently. It's possible we will get it in this year, but I can't promise anything
