### ISSUE TITLE
Running `EXPLAIN` in dark mode results in unreadable text in neo4j browser

### ISSUE THREAD

**Issue by zayd62** [neo4j/neo4j-browser#1241]
### Description

When you run an explain command, the resulting diagram has black text when using the **dark** theme. Text is readable in **Normal** and **Outline** theme. 

### Reproduce Steps

Running the following command and change the different themes
```
EXPLAIN MATCH (ja: Student{name:"Jack"}), (jm: Student {name:"James"}) RETURN ja, jm
```

### Expected Behavior
The text under the box (node) should be a different colour other than black. See example below for clearer example

### Current Behavior
**Normal theme**
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/26032382/98797090-05c1fb00-2404-11eb-94e0-3c19a4e49960.png">

**Outline theme**
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/26032382/98797139-18d4cb00-2404-11eb-8a7d-3947dffdad6f.png">

**Dark Theme**
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/26032382/98797204-3013b880-2404-11eb-9f11-d4668fedca6c.png">

### Can you propose a solution?

Simply changing the font colour to a light colour might not work as the edge between the boxes is also a light colour. perhaps a combination of a dark background and light.

Using Safari devtools, I that this is the code for the edge between two boxes and the text

```html
<g class="link">
<path fill="#DFE1E3" d="M 160.99730693553698 -314 C 160.99730693553698 -291.2975140491012 267.7100991404886 -291.2975140491012 267.7100991404886 -264 L 260.4922458823129 -264 C 260.4922458823129 -286.7024859508988 153.7794536773613 -286.7024859508988 153.7794536773613 -314 Z"></path>
<text font-size="10" font-family="'Helvetica Neue',Helvetica,Arial,sans-serif" text-anchor="end" y="-300" x="157.38838030644914">1&nbsp;</text>
<text font-size="10" font-family="'Helvetica Neue',Helvetica,Arial,sans-serif" text-anchor="start" y="-300" x="157.38838030644914">estimated row</text>
</g>
```
one solution is to wrap the `<text>` elements in a div, give the div a dark background and make the text white. something like this (apologies for bad drawing)

![bug (1)](https://user-images.githubusercontent.com/26032382/98801480-c1d1f480-2409-11eb-8f32-28c1639e6e51.png)

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Mac OS Catalina 10.17.5
| Web browser    |  Safari 14, Firefox 82
| node.js        | v14.12.0
| npm            | 6.14.8
| yarn           | 1.22.5
| Neo4j Browser  | included with Docker
| Neo4j          | neo4j:4.1.3 on Docker

**Comment by OskarDamkjaer** [comment]
Thanks for taking the time and all the detail you provided, we solved this by changing the color to a blue that's readable on both black and white backgrounds!
