### ISSUE TITLE
Failed to connect to Neo4j

### ISSUE THREAD

**Issue by flyking1994** [neo4j/neo4j-browser#1242]
Follow the README, I open http://localhost:8080 in my browser, but I failed to connect to Neo4j. 
In the URL, I tried "localhost:8080", "localhost:7687", "localhost:7474". Username and Password are both "neo4j".
 
![image](https://user-images.githubusercontent.com/30041161/99083366-69b11300-2600-11eb-9386-e188e10318c8.png)

**Comment by OskarDamkjaer** [comment]
Do you have a database running? I'm unable to reproduce this issue, could you provide more details?
