### ISSUE TITLE
not a WebSocket handshake request: missing upgrade

### ISSUE THREAD

**Issue by Trend20** [neo4j/neo4j-browser#1247]
### Description

I have started Neo4j server locally on Ubuntu 20 and when i navigate to the port number 7687, i encounter this error in my chrome browser.
error: not a WebSocket handshake request: missing upgrade

**Comment by OskarDamkjaer** [comment]
Could you provide some more details? 

How did you install neo4j, using desktop? Are you sure neo4j is running? Are you running on your computer or on a server?

**Comment by rbramley** [comment]
This message is seen when you connect to the Bolt connector on port 7687, instead of using port 7474 for the Neo4j browser.
