### ISSUE TITLE
Indentation of JSON in Neo4j Browser is off

### ISSUE THREAD

**Issue by corysimmons** [neo4j/neo4j-browser#1258]
![image](https://user-images.githubusercontent.com/224636/102721787-fc616380-42ca-11eb-88be-13a6b8460481.png)

Hopefully this is just a simple JSON.stringify tweak on the frontend, but it'd make browsing values a lot nicer if it was indented correctly.

**Comment by mrksph** [comment]
Hi, I've been wondering about this the last 2 years... Any update on this?

**Comment by OskarDamkjaer** [comment]
Hey! Sorry about the lack of updates here. I worked to fix this just last week! I'll post an update when it's released!

**Comment by ajmeese7** [comment]
I was just coming here with the intention of adding a fix, glad to see that you're already on it!

**Comment by OskarDamkjaer** [comment]
I've implemented a fix for this now, thank you for your patience :tada: We're planning to do a browser release on monday (which will be shipped in neo4j 5.3.0 some time mid december iirc). From wednesday it should be in aura free (browser.neo4j.io that is)

The code for formatting is _old_ so there might very well be other things that look off as well, if so do post another comment here and I'll be faster to fix it next time 😄

**Comment by corysimmons** [comment]
Thank you, and thanks for the update!

**Comment by mrksph** [comment]
Thank you!
