### ISSUE TITLE
Saved Scripts in Web UI Issue

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#129]
_From @edschembor on July 22, 2014 0:29_

So I'm not sure if this would could as a feature request or an issue. 

If you run a saved script in the Web UI and then cntrl-up to grab it from your history of searches, it no longer appears as a saved search. ie) the star is no longer gold and saving it creates a copy as opposed to overwriting. 

Pretty new to Neo4j, but I want to get involved with development so I'll try to look into the issue myself

_Copied from original issue: neo4j/neo4j#2713_

**Comment by oskarhane** [comment]
_From @akollegger on July 22, 2014 18:29_

Hi @edschembor 

Yes, that's a UX bug. We've explored design approaches which clarify the relationship between saved scripts, frames (the results from running), and "command history" but haven't resolved the appropriate behavior. 

The tricky bit is what happens when you have run a script multiple times. Each instance in history should be associated with the saved script. Now you edit one of them, and run it again without saving. That should create yet another instance that is associated, and *all* instances in history should get marked as dirty (in need of being saved), allowing you to walk back through each of them and then save the one you like. 

Something like that.

**Comment by OskarDamkjaer** [comment]
Thanks for reporting this issue, I know it's been a few years, but we'll keep this in mind when re-working the saved scripts interactions.
