### ISSUE TITLE
Graph Style Sheet doesn't support attribute selectors styling

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#131]
_From @liudonghua123 on January 6, 2015 2:44_

In Neo4j's browser graph visualization, graph style sheet only supports tag and tag.class selector, multiple chained class like "tag.class1.class2" is not support(see  https://github.com/neo4j/neo4j/issues/2112), I think attribute selectors is more important than multiple chained class.
For example, we can use the following to distinguish person of different gender.
node.Person[gender="male"] {
......
}
node.Person[gender="female"] {
......
}
And we could highlight the 1980s movies via
node.Movie[released^="198"] {
......
}

For more attribute selectors example, see http://www.w3schools.com/css/css_attribute_selectors.asp

_Copied from original issue: neo4j/neo4j#3751_

**Comment by oskarhane** [comment]
_From @Gary-Li on January 7, 2015 1:49_

+1

**Comment by oskarhane** [comment]
_From @khatkar on August 19, 2015 16:56_

Agree, this would be a really cool feature.
+1

**Comment by oskarhane** [comment]
_From @slorg1 on October 5, 2015 21:53_

+1

**Comment by marcosscriven** [comment]
+1 on this too. In the meantime, I made this little snippet you can paste in your browser console:

```
function createOverriddenStyleForNode(graphStyleDelegate) {
  var originalForNode = graphStyleDelegate.forNode;
  return function(node) {
    var style = originalForNode.call(graphStyleDelegate, node);
    if(node && node.propertyMap.singleton) {
      style.props.color = "#0000FF";
    }
    return style;
  }
}

var graphStyleDelegate = angular.element(document.getElementById("stream")).injector().get("GraphStyle");
var wrapped = createOverriddenStyleForNode(graphStyleDelegate);
angular.element(document.getElementById("stream")).injector().get("GraphStyle").forNode=wrapped;
```

In my particular case I wanted node with the property ```singleton``` to have a different colour.

**Comment by apcj** [comment]
fwiw, when I've thought about this in the past, I'd actually like to change GraSS to move slightly away from CSS and borrow the syntax from Cypher instead.

For example this would be the expression of nodes with the Person label and gender property set to male:

```
(:Person {gender: "male"})
{
    color: 'blue'
}
```

Equivalently you could choose to use a WHERE clause like in Cypher:

```
(n:Person) WHERE n.gender = "male"
{
    color: 'blue'
}
```

This allows for more sophisticated expressions that can't be expresses inline, e.g.:

```
(n:Person) WHERE (n.gender = "male" AND n.age > 60) OR (n.gender = "female" AND n.age > 65)
```

This style also works well for relationships, allowing them to be styled according to attributes of the end nodes. For example this rule could color relationships to criminals red, so that you can pick those relationships out amongst other friendships:

```
(:Person)-[:FRIEND]->(:Criminal)
{
    color: red
}
```

**Comment by nicho90** [comment]
Hi @oskarhane,
I watch this feature-request for a while, so I would like to ask you, if you can give me/us an update about the status? This feature would be really useful! Thanks and cheerio, Nicho ✌️

**Comment by nicho90** [comment]
Just in case, the following workaround works well for me:

```
MATCH (person:Persons) WHERE person.gender = 'female'
SET person :Persons:Women;
```

```
MATCH (person:Persons) WHERE person.gender = 'male'
SET person :Persons:Men;
```

After that, change the colors for the new labels accordingly! 🎨

**Comment by OskarDamkjaer** [comment]
Hi! Sorry for the lack of updates, we're trying to better how we handle responding to and giving updates on feature requests with [canny.io](https://neo4j-browser.canny.io/feature-requests). If this feature is something you're still interested in, do raise it there instead!
