### ISSUE TITLE
Browser: Ability to export saved scripts

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#132]
_From @edschembor on January 11, 2015 4:24_

If I understand correctly, the saved scripts in the browser are saved locally on the clients web browser. Are there any plans for a method to export selected saved scripts so that a bunch of them could be easily imported to another web browser? Or is the main method for doing so still manually moving them? (see http://stackoverflow.com/questions/23966160/neo4j-export-cypher-scripts-from-localhost7474-frontend-how-to)

Thanks!

_Copied from original issue: neo4j/neo4j#3781_

**Comment by jdorleans** [comment]
Similarly to #136. I'd love to have this implemented. It's such basic behaviour and very helpful. Why those 2 issues were closed?

**Comment by flatstep** [comment]
> Similarly to #136, I'd love to have this implemented. It's such basic behaviour and very helpful. Why those 2 issues were closed?

Same question here. Why has this isue been closed without any explanation?
A script import-/export function would be great.
