### ISSUE TITLE
Graph draws more nodes and relationships than

### ISSUE THREAD

**Issue by WhoIAmm** [neo4j/neo4j-browser#1325]
![微信图片_20210315210904](https://user-images.githubusercontent.com/45116001/111158649-3fce2400-85d3-11eb-814a-90757027efe5.png)

As my picture shows up there, I do the query then I get 322 results(rows), but in the Graph window, it seems that all the relationships between n1 and n2 are drawn. How could I just let it draws the 322 results I want rather than all relationships, it would be great that you could help me solve the problem, thank you very very very kindly...... :)
![QQ截图20210315211551](https://user-images.githubusercontent.com/45116001/111159305-eadedd80-85d3-11eb-8c04-949bd78f09f3.jpg)

**Comment by gregoryking** [comment]
Try unchecking the _Connect result nodes_ setting:
<img width="349" alt="CleanShot 2021-03-22 at 13 07 35@2x" src="https://user-images.githubusercontent.com/1253994/111994375-9c6b9a80-8b0f-11eb-9f82-3ffe83667e3a.png">

**Comment by OskarDamkjaer** [comment]
@WhoIAmm Did gregs tip help?

**Comment by OskarDamkjaer** [comment]
If gregs tip didn't help, feel free to re-open this issue
