### ISSUE TITLE
populate data browser query field from url

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#133]
_From @collin on January 22, 2015 20:5_

For debugging purposes it'd be great to be able to log out a url like...

```
http://neo4jhost:7474/browser/?query=MATCH (n:Label)-[:relationship]->(m:label {property:'value'} return n, m
```

And be able to just open that url in a browser and have the data browser automatically run that query.
Would that be easy to implement in the data browser?

_Copied from original issue: neo4j/neo4j#3861_

**Comment by oskarhane** [comment]
_From @jexp on January 22, 2015 20:18_

You can do that with the Neo4j console. 

http://console.neo4j.org?init=create%20data%20query&query=your%20query

**Comment by oskarhane** [comment]
_From @collin on January 22, 2015 22:23_

Is there a version of that console that runs against my local neo4j server?

Even in that case it would be nice to have the same feature in the browser. The browser lets you expand node relationships in the graph view, which is very nice for walking around the data while debugging.

**Comment by oskarhane** [comment]
_From @yuruki on September 2, 2015 13:36_

This would allow user to execute a query and show the resulting graph simply by clicking on a link.

We have been missing this feature since we started using Neo4j browser.

**Comment by oskarhane** [comment]
_From @jessmartin on October 6, 2015 21:12_

:+1:! Would love to have this feature as well.

**Comment by rationalism** [comment]
+1

**Comment by bakl** [comment]
!!!

**Comment by mbukosky** [comment]
+1

**Comment by augustearth** [comment]
+1

**Comment by nicolaschaillan** [comment]
+1

**Comment by artkhl** [comment]
+1

**Comment by achantavy** [comment]
Hi there, having this feature would make it infinitely easier to share data with other users.  Are there plans to work on this?

We would like something as described in this [StackOverflow question](https://stackoverflow.com/questions/24062795/can-i-send-neo4j-browser-a-cypher-query-via-get-post) -  go to `http://localhost:7474/browser/query='match n return n'` and then you get a page running that query.  The input sanitization here would be a nightmare, so..

Another way to do it could be to let a user run a query in the browser and then allow it to generate a short URL that when accessed will lead clients to that exact query.  This could be safer than the above approach.  What do you think?

**Comment by oskarhane** [comment]
This is possible since: https://github.com/neo4j/neo4j-browser/pull/956
It won't ru automatically but it populates the editor so the user can review it before they execute it.

**Comment by achantavy** [comment]
@oskarhane Awesome, thanks for replying!  Is there a doc on how to use this?  I'm not sure I'm doing it right.

I go to `http://localhost:7474/?cmd=params&arg={x:1.0,%20y:%22hello%22}` on my local unauthenticated instance running 3.5.14 but it only sends me to the login page.

**Comment by oskarhane** [comment]
@achantavy 3.5.14 is too old. It ships with Neo4j Browser ` 3.2.26`. 
This was released with Neo4j Browser `4.0.2`, which is in Neo4j `3.5.15` and later.

**Comment by achantavy** [comment]
I tried out 3.5.16 and 4.0.1 with auth turned off and going to `http://127.0.0.1:7474/?cmd=edit&arg=RETURN%201;&arg=RETURN%20rand();` still sends me to the login page.

I also tried turning auth on with both versions and it doesn't send me to the login page, but the query does not fill as expected.

Any ideas?

**Comment by achantavy** [comment]
@oskarhane Oh, this is community edition btw.

**Comment by blackvvine** [comment]
@achantavy Did you manage to solve this problem?

**Comment by bigquant** [comment]
+1 for this

**Comment by OskarDamkjaer** [comment]
When I add `?cmd=edit&arg=RETURN 1;` to browser, it works fine. Could we perhaps get some more details on what version/issues you've run into?
