### ISSUE TITLE
Make "Close Frame?" configurable

### ISSUE THREAD

**Issue by graphadvantage** [neo4j/neo4j-browser#1331]
Hi,

Understand that some folks want the extra check, but for experienced dev users it's a pain to wait for the "Close Frame?" warning to render and then have to click on it simply to clear out a bunch of old windows, which in the older version was a one click operation in the upper right.

Please at least make this configurable in the neo4j-browser settings.

Thanks! -Michael

**Comment by OskarDamkjaer** [comment]
Yeah, we hear you! We're planning to just remove it by the next version :)
