### ISSUE TITLE
Browser console: multi-line comments are not greyed out

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#138]
_From @mindrones on May 29, 2015 10:36_

In the browser console, multi-line comments are not greyed out as single-line comments.

![neo4j_browser_multiline_comment](https://cloud.githubusercontent.com/assets/1309648/7880974/c4d1e0c0-05fe-11e5-97c2-5dffe41c2702.png)

BTW: although working as expected, multi-line comments are not mentioned [in the documentation](http://neo4j.com/docs/2.2.2/cypher-comments.html), is this intended?

_Copied from original issue: neo4j/neo4j#4721_

**Comment by oskarhane** [comment]
_From @jexp on May 29, 2015 10:50_

Not sure this was intentional to work :) At least I haven't seen it before anywhere.

**Comment by OskarDamkjaer** [comment]
Thanks for this feature request! There's ongoing work to replace and improve the editor support for cypher. I've added this feature to our internal checklist of requirements
