### ISSUE TITLE
Allow configuring "Base-URL"/base location/context path, which currently defaults to '/browser', via environment variable

### ISSUE THREAD

**Issue by Masterxilo** [neo4j/neo4j-browser#1400]
See
* https://stackoverflow.com/questions/30093933/how-to-configure-neo4j-browser-to-use-a-custom-rest-endpoint
* https://stackoverflow.com/a/33321538/524504

This is required for more flexibility in reverse proxying to the neo4j-browser.

**Comment by Masterxilo** [comment]
Many other containers hosting a web-app have such a configuration option.
For example, https://github.com/mongo-express/mongo-express has 'ME_CONFIG_SITE_BASEURL'

**Comment by Masterxilo** [comment]
Another option would be to implement X-Script-Name. pgAdmin 4 does this:

https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html

> If you wish to host pgAdmin under a subdirectory rather than on the root of the server, you must specify the location and set the X-Script-Name header which tells the pgAdmin container how to rewrite paths:
```
server {
    listen 80;
    server_name _;

    location /pgadmin4/ {
        proxy_set_header X-Script-Name /pgadmin4;
        proxy_set_header Host $host;
        proxy_pass http://localhost:5050/;
        proxy_redirect off;
    }
}
```

**Comment by OskarDamkjaer** [comment]
Hi! This does indeed sound useful, but the hosting of Neo4j Browser when bundled with neo4j is not up to us. We have no server config in this repo, so you're better off opening the issue in the main Neo4j repo!
