### ISSUE TITLE
Dark text in dark mode

### ISSUE THREAD

**Issue by EmilioDelCastillo** [neo4j/neo4j-browser#1409]
### Description
The description text is barely visible in dark mode.

### Expected Behavior
It should be the same colour as the text above it, or at least less dark.

### Current Behavior
![screen-shot](https://user-images.githubusercontent.com/78765245/117868753-3f33d000-b29a-11eb-83a8-0d2a6c28592f.png)

### Can you propose a solution?
I suppose the fix is somewhere in [themes.ts](/neo4j/neo4j-browser/blob/master/src/browser/styles/themes.ts), I couldn't find where though. When I inspected it in the browser the css selector was `.gSIPwr`, I believe it was computed, but I don't know where.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  macOS 11.3
| Web browser    |  Firefox 88.0.1
| Neo4j Browser  | 3.2.16

**Comment by jharris4** [comment]
Or you can run the latest version directly from [here[(https://browser.graphapp.io/)

**Comment by EmilioDelCastillo** [comment]
Oh absolutely, my bad!
I am using a Browser version that is seemingly hosted by my company, but apparently they haven't updated it. I thought they were using the latest version already. Sorry!
