### ISSUE TITLE
Feature request: Connection string in HTML console

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#142]
_From @cosimosimeoneTR on November 5, 2015 12:50_

I found myself working with many DB installations.
When working with HTML console, it's impossible to tell which instance the browser tab is about DEV, BUILD, PROD, ...

_Copied from original issue: neo4j/neo4j#5842_

**Comment by oskarhane** [comment]
_From @jakewins on December 5, 2015 4:17_

@cosimosimeoneTR what do you mean when you say "HTML console"? Are you referring to the Neo4j browser?

**Comment by oskarhane** [comment]
_From @cosimosimeoneTR on December 9, 2015 14:0_

Yep, exactly.
HTML title is just "neo4j", might be better something like
```
neo4j - neo4j@127.0.0.1:7474
```
as in
```
neo4j - user@host:port
```

**Comment by cosimosimeoneTR** [comment]
Hi there! Any news? :-)

**Comment by cosimosimeoneTR** [comment]
Hi there! Any news? :-)

**Comment by oskarhane** [comment]
Thanks for reminding us @cosimosimeoneTR, there's now a pr open: https://github.com/neo4j/neo4j-browser/pull/232
