### ISSUE TITLE
Graph Guides - UI Issues

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j-browser#1421]
### Description
Testing graph guides, which were written to exist in the main and wider browser area with the queries in the new sidebar results in some small UI issues. 

Specifically, testing with these guides:

```
:guide https://guides.neo4j.com/graph-examples/drug-repurposing-by-hetnet-relationship-prediction-a-new-hope/graph_guide
```

```
:guide https://guides.neo4j.com/graph-examples/exploring-the-star-wars-social-network/graph_guide
```

* bullets don't look right

<img width="1061" alt="Screen Shot 2021-05-28 at 1 32 06 PM" src="https://user-images.githubusercontent.com/2731744/120022329-43f6c480-bfba-11eb-87ec-fe54090c9d3c.png">

* images were expecting a white background - dark text isn't visible

<img width="1174" alt="Screen Shot 2021-05-28 at 1 32 40 PM" src="https://user-images.githubusercontent.com/2731744/120022356-4f49f000-bfba-11eb-8d5a-681f65fb34a6.png">

* Images were expecting a wider area - perhaps should shrink larger images? 

<img width="710" alt="Screen Shot 2021-05-28 at 1 35 14 PM" src="https://user-images.githubusercontent.com/2731744/120022381-55d86780-bfba-11eb-9f73-c8c3607dda31.png">

### Reproduce Steps

Run the following queries and click through the resulting guides in the new guide sidebar:

```
:guide https://guides.neo4j.com/graph-examples/drug-repurposing-by-hetnet-relationship-prediction-a-new-hope/graph_guide
```

```
:guide https://guides.neo4j.com/graph-examples/exploring-the-star-wars-social-network/graph_guide
```

### Expected Behavior

* guide bullets should not have an extra linebreak
* images should be able to look right (background, size) in the sidebar guide view and the main view

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Mac
| Web browser    |  Neo4j Desktop Version 1.4.5 (1.4.5.55)
| Neo4j Browser  | Neo4j Browser version: 4.2.6
| Neo4j          | 4.2.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.

**Comment by OskarDamkjaer** [comment]
Thanks for taking the time to report this, in the 4.3.1 release we'll have a fix in place for the list items being off. Image background and sizing is up to the guide author to update to a format that works well in the sidebar, this is one of the main reasons we've not removed/deprecated the old :play command just yet!
