### ISSUE TITLE
Profiling stats are wrong after first execution

### ISSUE THREAD

**Issue by alexabidri** [neo4j/neo4j-browser#1454]
This is a regression observed some months ago.

### Reproduce Steps
Write a first query with profiling assuming the property `name` is indexed

`PROFILE MATCH (n:Person { name: "superman"}) RETURN n`

Then modify the query for another field non indexed

`PROFILE MATCH (n:Person { title: "superman"}) RETURN n`

You will see at the bottom that the statistics of the profiling didnt change, it keep displaying the one from the first query.

### Expected Behavior
I should see the profiling statistics of the last query I have executed in the window

### Current Behavior

I see the profiling statistics of the very first time I executed the query.

### Can you propose a solution?
**Manual quick win**: Launch a query in a new window

**Fix**: update the data at the bottom of the window

PR => https://github.com/neo4j/neo4j-browser/pull/1455

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  macOS Big 11.4
| Web browser    |  
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 1.3.11
| Neo4j          | 4.2.4

**Comment by OskarDamkjaer** [comment]
Closing this as we merged your PR
