### ISSUE TITLE
Missing type decelerations in D3Visualization module.

### ISSUE THREAD

**Issue by RayLuxembourg** [neo4j/neo4j-browser#1477]
Would be easier to work with declared types for Props.
This module is complex and it would be easier to understand with types in place.

**Comment by OskarDamkjaer** [comment]
I agree! We used [ts-migrate](https://github.com/airbnb/ts-migrate) to automatically do the first step of migrating, we've not found the time give every file proper types yet but we're working towards it.

**Comment by OskarDamkjaer** [comment]
Should be mostly resolved with #1632
