### ISSUE TITLE
Textual formatting of duration values

### ISSUE THREAD

**Issue by thobe** [neo4j/neo4j-browser#1482]
https://github.com/opencypher/openCypher/issues/453

- **Neo4j version:** 4.1.1
- **API/Driver:** Neo4j Browser or Cypher shell

### Steps to reproduce

```
RETURN duration({months:0.75})
```

vs

```
RETURN toString(duration({months:0.75}))
```

### Expected behavior

Duration value should be formatted in a way fit for human consumption. (`P22DT19H51M49.5S`)

### Actual behavior

Duration value is formatted based on internal representation. (`P0M22DT71509.500000000S`)

**Comment by OskarDamkjaer** [comment]
Sorry about slow reply, I've fixed this in: #1523
