### ISSUE TITLE
Performance with big amounts of data returned per row

### ISSUE THREAD

**Issue by freeeve** [neo4j/neo4j-browser#149]
from 3.0.0's browser: getLineFromRow is freezing up the UI when I return very large rows. It seems like this might need some optimization. Alternatively, I don't even use the text tab--perhaps this could be lazily populated instead of holding me up from seeing my results?

![cpu-profile](https://cloud.githubusercontent.com/assets/882560/14964679/4b2b9098-1077-11e6-8c18-244958e3b52b.png)

**Comment by oskarhane** [comment]
Thanks @freeeve, we'll look into this

**Comment by freeeve** [comment]
Well, it's roughly an order of magnitude faster, which is a lot more bearable (thanks!), but it's still the slowest part of rendering a request that only takes 150ms for the server to return.

<img width="728" alt="cpu-profile-2" src="https://cloud.githubusercontent.com/assets/882560/16246379/fb5f67b4-37d2-11e6-8f0a-5e2cf95954b1.png">

**Comment by oskarhane** [comment]
This should now be fixed with https://github.com/neo4j/neo4j-browser/pull/242 and going out in the next release.
