### ISSUE TITLE
Easy add node button

### ISSUE THREAD

**Issue by emdax** [neo4j/neo4j-browser#1498]
NEO4J is the best data model prototyping tool ever. 
It would be even faster if the cool GUI had a simple button to quick add a node.
Right now it requires a lot of typing to build new query to add node.
Quick add node button would make playing in the GUI more fun and fast.

**Comment by OskarDamkjaer** [comment]
Thanks for the kind words and sorry about the slow response! While it's a fun idea it's not a feature we'll be prioritizing in the near future
