### ISSUE TITLE
Minified react error #152

### ISSUE THREAD

**Issue by process0** [neo4j/neo4j-browser#1575]
### Description

I received this error message when clicking an error message describing inability to connect to database:

`Something went wrong: "Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=k for the full message or use the non-minified dev environment for full errors and additional helpful warnings." and the application can't recover.`

### Reproduce Steps

Possibly double click database connection error. Has only happened once

### Expected Behavior

Application should not crash

### Current Behavior

Application crashes with error message above

### Can you propose a solution?

No

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Debian latest
| Web browser    |  Firefox-esr latest
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | Latest
| Neo4j          | Latest

**Comment by OskarDamkjaer** [comment]
I've not managed to reproduce this error, if you find some reliable reproduction steps, feel free to re-open
