### ISSUE TITLE
How did you made those graph animations?

### ISSUE THREAD

**Issue by Chetan11-dev** [neo4j/neo4j-browser#1666]
Could you link me to resources such as mdn docs where i can learn how to create those animated graph balls which I get when i run a cypher query such as (match (n) return n). They are really awesome.

**Comment by OskarDamkjaer** [comment]
Happy you like it! It's custom built on top of the [d3 library](https://d3js.org/) and the code is [here](https://github.com/neo4j/neo4j-browser/tree/master/src/browser/modules/D3Visualization). If you want to build something yourself I'd recommend using with some library built on top of d3, so you don't have to do the groundwork yourself! This [d3-graph-controller](https://graph-controller.yeger.eu/) library seems like a good start!
