### ISSUE TITLE
Bug: In single-line mode up/down key recalls history when not expected

### ISSUE THREAD

**Issue by ADTC** [neo4j/neo4j-browser#168]
In single-line mode, the typed command can wrap into multiple lines (it is still single-line mode because pressing Enter will execute the command, and the prompt shows `$`, not `1 2 3`).

It is natural to use the up/down arrows to move up and down the wrapped multiple lines (works fine and is an expected behavior in any normal text box). But in Neo4j browser, this recalls previously executed commands instead.

It wouldn't be so bad, if the browser saved the command I was editing (not yet executed), and I could recall the draft command by pressing the arrow in the opposite direction. But this is not the case. Often I have been really frustrated because I am editing a draft command and I (naturally) press an up/down key to move the cursor from line to line, but suddenly the whole command is gone and replaced with a previously executed command.

And the draft command is really _gone_, there's no way to get it back. I have to type out the command all over again. **It's really frustrating especially when I had done a lot of edits, and suddenly they are all lost.**

Ideally:
1. Drafted commands must be saved automatically and we should be able to recall them by moving past the end of history.
2. Moving cursor between lines in wrapped single-command mode must be supported. Only when I'm at the top line, and I press Up should it recall history. Otherwise, no! I don't expect history. I expect to be able to move the cursor around.
3. Adding to last point, being at the bottom line and pressing Down should **not** clear the text box.

**Comment by oskarhane** [comment]
Hi @ADTC and thank for you report.  
The intended behavior is that to walk in history in multi-line-mode you'd have to press `cmd` or `ctrl`.  
Just pressing arrow keys in multi-line-mode should move the cursor, not walk in history.

In single-line-mode pressing arrow keys will walk in history.

Are you saying that when you press arrow keys in multi-line-mode (without holding any modifier keys) you walk in history?
If so, that's not good.

What web browser and operating system do you use?

I agree that your current work shouldn't be lost when when walking history or pressing down.

**Comment by ADTC** [comment]
> Are you saying that when you press arrow keys in multi-line-mode (without holding any modifier keys) you walk in history?
NO! That's what I had been trying to make it clear in my report. Apparently my language was not good enough.
In multi-line-mode, the intended behavior works fine. I do have to press Ctrl to move through history. That is fine.

> In single-line-mode pressing arrow keys will walk in history.
This is where the problem is. It's fine that you are walking history when arrow keys (up/down) are pressed. But it conflicts with the wrapping of the line. If the "single line mode" is wrapped into multiple lines (note again, that this is **NOT** multi-line-mode), I should be able to move my cursor around without walking the history, until I'm at the top or bottom. Only at top or bottom, one more press should walk into history.

> What web browser and operating system do you use?
Firefox 46.0.1, Windows 10 Pro x64

> I agree that your current work shouldn't be lost when when walking history or pressing down.
I hope some form of draft saving mechanism will be implemented, at least. It will lessen the pain of walking history when I don't expect that.

**Comment by ADTC** [comment]
I noticed that a draft-saving mechanism does exist when I type a new command into a fresh empty line. Problem is if I walked the history and started making changes to a previous command from history, and I accidentally pressed up/down my changes are gone, and the original command from the history is recalled.

Also, attached is a screenshot to show what I mean by "multiple wrapped lines in single-line-mode". If the cursor is in the middle line (as shown), and I press up/down, I expect the cursor to move up or down one line. This is how standard textboxes behave everywhere. Try it when you type a reply in this issue. If I press up/down again and there are no more lines to move to, then and only then it should walk history. I hope you understand.

![Example of wrapping in single line mode](https://cloud.githubusercontent.com/assets/6047296/15356415/264f189c-1d2b-11e6-9b62-4d7f5be33536.png)

**Comment by oskarhane** [comment]
Ah, I see, I misunderstood what you meant.  
I agree that it would be a better experience if the behavior was what you suggest.  
I'll see what we can do about that in the coming versions.

**Comment by ADTC** [comment]
Can there be a Setting to force Ctrl requirement in both single line and multi line mode?

**Comment by OskarDamkjaer** [comment]
Currently the query is no longer lost when pressing up by mistake, so part of your issue is solved. We're hesitant to implement the ctrl requirement setting unless we see some broader demand for it.
