### ISSUE TITLE
Node count in the database-information-menu doesn't match the amount in the overview-menu of the cypher query

### ISSUE THREAD

**Issue by test123-all** [neo4j/neo4j-browser#1699]
### Description

Bug:
Node count in the database-information-menu doesn't match the amount in the overview-menu of the cypher query, that matches all nodes and returns them.

### Reproduce Steps
Return all nodes of one database

### Expected Behavior
I would expect that both numbers would be the same.

### Current Behavior
The numbers aren't the same.

![Screenshot_20220310_222705](https://user-images.githubusercontent.com/84460847/157758673-6af9df8b-44db-489f-a044-a875093f70e0.png)

The used cypher query:
`MATCH (n) RETURN n LIMIT 25000`
### Can you propose a solution?
No, sorry.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  KDE neon User - 5.24 (based on Ubuntu 20.04 focal)
| Web browser    |  Mozilla Firefox 97.0.2
| node.js        | -
| npm            | -
| yarn           | -
| Neo4j Browser  | 4.4.2
| Neo4j          | 4.4.4 (enterprise)

### Additional Information

- Neo4j is running from the official enterprise docker-image
- The APOC-plugin is installed

Any additional information, configuration or data that might be necessary to reproduce the issue.

### For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.
I don't know exactly which number is the right one. The difference between 5625 and 8574 is quite huge. I would like to have a more exact measurement value for speed testing purposes.

**Comment by test123-all** [comment]
## Important Addendum:
I noticed this morning how the number 8574 can be explained and that it is "probably right".

Some of the nodes in the database have multiple labels. The numbers on the right show how often the labels are present in the database. If I count the numbers together I exactly end up at 8574.

Is this intended? I expected the number of nodes.

I also noticed that the number of displayed nodes and relationships is written on the right to. But the number for the displayed relationships is 0. But there are displayed relationships?

**Comment by OskarDamkjaer** [comment]
Thanks for providing the extra info, it does look like we count number of labels on the right and number of nodes on the left, that's definitely confusing..

**Comment by OskarDamkjaer** [comment]
I've added this to our internal issue tracker, hopefully I can report back to you with progress soon! 😄

**Comment by test123-all** [comment]
Hey, no problem! :) 

Thanks, I would suggest to keep both values, since they can both be helpful at times. But making it somehow clearer what is meant

**Comment by test123-all** [comment]
Okay, thank you very much :) :+1:
