### ISSUE TITLE
Playing guides from URL fails despite CORS being enabled

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j-browser#170]
I am trying to play guides from URLs in the Neo4j 3.0.1 Community browser.

The specific browser command I am using to troubleshoot is:

```
:play https://gist.githubusercontent.com/dhimmel/83829c940d1b118af775c8e9ac6746a1/raw/81c93e06b168f70da8511b9109a170ee636ed23d/clofarabine-MS.html
```

Prior to setting `browser.remote_content_hostname_whitelist=*` in `conf/neo4j.conf`, I was getting the following error as expected:

```
Requested host is not whitelisted in browser.remote_content_hostname_whitelist.
```

However, now that I have whitelisted all remote content hosts, I get the following error:

```
No 'Access-Control-Allow-Origin' header is present on the requested resource and can therefore not be played.
```

However, [the URL](https://gist.githubusercontent.com/dhimmel/83829c940d1b118af775c8e9ac6746a1/raw/81c93e06b168f70da8511b9109a170ee636ed23d/clofarabine-MS.html) I'm playing the guide from appears to include `Access-Control-Allow-Origin:*` in its response header. Hence, I think we may have a bug on our hands. 

CCing @jexp who first [mentioned guides](http://stackoverflow.com/a/37377745/4651668) to me.

***

Note: I originally posted this issue on the `neo4j/neo4j` but am now moving it here. Hence, this post closes neo4j/neo4j#7227.

**Comment by dhimmel** [comment]
Here are the [relevant lines](https://github.com/neo4j/neo4j-browser/blob/eb49e41ec23f7420d23cdc67d28d5f7516f9a78d/app/scripts/services/Frame.coffee#L121) in `app/scripts/services/Frame.coffee`:

```coffee
#This happens on remote requests when no 'Access-Control-Allow-Origin' is present.
if result.is_remote and result.status is 0
  result = {errors: [{code: 0, message: "No 'Access-Control-Allow-Origin' header is present on the requested resource and can therefore not be played."}]}
```

Is there any chance that `result.status` could be 0 for a reason other than a lacking `Access-Control-Allow-Origin` header?

**Comment by dhimmel** [comment]
Just wanted to migrate @jexp's [comment that](https://github.com/neo4j/neo4j/issues/7227#issuecomment-221736261):

> The CORS stuff is really tricky, I haven't found a clear way to tell which hosting works and which not.

@jexp do you know of any hosting that currently works? I'm planning on making ~200,000 guides -- each one highlighting the [therapeutic potential](https://thinklab.com/discussion/predictions-of-whether-a-compound-treats-a-disease/2030) of a compound to treat a disease. First, I'll generate the asciidocs and then convert them to HTML using [`jexp/neo4j-guides`](https://github.com/jexp/neo4j-guides). And in the meantime is there a way to play a guide locally?

**Comment by jexp** [comment]
The http scripts in neo4j-guides allow that. If you host your guides yourself you can use the same headers

Von meinem iPhone gesendet

**Comment by oskarhane** [comment]
@dhimmel When trying to `:play` your guide, I see that the server responds to the preflight OPTIONS request with `Request header field Pragma is not allowed by Access-Control-Allow-Headers in preflight response`.  
What this means is that the server does not allow our CORS request due to we're sending disallowed headers .

As a matter in fact, no header seems allowed since the response is missing the `Access-Control-Request-Headers`.

You can try with curl like this: `curl -I -s -X OPTIONS -H "Access-Control-Request-Method: GET" -H "Access-Control-Request-Headers: accept, cache-control, if-modified-since, pragma, x-stream" -H "Origin: www.example.com" https://gist.githubusercontent.com/dhimmel/83829c940d1b118af775c8e9ac6746a1/raw/81c93e06b168f70da8511b9109a170ee636ed23d/clofarabine-MS.html`.

One can argue that we send too many headers here, and we should probably fix that, but your issue would still remain.

I would recommend Amazon S3 for hosting guides. There's a option there to set your own CORS settings.  
This is the config we use for our guides hosted there:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by dhimmel** [comment]
Thanks @oskarhane. Let me see if I understand -- the following curl command simulates the request made by the Neo4j Browser to retrieve a remote guide.

```shell
curl \
  --head \
  --request OPTIONS \
  --header "Access-Control-Request-Method: GET" \
  --header "Access-Control-Request-Headers: accept, cache-control, if-modified-since, pragma, x-stream" \
  --header "Origin: www.example.com" \
  https://gist.githubusercontent.com/dhimmel/83829c940d1b118af775c8e9ac6746a1/raw/81c93e06b168f70da8511b9109a170ee636ed23d/clofarabine-MS.html
```

The response to the above curl command contains the following header:

```
HTTP/1.1 200 OK
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000
ETag: "4679eb5e8573ccc7b851289e13c5d5ed50093cb0"
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
X-GitHub-Request-Id: C71B4F26:1E64:E93B00:57473986
Content-Length: 3662
Accept-Ranges: bytes
Date: Thu, 26 May 2016 17:59:34 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-lax1438-LAX
X-Cache: MISS
X-Cache-Hits: 0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: fbfe8afa78f0173fb28b40d97868b2d48d1c4b5f
Expires: Thu, 26 May 2016 18:04:34 GMT
```

Since this header is missing a `Access-Control-Allow-Headers` field, cross-origin resource sharing is not allowed. In other words, your post [should](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#Headers "The HTTP headers that relate to CORS") say:

> As a matter of fact, no header seems allowed since the response is missing the ~~`Access-Control-Request-Headers`~~`Access-Control-Allow-Headers`.

So it seems like there's not an [easy solution](http://stackoverflow.com/questions/13146892 "Cors Access-Control-Allow-Headers wildcard being ignored?") to make the remote host allow any headers. Although your Amazon S3 config does include a wildcard option (`<AllowedHeader>*</AllowedHeader>`)?

So we can use Amazon S3 or is there a way to include the guides in the instance and avoid having to make a cross-origin request?

**Comment by oskarhane** [comment]
> Since this header is missing a Access-Control-Allow-Headers field, cross-origin resource sharing is not allowed (given the request includes headers). In other words, your post should say

You're right.

> So it seems like there's not an easy solution to make the remote host allow any headers.

As the answer in the link says, the common thing to do is to reflect the headers from the incoming request.

> So we can use Amazon S3 or is there a way to include the guides in the instance and avoid having to make a cross-origin request?

Yes, S3 will work fine, try `:play http://guides.neo4j.com/reco` if you like, it's hosted there. Sorry, no way of include the guides to get away from cors at the moment.
I'm not sure what amazon does, maybe a `*` in the config in practice means that they just reflect the requests headers.

**Comment by dhimmel** [comment]
Got it -- thanks @oskarhane. It looks like I have at least three options:

1. Host the guides from within the Neo4j instance. See [the neo4j-guides guide-extension](https://github.com/jexp/neo4j-guides/tree/f8123837c14ebc4ca3d9426caa55feae378f6e6a/guide-extension) by @jexp.
2. Host guides on Amazon S3 using the [CORS settings](#issuecomment-221791023) that work for `http://guides.neo4j.com/reco`
3. Host a small python webserver to serve the guides with the proper `Access-Control-Allow-Headers` fields. See [example in `jexp/neo4j-guides`](https://github.com/jexp/neo4j-guides/blob/f8123837c14ebc4ca3d9426caa55feae378f6e6a/http.py#L8).

Feel free to close this issue, if you think we've addressed it to its fullest extent.

**Comment by oskarhane** [comment]
I think that sums it up quite well. Thanks for all input and questions.

**Comment by zeluspudding** [comment]
I've created a guide and am running into the same problem when I try to play it from my cloud host:
`No 'Access-Control-Allow-Origin' header is present on the requested resource and can therefore not be played.`

I haven't messed with CORS since it appears guide-extension support [is in place for Neo4j 3.x](https://github.com/neo4j-contrib/neo4j-guides/issues/2). My setup:
 - I'm on Win7 64
 - The Guide-extension JAR file from [here](https://github.com/neo4j-contrib/neo4j-guides/blob/f8123837c14ebc4ca3d9426caa55feae378f6e6a/guide-extension/readme.adoc) is in the plugins directory
 - My `neo4j.conf` (note - I don't have a file named `neo4j-server.conf`) looks like:
```
# My custom configurations
browser.remote_content_hostname_whitelist=*
# Configure the guide-extension
# dbms.unmanaged_extension_classes=extension.web=/guides
# org.neo4j.server.guide.directory=data/guides
```

I currently have those last two configurations commented out because if I don't I get this error:
```
Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-50a1bcc4@643c6b51==org.neo4j.server.web.NeoServletContainer,-1,false 
```
So trying to fetch the guides locally isn't working either. I know `:play http://guides.neo4j.com/reco`  works for me so I'm kinda scratching my head. What am I missing? Do I need to be running Neo4j Enterprise for this functionality?

**Comment by opensource21** [comment]
Simplest solution for me when I work complete at localhost was to use the Chrome-Extension _CORS Toggle_. Then you can disable cors.

**Comment by veleritas** [comment]
I was running into this same issue with a Neo4j server hosted on Amazon EC2. I managed to solve it by providing an explicit IPv4 address in the configuration file.

Relevant changes:

In `conf/neo4j.conf`:

```
browser.remote_content_hostname_whitelist=*
browser.post_connect_cmd=play http://<explicit IP address of my EC2 instance>:<port #A>/<path to guide>
```

1. Put all your files for your guide in the `data/guides/` folder
2. Modify `data/guides/http-server.py` in `main()` to: `HTTPServer(('0.0.0.0', <port #A as above in neo4j.conf>), CORSRequestHandler).serve_forever()`
3. Run `python3 http-server.py` after starting the Neo4j server
4. Connect to your EC2 instance as normal.

It seems that providing the explicit EC2 IP address bypasses the CORS issue.

**Comment by Khazl** [comment]
I run neo4j Version: 3.3.2 in a docker container and tried to configure a default style as described above.
- Grass file is accessable via HTTP (http://domain.com/resources/style.grass)
- CORS rules are set
- Command added to config: `browser.post_connect_cmd=style http://domain.com/resources/style.grass`

When i start my container with this config and run `match (n) return n` i see nothing.
Then i run :style http://domain.com/resources/style.grass and it works... Why? It seems that there is an error with the default style configuration.
Do you have any tips to debug this? The logs are clean.
