### ISSUE TITLE
Allow multiple post-connect commands in neo4j.conf

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j-browser#172]
Pull request #152 enabled auto-executing a command when opening a new Browser. The command is specified in `neo4j.conf` using the `browser.post_connect_cmd` setting. It would be nice to be able to specify multiple commands that would become multiple frames.

My current use case is:
1. auto-applying a style (see #171)
2. auto-playing a guide describing our network

I also plan to make use of the URL parameter API to play a guide on load (like `http://neo4j.het.io/browser/?cmd=play&arg=cypher`, see #153). However, these features differ in scope, I just wanted to mention the URL parameter API, which may suit some needs.

**Comment by oskarhane** [comment]
I can clearly see the use case here, thanks. I'll add it to our backlog.

**Comment by oskarhane** [comment]
Oh, I forgot to update this issue. There is now support for multiple commands in `browser.post_connect_cmd`.
See https://github.com/neo4j/neo4j-browser/pull/548 for info
