### ISSUE TITLE
Browser unable to show relationships in the graph under "Database Information" drawer

### ISSUE THREAD

**Issue by rishabhjain08** [neo4j/neo4j-browser#173]
If the relationship has a " (double quote) in its name then the browser is unable to show the relationships under the database information drawer.
This is happening because broser is unable to parse the data returned by /db/data/relationship/types to a JSON since the double quotes in relationship types are not escaped before sending to the client. 
The same thing DOES NOT happen with node labels.

**Comment by oskarhane** [comment]
Thanks, I'll add this to our bug backlog.

**Comment by oskarhane** [comment]
This is fixed in the later versions of the browser.
![oskar4j 2017-06-27 at 11 14 32](https://user-images.githubusercontent.com/570998/27580066-de5a875e-5b29-11e7-8deb-f486f01f5507.png)
