### ISSUE TITLE
Backticks not escaped in auto-generated statements 

### ISSUE THREAD

**Issue by rishabhjain08** [neo4j/neo4j-browser#174]
Sometimes node labels or relationship names may contain characters which need to be escaped before being sent to the server. Browser automatically creates queries when I click on the label name or relationship type in the "Database Infromation" drawer. Looks like all the characters in the auto-generated queries are being escaped properly except backticks.

**Comment by oskarhane** [comment]
Good find, thanks. I'll add it to our bug backlog.

**Comment by oskarhane** [comment]
This is fixed, we just forgot to close this issue.
