### ISSUE TITLE
Feature request: Allow parameterization in browser

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j-browser#175]
A Neo4j browser query might look like this:

CREATE (n:person {name: "Joe Smith"})

However, Neo4j queries sent through the API usually look like this, because of the advantages of parameterization:

CREATE (n:person {name: {x}}) {x: "Joe Smith"}

I don't think the neo4j browser supports this format, so queries from an application have to be rewritten for the browser. Could support for parameterized queries be added? Thanks.

**Comment by oskarhane** [comment]
Fixed with https://github.com/neo4j/neo4j-browser/pull/218
