### ISSUE TITLE
Editing style in browser didn't work

### ISSUE THREAD

**Issue by touseef306** [neo4j/neo4j-browser#1750]
After importing the grass file when I click on run I got an error as follows.
Neo.ClientError.Statement.SyntaxError: Invalid input 'n': expected <init> (line 1, column 1 (offset: 0))
"node {"
 ^

**Comment by OskarDamkjaer** [comment]
Do you have some simple instructions I could follow to recreate your problem?

**Comment by touseef306** [comment]
Issue resolved.
While saving I didn't select all files that's why it got saved as text, which off course will not work for styling.

**Comment by touseef306** [comment]
Issue resolved
