### ISSUE TITLE
Where is neo4j.conf for the standalone browser?

### ISSUE THREAD

**Issue by nacnudus** [neo4j/neo4j-browser#1778]
### Description

Hello, I am running the standalone browser as described [here](https://neo4j.com/docs/browser-manual/current/deployment-modes/dedicated-web-server/#pre-built-neo4j-browser), by downloading the .jar, unzipping it, and hosting it with a server.  I would now like to configure it with neo4j.conf, but where will it find that file?  There is no such place as `NEO4J_HOME` in this situation, because Neo4j itself has not been installed.

**Comment by OskarDamkjaer** [comment]
We read neo4j.conf values through the `dbms.listConfig()` neo4j procedure, so we need a connection to neo4j itself to use neo4j.conf settings
