### ISSUE TITLE
JMX MBean ObjectName should not be hardcoded

### ISSUE THREAD

**Issue by thobe** [neo4j/neo4j-browser#182]
The JMX query for getting the `sysinfo` data should not assume that the database kernel name is always `kernel#0`.

In [https://github.com/neo4j/neo4j-browser/blob/master/app/scripts/controllers/SysinfoController.coffee#L38-L44](SysinfoController) this is hard-coded, the base ObjectName should instead be retrieved from the server.

**Comment by oskarhane** [comment]
Ah, good catch. Thanks.

**Comment by eve-bright** [comment]
Fixed in https://github.com/neo4j/neo4j-browser/pull/208
