### ISSUE TITLE
websocket port can not change

### ISSUE THREAD

**Issue by jinmmd** [neo4j/neo4j-browser#183]
websocket port defaults to 7687, I can not change it.

neo4j.conf
> dbms.connector.bolt.address=0.0.0.0:8687

console log
> WebSocket connection to 'ws://x.x.x.x:7687/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by eve-bright** [comment]
Hi @jinmmd. There is a setting 'Bolt host' in the browser settings drawer which will allow you to manually change the websocket port that is being used by the browser.  We are working toward a more automated solution for this scenario but in the meantime, the workaround is to use the setting.
