### ISSUE TITLE
Missing space in "You are connected" message

### ISSUE THREAD

**Issue by stefano-ottolenghi** [neo4j/neo4j-browser#1834]
I observe a missing space in the connection message:

![Screenshot from 2022-10-10 14-29-41](https://user-images.githubusercontent.com/114478074/194866631-1de2bbfd-98f7-4f72-ae80-b754cba2f6a6.png)

this is due to a trailing space missing in https://github.com/neo4j/neo4j-browser/blob/master/src/browser/modules/Stream/Auth/ConnectedView.tsx#L44 , which when gets (possibly) concatenated with the host, it gets stitched together into `connectedto`. 

I can go on and submit a PR adding that space, unless there is a reason for that not being done? :)

**Comment by OskarDamkjaer** [comment]
Feel free to submit a PR! Reach out here on the issue if you run into any issues :)

**Comment by OskarDamkjaer** [comment]
Probably best to wait with closing the issue until we've actually fixed the issue 😅
