### ISSUE TITLE
How is neo4j Connect result nodes implemented?

### ISSUE THREAD

**Issue by ZshaoChuan** [neo4j/neo4j-browser#1909]
When this option is checked, the browser will display all the relationships of the nodes, While this works in the Neo4j browser, I cant quite get it to connect in Neo4j bloom. So question is whats the second query thats run to connect the result nodes under the hood? I wonder how this is achieved.
Thank you so much.

**Comment by OskarDamkjaer** [comment]
The cyphe query we run is approximately:
```cypher
MATCH (a)-[r]->(b) WHERE id(a) IN $existingNodeIds AND id(b) IN $existingNodeIds RETURN r;
```
With the `$existingNodeIds` parameter set to a list of all current ids (something like [1,2,3,4]).

[This](https://github.com/neo4j/neo4j-browser/blob/68599ed3514c2458f9d4a709e5e6bf31371a50aa/src/browser/modules/Stream/CypherFrame/VisualizationView/VisualizationView.tsx#L233) is where it's done in the code.

**Comment by ZshaoChuan** [comment]
Thank you very much for your answer!
