### ISSUE TITLE
Datetime function timezone issue when hour is 00

### ISSUE THREAD

**Issue by B-D-T** [neo4j/neo4j-browser#1919]
### Description  
The `datetime()` function appears to have an error when the time is between 12-1am. This does not happen everywhere, however, as it works as expected when using cypher-shell.

### Reproduce Steps  
Run a query trying to use `datetime()` to convert a time between midnight and 1:00am.

#### Expected Behavior  
With 1:00 am, the time zone returns as expected (-04:00): 
```lang-cypher
RETURN datetime('2023-05-30T01:00:00[America/New_York]')
// Expected: 2023-05-30T01:00:00-04:00[America/New_York]
// Actual:   2023-05-30T01:00:00-04:00[America/New_York]
```

#### Current Behavior
With anything in the 12:00am range, the time zone changes to +20:00:
```lang-cypher
RETURN datetime('2023-05-30T00:59:00[America/New_York]')
// Expected: 2023-05-30T00:59:00-04:00[America/New_York]
// Actual:   2023-05-30T00:59:00+20:00[America/New_York]
```

This happens when passing the individual components, too, and only happens with 12-1am. I've tried with several different years and days.
```lang-cypher
UNWIND range(0, 23) AS hr
RETURN datetime({year:2023, month:5, day:30, hour:hr, minute:0, second:0, timezone:'America/New_York'})
// All correct expect the first hour of the day.
```

# Environment information
- Database v5.8.0, Neo4j desktop client v1.5.7 on Windows 11
- Ran this in the Neo4j Browser to isolate the problem. It works when I run it in the Neo4j Terminal.

**Comment by OskarDamkjaer** [comment]
Hi! Thanks for debugging and reporting this! It looks very odd and since it works properly in cypher-shell, it's probably something wrong in either Browser or the javascript driver :+1:

**Comment by B-D-T** [comment]
Confirmed that this is still an issue on Neo4j Desktop v1.5.8 with the following configuration:

- Neo4j Browser version: 5.9.0
- Neo4j Server version: 5.4.0 (enterprise)
- Build number: 167
- Build date: 5/31/2023

I haven't bothered setting up a JavaScript driver connection, so I haven't been able to isolate whether it's a browser issue or a driver issue.

**Comment by OskarDamkjaer** [comment]
Hello @B-D-T! I forgot to give an update but we did investigate this and found it to be an issue with the driver.

https://github.com/neo4j/neo4j-javascript-driver/issues/1096 

I think the fix has since been merged to driver, but we're still behind a few versions on our end
