### ISSUE TITLE
Custom Favorites : re-execution mandatory to take name/comment into account 

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j-browser#1920]
### Description
Having executed a correct query, I want to add it as a favorite.
Therefore I add a comment in the first row.
Then "save as favorite"
As a result, I see the cypher in the favorites and not the comment I wanted to be used as name

### Reproduce Steps
Execute "MATCH (n) RETURN n LIMIT 10"
Click on the Cypher code in the newly created frame
Go to start of line, press SHIFT+Enter, your code is now on line two
Move cursor to line 1
Type "// something"
Click the Star button "Save as favorite"

Oh, the cypher appears in the "local scripts"

### Expected Behavior
Have the comment appear in the "local scripts"

### Current Behavior
the cypher appears in the "local scripts"

if I re-run the cypher from the frame, then clicking the star make the name/comment  appear correctly in the "local scripts"   

### Your Environment
Desktop 1.5.8

| software name  | version
| ---------------|----------
|                |  
| OS             |  linux 
| Web browser    |  firefox 113.0.2
| Neo4j Browser  | 5.6.0
| Neo4j          | 5.8.0

### Additional Information

Build number: 162
Build hash: 478b9b2c31f44dd05f
Build date: 21/03/2023

**Comment by OskarDamkjaer** [comment]
Hello! Thanks for reporting this, it would for sure be better if the query didn't need to be re-run to update a favorite. I'm not sure when I'll have the time to fix it, but I'll let you know once it is done!

**Comment by LucasBoberg** [comment]
This should now be fixed in the next release
