### ISSUE TITLE
[Logging] annotationData as json structure instead of java map toString() output

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j-browser#1926]
## Setup
Version: 5.6.0-enterprise
OS: any

Transaction metadata can be set for every transaction executed against neo4j from a client, for eg

```
chris@neo4j> :begin
chris@neo4j# CALL tx.setMetaData({app: 'my-app'});
0 rows
ready to start consuming query after 22 ms, results consumed after another 0 ms
chris@neo4j# MATCH (n) RETURN count(n);
+----------+
| count(n) |
+----------+
| 2403     |
+----------+

1 row
ready to start consuming query after 11 ms, results consumed after another 1 ms
chris@neo4j# :commit
chris@neo4j>
```

When query logging is enabled and configured to be logged as json format, this is the following output : 

```json
{"time":"2023-03-25 18:02:02.801+0000","level":"INFO","event":"success","type":"query","elapsedTimeMs":11,"allocatedBytes":176,"source":"bolt-session\tbolt\tneo4j-cypher-shell/v4.4.14\t\tclient/172.30.0.1:38856\tserver/172.30.0.2:7687>","database":"neo4j","username":"chris","executingUser":"chris","authenticatedUser":"chris","query":"MATCH (n) RETURN count(n);","queryParameters":"{}","runtime":"pipelined","annotationData":"{app: 'my-app'}"}
```

As you can see, the `annotationData` field of the json body contains a standard java output of the `Map::toString()` method, preventing common log query processors to access easily values inside that field as they're simple strings and we need to resort to regexes or even in log4j2 filters ( like here https://github.com/ikwattro/neo4j-log4j2-examples/blob/main/tx-metadata-filter/server-logs.xml#L50 ) where normally we could just filter on a nested field.

Expected : 

When json query logging is enabled, the value of the `annotationData` field should be a proper json object string, in this case : 

```
"annotationData": {"app:" "my-app"}
```

**Comment by OskarDamkjaer** [comment]
@ikwattro Hello! This was indeed caused by Browser, we made the background polling more efficient in `5.9.0` and this bug slipped in.

**Comment by klaren** [comment]
@ikwattro Just a heads up, the next release(5.12.0) will include a new setting based on additional feedback, `db.logs.query.annotation_data_format`, which will replace `db.logs.query.annotation_data_as_json_enabled`. 

Possible values for `db.logs.query.annotation_data_format`
* `CYPHER`: Formatted as a Cypher map. E.g. `{foo: 'bar', baz: {k: 1}}`. This is the default.
* `JSON`: Formatted as a JSON map. E.g. `{"foo": "bar", "baz": {"k": 1}}`.
* `FLAT_JSON`: Formatted as a flattened JSON map. E.g. `{"foo": "bar", "baz.k": 1}`.

If `db.logs.query.annotation_data_as_json_enabled` is set to true, it will be treated as `db.logs.query.annotation_data_format=FLAT_JSON` to preserve backward compatibility. This new setting will allow for greater flexibility and support more use cases.

**Comment by ikwattro** [comment]
Hi @klaren , great, I think its even better, I had to do some funny formatting in loki to handle `baz.k` ( nothing major, I was living happy with it )

Feel free to send me a snapshot of 5.12 over Slack so I can test it before ;-) 

Cheers

Christophe
