### ISSUE TITLE
Distribution download error: Error: net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by ajmeese7** [neo4j/neo4j-browser#1935]
### Description

My WiFi connection has been dropping out intermittently for very brief periods of time, often 3 seconds or less. Whenever this happens in the Neo4j Browser when I am attempting to download a different version of the DBMS to create a new project, I get errors like the following:

![Error messages](https://github.com/neo4j/neo4j-browser/assets/17814535/7f7c3a7d-f45d-4aa3-b38e-79a09b178f09)

### Reproduce Steps

If your WiFi connection is slightly unstable, a very short interruption in service or loss of connection will cause the download to fail completely.

### Expected Behavior

The app should be able to recover from a temporarily paused download where it left off, instead of failing completely and requiring a restart of the whole download. Much like the ability in Brave Browser (Chromium) to click "resume" when a download fails and it will pick up where it last left off.

### Can you propose a solution?

Don't have the time to attempt a PR at the moment, figured I'd make an issue for visibility in case someone is able to get around to looking at it before me.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows 11 Pro Insider Preview, Version 22H2, Build 23541.1000
| Web browser    |  N/A
| node.js        | v16.20.2
| npm            | 9.8.1
| yarn           | N/A
| Neo4j Browser  | 1.5.8
| Neo4j          | 5.3.0 (attempting to download 5.11.0)

### Additional Information

The following is my `log.log` file from the `.Neo4jDesktop` folder:

[log.log](https://github.com/neo4j/neo4j-browser/files/12580787/log.log)

**Comment by OskarDamkjaer** [comment]
Hello and thanks for the error report & repro steps. This is an issue with Neo4j Desktop rather than Neo4j Browser and the best way to report desktop issues is at [canny](https://feedback.neo4j.com/desktop).
