### ISSUE TITLE
Outdated changelog

### ISSUE THREAD

**Issue by diyoyo** [neo4j/neo4j-browser#1942]
### Description
Clicking on the link to changelog in neo4j-browser shows an outdated wiki page

### Reproduce Steps
- Go to `About Neo4j ` and look for words "You are running"
- Click on "Changelog"

![image](https://github.com/neo4j/neo4j-browser/assets/6624639/ca35b9a2-6df0-4f4b-84d3-43106a76bc56)

### Expected Behavior
- Changelog up to date (here for version 5.12.0)

### Current Behavior
- 2-years old changelog

![image](https://github.com/neo4j/neo4j-browser/assets/6624639/a9b84071-d313-406d-bec6-2470b1d37e40)

### What needs to be done to address this issue? Ideally, provide a pull request with a fix.
Update the old changelog or change the link to an up-to-date document.

### Your Environment
Running on Neo Desktop for Mac (latest everything)

**Comment by OskarDamkjaer** [comment]
Thanks for reporting this, opening a PR to fix it today :)
