### ISSUE TITLE
How to pack Neo4j Browser and include the dist folder?

### ISSUE THREAD

**Issue by tweirick** [neo4j/neo4j-browser#1969]
### Description
I want to install a customized version of Neo4j Browser locally. From what I understand, I should be able to install a packed tgz file in Neo4j Desktop. I have tried `npm pack` and `yarn pack`. `npm pack` builds something similar to [neo4j-browser-5.15.0.tgz](https://github.com/neo4j/neo4j-browser/releases/download/5.15.0/neo4j-browser-5.15.0.tgz), except that the dist/ folder is missing. 

Are there arguments I am missing when running `npm pack`? I tried deleting dist from the .gitignore file and this did not change anything. 

### Reproduce Steps

`yarn install`

`yarn start # Tested and works`

`npm pack`

### Environment
Ubuntu 22.04

**Comment by OskarDamkjaer** [comment]
I've not used the `npm pack` command, but at a quick glance it seems what's missing is running `yarn build` command as this creates the `dist` folder

**Comment by tweirick** [comment]
Thanks for your help. Running `yarn build` in the release tar file [5.15.0](https://github.com/neo4j/neo4j-browser/releases/tag/5.15.0) built dist successfully.  

Note: I initially had trouble with the latest version of yarn. Using yarn@1.22.16 built the dist successfully.
