### ISSUE TITLE
Neo4j browser editor should be resizeable

### ISSUE THREAD

**Issue by thedomeffm** [neo4j/neo4j-browser#1980]
### Description
Make the editor input resizeable.
When I am prototyping my new queries in the neo4j browser they can get very large... like 100+ LOCs

But the editor just shows 12 lines and it is not possible to resize the window.

### Expected Behavior
It should be resizeable.

### Your Environment

| software name  | version
| ---------------|----------
| Neo4j Browser  | 5.21.0

**Comment by OskarDamkjaer** [comment]
I think it'd make sense to make the editor resizeable, what you can do today is to make it fullscreen to get more space

**Comment by daveajrussell** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cancel saved cypher edit should discard changes](https://trello.com/c/3V7hbLGV/1172-cancel-saved-cypher-edit-should-discard-changes)
