### ISSUE TITLE
Neo4j browser editor should use the "default" text cursor

### ISSUE THREAD

**Issue by thedomeffm** [neo4j/neo4j-browser#1981]
### Description
The current cursor that the neo4j browser editor use is like the replace cursor that is often used in other OS.
Can the browser please switch or at least make it configureable to use the default "|" cursor instead of the weird replace block cursor.

It is funny to see that the monaco editor by default is using the text cursor. But the Neo4J browser has changed it?
=> https://microsoft.github.io/monaco-editor/

### Your Environment

| software name  | version
| ---------------|----------
| Neo4j Browser  | 5.21.0

**Comment by OskarDamkjaer** [comment]
We've been working on a new cypher editor, which has a more sensible cursor. It'll be available as part of a preview of a modernized Neo4j Browser this year and you can use it today already in aura / the cloud console
