### ISSUE TITLE
Feature request: edge/node-type specific alpha transparency

### ISSUE THREAD

**Issue by cgreene** [neo4j/neo4j-browser#275]
**Use case**: I frequently need to make presentations to disseminate our results and findings. This involves highlighting, at various times, different parts of a network.

**Problem**: I can change some visualization properties, however not the ones that would be most useful to me for highlighting specific node and edge types. A flexible way to display and/or highlight only certain node types would be to allow setting alpha in addition to color, size, and caption in the visualization selector.

![screenshot from 2016-10-11 09-06-02](https://cloud.githubusercontent.com/assets/542643/19271331/421fa1f2-8f92-11e6-8497-d70336373d50.png)

**Comment by dhimmel** [comment]
@cgreene are you envisioning that the alpha for a node or edge also affects the transparency of the text label?

**Comment by cgreene** [comment]
@dhimmel : in the ideal world, yes. I'd also be fine with being able to disable the text label if that got me easier alpha transparency.

**Comment by oskarhane** [comment]
I like this and I definitely can see the use case here. 
I'll add it to our backlog but cannot make any promises when it will be implemented or if it will be implemented in some other way since the user goal here is really to highlight certain parts of the visualization.

**Comment by OskarDamkjaer** [comment]
As it's not been seen as high priority enough to get added in the past four years, it's likely it will never be done. If we see renewed interest for this kind of feature or happen to work on some visualization improvement it might be get picked up. Thanks for the idea!
