### ISSUE TITLE
Authentication Failure in the browser only, success otherwise

### ISSUE THREAD

**Issue by mattfiocca** [neo4j/neo4j-browser#280]
I'm getting an authentication error when trying to connect via the neo browser:

```
The client is unauthorized due to authentication failure. (ID:3F07571939120DB3905D8D08F1A7366A4AC6A49B2AC3F43AFA76A7AEAF221DB3)
```

However, our applications can connect and make requests all day through the APIs using the same credentials that we are trying here in the browser.

Are there any server configs that I may be missing for this? Here are our versions.

Neo4j Version 3.0.1
Browser Version 2.0.0-M04

**Comment by oskarhane** [comment]
Hi @mattfiocca,
Browser 2.x not guaranteed to be compatible with Neo4j 3.0.x (at least not over Bolt).

What you could do is one of:

- Use Browser 2.0.0-M04 and disable Bolt in the Browser settings  
or
- Use Browser 1.1.9 (released last week)

**Comment by mattfiocca** [comment]
Unchecking bolt for 2.0.0 did the trick!

Thanks
