### ISSUE TITLE
Properties Persist after Detach/Delete

### ISSUE THREAD

**Issue by lothomas17** [neo4j/neo4j-browser#290]
Neo4J Version: 3.1.0 Beta 1
OS: Mac OSX 10.10

After running a detach delete on a large dataset, the nodes and relationships were deleted, but the sysinfo page still shows that there are ~1.5 Million entries. There is no way to view these that I have found, and queries to the database claim that it is an empty database.

**Comment by oskarhane** [comment]
Hi,
The Neo4j Browser just consumes the data coming from the jmx endpoints from the Neo4j server.

I suggest you open an issue in the [neo4j repository](https://github.com/neo4j/neo4j/issues) to get some eyes on it.
