### ISSUE TITLE
Dark theme renders text unreadable in browser console

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j-browser#318]
In the browser, I loaded the example movie database and executed the first CREATE query. Then while viewing the query results below, I switched to the "text" tab, the results were not readable. This happened when I had the "dark" theme selected in settings. When I switch to "normal" theme, the text is readable again (screenshots included).

- Neo4j version: 1.1.8 (Neo4J Browser), 3.0.6(Neo4J CE)
- Operating system: macOS Sierra
- API/Driver: Cypher
- Browser: Google Chrome ver 54.0

## Steps to reproduce

1. Login to the browser console on http://localhost:7474/browser/
2. Load the sample movie database, and execute the first "create" query
3. When the results load, switch to the "text" tab.

## Expected Behavior
The text should be readable (as in the normal theme) -

![830cc628-a369-11e6-809b-141bf40e9dd4](https://cloud.githubusercontent.com/assets/11348778/20042582/964a500c-a44a-11e6-98e7-24881862b6fe.png)

## Actual behavior

The text is unreadable in dark theme -

![9631ebe8-a369-11e6-8c54-6fd2a90a12ea](https://cloud.githubusercontent.com/assets/11348778/20042586/a8a73a12-a44a-11e6-9402-691315142adf.png)

Formerly in https://github.com/neo4j/neo4j/issues/8316

**Comment by oskarhane** [comment]
Yes, you're correct. Thanks, we'll get this fixed.

**Comment by noppanit** [comment]
I believe this is fixed in the latest?

**Comment by ATGardner** [comment]
I'm not sure if there was any regression lately, but today I ran the latest docker image (I think it is 3.2.5), and in the dark theme I can't see the result table.
