### ISSUE TITLE
Caption list cut off in Neo4j 3.1 Beta 3 (Browser M06)

### ISSUE THREAD

**Issue by heavydawson** [neo4j/neo4j-browser#319]
![image](https://cloud.githubusercontent.com/assets/2285843/20143691/ebd7b386-a691-11e6-94e4-f4631e77dab5.png)
For the node above there are at least twice as many captions available as can be accessed here. Using Chromes development tools I can see the HTML elements are indeed there, just clipped.

**Comment by oskarhane** [comment]
Thanks for the report on the @heavydawson! We'll make sure it gets fixed.
