### ISSUE TITLE
Fixed Column Headers for Rows

### ISSUE THREAD

**Issue by whitfa99** [neo4j/neo4j-browser#331]
Hi there,

Is there any way to make the column headers stay visible when scrolling down through the output of rows?  
I find it a bit cumbersome having to highlight the row I'm on then scroll to the top to find out the column header then scroll back down to my highlighted row etc.  When working with any dataset bigger than a page and when it's not obvious by the output which column is which I find it very awkward to use.  

I think it would be fantastic to have the column header row fixed or be able to pin it, which would make it behave more like a spreadsheet or database IDE.

What do you think?

Adrian

**Comment by OskarDamkjaer** [comment]
Thanks for opening this issue and sorry for taking this long to get back to you. It seems we've solved this problem over the years, so I'm closing this issue. If there's something else you'd like to see in browser, feel free to add a feature request at  [canny](https://neo4j-browser.canny.io/feature-requests)
