### ISSUE TITLE
Can call rest api and get some data then result can manipulate here in cypher query??

### ISSUE THREAD

**Issue by cseppd** [neo4j/neo4j-browser#341]
I want to call a rest api when click play button and the result of the api, I create the cypher query to execute here. Plz help me..... 
When i want to call then a error occur : XMLHttpRequest cannot load http://localhost:9200/xxxx. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.

**Comment by oskarhane** [comment]
Is this still an issue @cseppd?
Your endpoint needs to send the right CORS headers for the web browser to call it.
Feel free to open is the issue remains.
