### ISSUE TITLE
Cloud Services session doesn't persist if you click on 

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j-browser#345]
After logging in to `localhost: 7474/browser`, sign in to your account using the "cloud services" tab. Next, if you click on the link shown in the `:play start` frame, something like - 

> Free online training, to level-up your Neo4j skills.

 The link opens in the same tab and you're logged out of your account that you signed in using "cloud services".

It would be nice if the user account is persisted when you click on recommended links.

**Comment by oskarhane** [comment]
This is now fixed with: https://github.com/neo4j/neo4j-browser/pull/641 and is coming in the next release.
