### ISSUE TITLE
When using bolt, graph view not available for relationships 

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j-browser#347]
In Neo4j 3.1.1 and with the "Do not use Bolt" unchecked (so using bolt), relationships returned by a query do not have the option of graph view. Instead, they only have the Rows, Text, & Code views. Here are three queries you can try at https://neo4j.het.io/browser/. The node and path queries do display the graph, but the relationship query does not.

```cypher
// node query (works)
MATCH (node) RETURN node LIMIT 1

// relationship query (does not work)
MATCH ()-[rel]-() RETURN rel LIMIT 1

// path query (works)
MATCH path = ()--() RETURN path LIMIT 1
```

I discovered this while doing a live demonstration of the Hetionet Browser in my [presentation](http://slides.com/dhimmel/big-data-seminar#/) :cry:!

As a workaround, you can disable bolt in the Browser Settings. But I believe the bolt is enabled by default for first time browsers? So lot's of confusion potential.

**Comment by oskarhane** [comment]
Hi @dhimmel. You're correct and I think this is the expected behavior (maybe @technige can confirm) and that's why we have updated the sidebar relationship queries to return the path: `MATCH p=()-[r:PARTICIPATES_GpCC]->() RETURN p LIMIT 25`.

Though being convenient the the "graph" REST format is sometimes misleading for the user and the Bolt format is more correct. If you return the relationship -> you get the relationship. If you return the path -> you get the path.

Btw, really cool project!

**Comment by dhimmel** [comment]
@oskarhane thanks for the info. So I guess the issue is that bolt relationship queries do not return sufficient information to completely render the adjacent nodes. They do however return the `startNode` and `endNode` ids. Accordingly, I get why graph view isn't available for relationships, but I think there are some things we should consider:

1. Not being able to visualize relationships in the Browser will reduce its utility and/or lead to inconveniences. I can think of many queries where path assignment is not a workaround. The `startNode()` and `endNode()` functions, although sometimes unwieldy, will have to be used a lot. In general, exploratory Cypher queries will get more ugly and difficult to write.

2. The Browser already retrieves additional information to make the Graph view more useful. Specifically, auto-complete fills in edges between visualized nodes. Shouldn't there be an option to fill in nodes for returned edges?

3. Lot's of queries that used to "just work" in the Browser, no longer work as expected.

So I agree that while it's not appropriate for bolt to return node information that is not queried. However, I do think there's opportunity for the Browser to be smart and visualize relationships. This would be a value-added feature by the browser and not a innate feature of bolt. Not sure of exactly the right solution -- it will definitely require some thought!
