### ISSUE TITLE
Allow calling guides by namespaced name

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-browser#352]
Currently, the only existing method, afaik, to call custom guides is via URI.
It would be nice if calling by name was allowed.

Namespaces could be made mandatory to avoid name collisions.

**Comment by oskarhane** [comment]
Thanks for this suggestion. 
Does https://github.com/neo4j/neo4j-browser/pull/483 cover your request?

**Comment by fbiville** [comment]
👍 nice!! And I see it's merged, perfect 🍾

**Comment by oskarhane** [comment]
👍
