### ISSUE TITLE
Preact / React - dynamic webpack configuration

### ISSUE THREAD

**Issue by gurkerl83** [neo4j/neo4j-browser#371]
Nice to see the component is moving from angular to preact. Maybe someone could highlight the motivation behind the migration. 

As this project is a full stacked application, it is rather unlikely to see this gets pushed to npm. Anyway, it would be very cool if this application can be somehow reutilized as a component / module in an arbitrary third party application e.g. through a git-submodule integration process. 

What are the reasons for selecting preact in favor for react, is it the size of the preact library?
I`m curious to know if there are performance reasons why you have selected preact. Does preact provide certain features which are highly relevant in the neo4j-browser but are not available in react? 

My intention is that the preact community is growing, but the react community is by far larger.

The documentation about preact says that preact-compat dependencies are switchable in the webpack configuration.

`
{
  "resolve": {
    "alias": {
      "react": "preact-compat",
      "react-dom": "preact-compat"
    }
  }
}
`

Is it an appropriate estimation to provide a dynamic alias dependency resolution to allow the developer to choose which framework gets used in the build process.

Thanks!

Cheers, Markus

**Comment by oskarhane** [comment]
I understand the motivation for this, but since a time back we have moved to React.

To summarize why we chose preact over react: React's license at the time being.
Why we're moving to React now: Innovation and a more safe bet for the future.
