### ISSUE TITLE
Setting initialState "bolt" value in src does not auto-populate `:server connect` Host box

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j-browser#503]
I added the `bolt.address.com` that I want to be included in a build of neo4j-browser, instead of adding it via `:config bolt:` command (which isn't global to all users)

However, it does not populate the Host box in `:server connect`. Is there another way to do this?

Before:
```
const initialState = {
  cmdchar: ':',
  maxHistory: 30,
  theme: 'normal',
  useBoltRouting: false,
  initCmd: ':play start',
  initialNodeDisplay: 300,
  maxNeighbours: 100,
  showSampleScripts: true,
  browserSyncDebugServer: null
}
```
After:
```
const initialState = {
  cmdchar: ':',
  maxHistory: 30,
  theme: 'normal',
  useBoltRouting: false,
  initCmd: ':play start',
  initialNodeDisplay: 300,
  maxNeighbours: 100,
  showSampleScripts: true,
  browserSyncDebugServer: null,
  bolt: 'bolt.address.com:7687'
}
```
https://github.com/naisanza/neo4j-browser/blob/3.0/src/shared/modules/settings/settingsDuck.js#L49

Results running neo4j-browser `:config`:
```
{
  "cmdchar": ":",
  "maxHistory": 30,
  "theme": "normal",
  "useBoltRouting": false,
  "initCmd": ":play start",
  "initialNodeDisplay": 300,
  "maxNeighbours": 100,
  "showSampleScripts": true,
  "browserSyncDebugServer": null,
  "bolt": "bolt.address.com:7473"
}
```

And it does not populate the `:server connect` Host box:

![screenshot from 2017-05-03 05-57-47](https://cloud.githubusercontent.com/assets/1614425/25656152/ac35b792-2fc5-11e7-9adf-c741fb66a480.png)

**Comment by oskarhane** [comment]
Hi,

Commands starting with `:` is not Cypher. They're never sent to the database at all, they're client side commands that Neo4j Browser interprets and acts upon.

Host for connections are not stored in the settings in the global state. There's a separate place in the global state where the connection information lives and that cannot be manipulated through any commands.

In the case of Neo4j Browser being served from a Neo4j Server, a GET request to `/` with `Content-Type: application/json` is sent. That response is expected to be in JSON format and look like this:

```
{
  "bolt":"bolt.address.com:7687"
}
```

and if a `bolt` field is found, the host field on the connection frame is populated with that.
So if you could setup a listener on your web server that responds in the above format you have solved your problem.

**Comment by naisanza** [comment]
@oskarhane I see so it's the `bolt` value that populates the host field, and not the `host` field (never would have guessed that, since "host" => "host" made more sense than "bolt" => "host")

Thanks for correcting me on the Cypher vs Browser commands (I should have caught that one)

**Comment by naisanza** [comment]
@oskarhane I've updated the source file (https://github.com/neo4j/neo4j-browser/blob/3.0/src/shared/modules/settings/settingsDuck.js#L55) to include the `bolt` address when it builds with `yarn build`. And the `:config` output from neo4j-browser can be seen below, yet the `Host` field isn't populated.


`:config` output:
```
{
  "cmdchar": ":",
  "maxHistory": 30,
  "theme": "normal",
  "useBoltRouting": false,
  "initCmd": ":play start",
  "initialNodeDisplay": 300,
  "maxNeighbours": 100,
  "showSampleScripts": true,
  "browserSyncDebugServer": null,
  "bolt": "bolt.address.com:7687"
}
```

![screenshot from 2017-05-08 16-26-05](https://cloud.githubusercontent.com/assets/1614425/25823775/1293ee7a-340b-11e7-9972-c57c8a24d763.png)

**Comment by oskarhane** [comment]
Is this still an issue @naisanza?
You misunderstood me. The server responds with the `bolt` field, you cannot set it in the client settings like that.

If you want it hard coded, you change

```
const passedURL = getUrlParamValue('connectURL', action.url)
```

to

```
const passedURL = 'bolt.address.com:7687'
```

on https://github.com/neo4j/neo4j-browser/blob/3.0/src/shared/modules/discovery/discoveryDuck.js#L71

Feel free to open if issue still remains.

**Comment by naisanza** [comment]
@oskarhane that is perfect! Sounds like exactly what I needed! I'll have to test it out

I just didn't want to need to manually enter in the bolt server address when letting others log in, because it would be too complicated to tell them to put in a bolt address, and then their username and password
