### ISSUE TITLE
Error connecting to publicly accessible Neo4j bolt port "WebSocket `readyState` is: 3"

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j-browser#504]
When connecting neo4j-browser to a a neo4j bolt port I get the following WebSocket connection error:

```
N/A: WebSocket connection failure. Due to security constraints in your web browser, the reason for the 
failure is not available to this Neo4j Driver. Please use your browsers development console to determine 
the root cause of the failure. Common reasons include the database being unavailable, using the wrong 
connection URL or temporary network problems. If you have enabled encryption, ensure your browser is 
configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3
```

However, if I use a neo4j + built-in browser, where there's the setting page to enter in the bolt address, it works, connects to the bolt port, and everything works:

![screenshot from 2017-05-08 18-28-23](https://cloud.githubusercontent.com/assets/1614425/25828052/28393bfc-341c-11e7-9bd8-9ea33f5ee461.png)

So I now know it's not an issue with connecting to the neo4j (database) bolt port, it's with neo4j-browser, but I don't know where

From this [explanation](https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/), it says to uncomment a configuration line in neo4j (database) to allow non-loopback connections to bolt, `$NEO4J_HOME/conf/neo4j.conf`

```
dbms.connector.bolt.address=0.0.0.0:7687
```

However, it does not help with neo4j-browser connecting to neo4j's (database) bolt port either

**Comment by naisanza** [comment]
Solved. See https://github.com/neo4j/neo4j-browser/issues/509#issuecomment-301628740

**Comment by greghines** [comment]
Hi - I am running neo4j on one computer and needing to access the web interface on a different computer - and am getting the same error message. I followed the suggested solution of uncommenting the line in neo4j.conf which does not change anything => still getting the same error message. 

I am trying to figure out if your solution with certificates could help but I don't understand exactly what you did. Could you please provide some detailed steps for what I do. Also I feel that the suggested help on neo4j's page needs to be updated, so their solution doesn't seem to work (or is at least incomplete.)

**Comment by naisanza** [comment]
Hey @greghines 

Try creating a new container/vm and reinstall neo4j again, and start it up. Then access it via its https port: `https://your-neo4j-ip-or-hostname:7473`


The solution mentioned on this page is meant for when connecting an API to neo4j's `bolt` port, that uses the same certificate as the `https` port

**Comment by ppdouble** [comment]
Now, It works for me. Neo4j-community-3.1.2.
My experiences is that:

1. uncomment `dbms.connector.bolt.address=0.0.0.0:7687`

2. Add the bolt url as IP of my target neo4j server

3. I add the certificate as trusted to my mac os. (I found that the certificate is signed by "localhost" and trusted by target neo4j server IP and the expire time is Jan 1st, 10000 year.)

PS.

I install neo4j on one machine running CentOS. I access neo4j using chrome or safari on my mac book.

**Comment by naisanza** [comment]
@ppdouble yeah unless you access the neo4j server via https first, you won't be able to accept the certificate. My solution was to use a universally trusted CA, so it passes certificate verification. That way I didn't need to manage certificates on the clients

**Comment by KavinLiu** [comment]
I came across the same problem. And after I added 7687 port to iptables , it worked fine.

**Comment by Sankarb475** [comment]
Hi I came across same problem and i did follow all the three steps that @ppdouble has mentioned, but I'm still getting the same error.

**Comment by naisanza** [comment]
@Sankarb475 it's very likely it's still a certificate issue. The browser doesn't have it, so it's not allowing the connection. Give both Firefox and Chrome a try; Chrome has more training wheels than Firefox, Firefox let's you do more insecure user actions

**Comment by Sankarb475** [comment]
![image](https://user-images.githubusercontent.com/30991579/35958153-4daaa0a6-0cc5-11e8-9a05-d997d48ece5f.png)

Tried using Firefox, but keep getting the same error. Plus I am able to connect when i am using it through Java.

**Comment by oskarhane** [comment]
Please describe your setup @Sankarb475. OS, Neo4j version, if you're running it in docker or a VM etc.

**Comment by Sankarb475** [comment]
OS: Linux redhat enterprise server 7.4
Neo4j Version: 3.2.3
Running it on VM.

**Comment by alok-agarwal** [comment]
Having the same issue.

OS : Centos 6.9
Neo4j Version : 3.3.1
Running on EC2.

openjdk version "1.8.0_161" 
OpenJDK Runtime Environment (build 1.8.0_161-b14) 
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

**Comment by abhi2495** [comment]
@naisanza Hi. I have been trying to setup neo4j server in ubuntu (installed in Amazon AWS EC2) which I need to access from remote machine. I followed the Neo4j Doc and some stackoverflow questions , but found that I couldnt access it from my Corporate Network. So I decided to set up Nginx as proxy. I followed multiple links.With these I could hit the Neo4j server in browser,but couldnt connect to it's DB. 

Here is my detailed Question: https://stackoverflow.com/questions/50995925/set-up-neo4j-with-nginx-as-proxy-in-aws-ec2-ubuntu-16-ami

Please help

**Comment by naisanza** [comment]
@abhi2495 the easiest way to get this to work is have a ssl certificate that can be verified by third-party CA's. So no private certificates. I got mine from LetsEncrypt. 

- You'll want the nginx to use a validatable certificate as an ssl terminator
- The nginx conf will proxy your request to your neo4j server bolt port


This is an example pseudo nginx conf:
```
server {
    if ($host = domain) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        listen  80;
        listen  [::]:80;
}

server {
        listen  443 ssl;
        listen  [::]:443 ssl;

        ssl_certificate         /etc/letsencrypt/live/domain/fullchain.pem; # managed by Certbot
        ssl_certificate_key     /etc/letsencrypt/live/domain/privkey.pem; # managed by Certbot

        ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers       on;
        ssl_ciphers             "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_ecdh_curve          secp384r1; # Requires nginx >= 1.1.0
        ssl_session_cache       shared:SSL:10m;
        ssl_session_tickets     off; # Requires nginx >= 1.5.9
        ssl_stapling            on; # Requires nginx >= 1.3.7
        ssl_stapling_verify     on; # Requires nginx => 1.3.7
#       resolver                $DNS-IP-1 $DNS-IP-2 valid=300s;
        resolver_timeout        5s;
        add_header              Strict-Transport-Security "max-age=63072000; includeSubDomains; always";
        add_header              X-Frame-Options DENY;
        add_header              X-Content-Type-Options nosniff;

        location / {
                add_header              Strict-Transport-Security "max-age=63072000; includeSubDomains; always";
                proxy_pass              http://internal-neo4j-server:7687;
                proxy_read_timeout      90;
        }
}
```

**Comment by abhi2495** [comment]
@naisanza I dont want to complicate things by bringing https authentication into here.  This is not for production . It's just for personal use. Below I am giving you details of configuration changes I had made( which didnt work unfortunately :( ) Please take a look at them and suggest me what should I do here.
For your reference,
Network Connector Configuration of Neo4j:

`
dbms.connectors.default_listen_address=0.0.0.0
dbms.connectors.default_advertised_address=ec2-xx-xx-xx-xx.compute-1.amazonaws.com

dbms.connector.bolt.enabled=true
dbms.connector.bolt.listen_address=:17687
dbms.connector.bolt.advertised_address=:7687

dbms.connector.http.enabled=true
dbms.connector.http.listen_address=:17474

dbms.connector.https.enabled=true

`

HTTP and bolt in Nginx Config:-
a. For the HTTP part, I added the following inside the server section of /etc/nginx/sites-available/default this snippet:
location /neo4j/ {
proxy_pass http://localhost:17474/;
}
b. For the bolt protocol, I amended to /etc/nginx/nginx.conf this snippet:
stream {
server {
listen 7687;
proxy_pass localhost:17687;
}
}


Neo4j Version: 3.4.1 (installed in AWS EC2 inside VPC Public Subnet with security group allowing inbound 22,80, 7474,7473 and 7687 TCP connections)
Operating System: Ubuntu 16.04
API: Java Driver

**Comment by naisanza** [comment]
@abhi2495 check the logs to see if I'm wrong about this, but for connecting to anything more than localhost, it will check the certificate (bolt port uses ssl), and any self signed certificate will not pass. So that's why it has to be a third party signed certificate.

Or you can patch the source code not to verify the certificate.
