### ISSUE TITLE
How to get neo4j-browser to prompt to trust bolt certificate

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j-browser#509]
In attempts to solve https://github.com/neo4j/neo4j-browser/issues/504 I came across a page using neo4j-client connecting to the bolt port of a neo4j database. In the example given, it asks to accept the certificate fingerprint of the host.

I believe I need to get neo4j-browser to accept the certificate of my neo4j database when connecting to its bolt port.

The closest I've found in the neo4j-browser code is a line referring to whitelisting hosts, however adding my `bolt.server.com` to the list didn't work:

```
let whitelistedHosts = ['guides.neo4j.com', 'localhost', 'bolt.server.com']
  if (whitelist && whitelist !== '') {
    whitelistedHosts = whitelist.split(',')
  }
```

ref: https://github.com/neo4j/neo4j-browser/blob/3.0/src/shared/services/utils.js#L76

Accepting certificate in neo4j-client:
```
$ neo4j-client -u neo4j localhost
The authenticity of host 'localhost:7687' could not be established.
TLS certificate fingerprint is ded0fd2e893cd0b579f47f7798e10cb68dfa2fd3bc9b3c973157da81bab451d74f9452ba99a9c5f66dadb8a360959e5ebd8abb2d7c81230841e60531a96d268.
Would you like to trust this host (NO/yes/once)? yes
```
ref: http://www.chrisleishman.com/libneo4j-client/

**Comment by naisanza** [comment]
Using a signed certificate, such as one created by Let's Encrypt works. IT'S WORKING. EVERYTHING WORKS

However, this is still an issue if I want to explicitly accept a self-signed certificate. I believe the proper way is to accept the certificate into the browser via accessing the `https` port of the neo4j database (as mentioned here: https://github.com/neo4j/neo4j-browser/blob/3.0/src/browser/modules/Help/html/bolt-encryption.html). However, if the neo4-browser is to be run separately from the neo4j database, then it would cause issues such as:

- Requiring users to access a site twice, once to accept the self-signed certificate, and once again when it has been added to the user's browser
- Prompting the user to accept the self-signed certificate

I believe one way this could be solved is strictly by:

- Using a whitelist option to hard code in the self-signed certificate signature, that could possibly be passed to websockets (which I don't think will work)
- Or, give the user the option to accept the self-signed certificate in neo4j-browser when `:server connect` connects to the bolt port. And also allow for certificate whitelisting.

**Comment by oskarhane** [comment]
I don't think it's possible to prompt the user to accept certificates for other sites.
The user must go to the `https://` of the other site and manually trust it, just as you say.

There's nothing we can do here.
