### ISSUE TITLE
Can't define shaft-width dependent on relationshit weight in Grass Style Sheet

### ISSUE THREAD

**Issue by PrinzTu** [neo4j/neo4j-browser#518]
I tried to set the shaft width by defining the Style for `shaft-width: {weight}px;` , but it doesn't work when visualizating the graph. Would be great, if this issue can be fixed.

I think in modules/D3Visualization, File graphStyle.js those lines could be improved:

`GraphStyle.prototype.interpolate = function (str, item) {
      let ips = str.replace(/\{([^{}]*)\}/g, function (a, b) {
        let r = item.propertyMap[b]
        if (typeof r === 'object') {
          return r.join(', ')
        }
        if (typeof r === 'string' || typeof r === 'number') {
          return r
        }
        return ''
      })
      if (ips.length < 1 && str === '{type}' && item.isRelationship) {
        ips = '<type>'
      }
      if (ips.length < 1 && str === '{id}' && item.isNode) {
        ips = '<id>'
      }
      return ips.replace(/^<(id|type)>$/, function (a, b) {
        const r = item[b]
        if (typeof r === 'string' || typeof r === 'number') {
          return r
        }
        return ''
      })
}`

**Comment by oskarhane** [comment]
This is a pretty cool feature. Feel free to open a PR for it.

**Comment by PrinzTu** [comment]
It would be indeed pretty cool. Unfortunately i am not sure, how to implement that. If someone know's how to do that, it would be fantastic

**Comment by PrinzTu** [comment]
any help here?

**Comment by PrinzTu** [comment]
Pull request doesn't work, but the following code works now:

`
    GraphStyle.prototype.forRelationship = function (rel) {
      const selector = relationshipSelector(rel)
      let style = this.calculateStyle(selector)
      if (rel.propertyMap.weight !== undefined) {
        let shaftWidth = Max(
          Math.ceil(rel.propertyMap.weight / 2),
          style['props']['shaft-width']
        )
        style['props']['shaft-width'] = shaftWidth
      }
      return style
    }`

**Comment by OskarDamkjaer** [comment]
Closing this since it's been a few years with no updates, but if you end up submitting a PR in the end you can still reference this issue
