### ISSUE TITLE
Suggestion: give ability to switch query autocompletion off

### ISSUE THREAD

**Issue by lilianaziolek** [neo4j/neo4j-browser#525]
Whilst the new query autocompletion is generally awesome, I also noticed that it is at times a bit slow - I'm guessing the browser just cannot keep up with my speed of typing sometimes!
The result is that the input box freezes, sometimes jumps around making me type in the wrong place, and overall when I know exactly what I want to type, it simply gets in my way.

It would be great to have a switch that would allow me to switch autocompletion on and off, and when I think and type faster than autocompletion I'd have it off, and when I'm exploring things more slowly I could turn it on.

**Comment by InverseFalcon** [comment]
Might want to specify query autocompletion. There's another auto-complete feature on the graph results view that has to do with completing relationships between returned nodes, even if the relationships weren't returned in the original query.

**Comment by lilianaziolek** [comment]
Oh, wasn't aware of that at all. Changed the title of issue to make it clearer.

**Comment by oskarhane** [comment]
Thank you, fixed with https://github.com/neo4j/neo4j-browser/pull/560
