### ISSUE TITLE
Neo4j v3.2.0 browser cursor automatically & randomly switches back to the first position in the editor pane

### ISSUE THREAD

**Issue by aamanlamba** [neo4j/neo4j-browser#526]
When typing a Cypher query in the Neo4j v3.2 editor, the cursor position occasionally and randomly goes back to the first position in the editor pane, leading to many typing errors and rework,

Neo4j version: 3.2.0

Operating system: (for example Windows 95/Ubuntu 16.04): Windows Server 2012

API/Driver: (for example Cypher/Java API/Python driver : Cypher (Browser v 3.0.1)

Browser: Google Chrome

Steps to reproduce
Type a long query, covering multiple lines

Expected behavior
The text renders correctly, and the cursor does not change position unexpectedly

Actual behavior
The cursor position occasionally and randomly goes back to the first position in the editor pane

**Comment by lilianaziolek** [comment]
+1 here, I've noticed that too, one of the reasons I raised issue to allow disabling autocompletion, I suspect it has something to do with the browser not being able to catch up with the speed of typing...

**Comment by whitfa99** [comment]
+1

Neo4j version: 3.2.0

Operating system: Linux Mint 18 front
API/Driver: Cypher (Browser v 3.0.1) +Bolt

Browser: Slimjet  (Chromium-based browser)

**Comment by FylmTM** [comment]
Just a note for everyone and myself included.

Issue can be reproduced quite easily if (I am using latest macbook pro)
- Press 6 keys at the same, where one of the key trigger autocompletion. For example: `a`  `s`  `d`,
`m` `,` `.`

So, the key problem is auto-triggering. Question would be now - why this is happening?

**Comment by FylmTM** [comment]
UPD. It's nothing to do with autocompletion.

There is loop. Whenever editor value changes, onchange is triggered. Whenever onchange is triggered, the new code is set to editor.

There is check that if code is identical -> do nothing.

But unfortunately, setState is not synchronous, so we end up with race condition when code in state is older then in editor. 

The value is set, and therefore cursor end up in the beggining.
