### ISSUE TITLE
Spelling error for "Property ID" in :sysinfo in 3.2 

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j-browser#557]
After :sysinfo, in the ID Allocation column, note that "Property ID" is misspelled as "Propery ID".

**Comment by oskarhane** [comment]
Thanks for the report.
This seems to be fixed: https://github.com/neo4j/neo4j-browser/blob/3.0/src/browser/modules/Stream/SysInfoFrame.jsx#L143
