### ISSUE TITLE
Neo4j browser :style command missing a parameter

### ISSUE THREAD

**Issue by andrewhl** [neo4j/neo4j-browser#562]
I'm using Neo4j browser 3.0.1, and I'm trying to access the `:style` menu. Unfortunately, when I do  `:style`, as per the instructions [here](https://neo4j.com/developer/guide-neo4j-browser/#_styling_neo4j_browser_visualization) (under advanced styling), I get the following error:

```:style command missing a parameter - grass url, grass style data or reset```

I can't find any documentation on what this means or how to resolve it. Is it possible the style popup editor is gone in this version of Neo4j? How can I do advanced styling?

**Comment by oskarhane** [comment]
Hi @andrewhl, yes, this is a known regression in browser `3.0` that we are yet to fix.
With the coming `3.0.2` release you can upload `.grass` files, so you can do advanced styling again.
The `:style` window still isn't there though, but it will come back.

Sorry for the inconvenience.

**Comment by oskarhane** [comment]
Oh, btw, you can do `:style http://url.com/to/style.grass` to load a grass file.

**Comment by andrewhl** [comment]
@oskarhane Thanks for the fast response! I look forward to the new release.
