### ISSUE TITLE
Neo.ClientError.Statement.SyntaxError for labels that contain hyphen "-"

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j-browser#571]
I have labels created in Neo4j using the backtick `` ` ``

Such as:
```
MERGE pattern = (node :`label-with-hyphen` { `prop`: "value" } )
```

It works, and shows up in the database. When selecting an item with that label in neo4j-browser it doesn't add in backticks for the cypher command to execute properly

![screenshot from 2017-05-31 05-30-45](https://cloud.githubusercontent.com/assets/1614425/26625546/6bd21c78-45c2-11e7-9c54-8b6706911cb7.png)

**Comment by oskarhane** [comment]
This will be fixed in the next release by https://github.com/neo4j/neo4j-browser/pull/536
