### ISSUE TITLE
Bug - Save/Edit favorite query control has visual/functional issues in 3.2.x

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j-browser#578]
The Save/Edit favorite control next to the query input area does not change its visual to reflect a saved query or an edited save query.

More importantly, the functionality remains constant when it should be changing. Pressing the control will always add a new favorite query, even if a favorite query has been loaded and edited, which should have changed the functionality to saving the edited favorite.

Observed in 3.2.0 and 3.2.1 on Chrome and Safari on a Mac.

**Comment by oskarhane** [comment]
Fixed with https://github.com/neo4j/neo4j-browser/pull/593
