### ISSUE TITLE
Bug - Query plan expand/collapse all buttons only affect topmost plan results in 3.2.1 and 3.2.2

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j-browser#579]
When multiple query plan results are showing, all expand/collapse buttons (that are NOT for the topmost plan) affect the topmost query plan (inconsistently), and never the plan they're associated with. This also introduces some visual issues in the expanded/collapsed plan if the topmost plan is off-screen.

**Comment by oskarhane** [comment]
Should be fixed with https://github.com/neo4j/neo4j-browser/pull/610
