### ISSUE TITLE
Bug - Export to PNG does not work in Plan, Table, Text, or Code result views in 3.2.1 and 3.2.2

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j-browser#580]
The only time PNG export seems to work properly is on the graph result view. In the times that a png is created on the affected result views, the png is empty and an error is encountered. Users will be forced to take screenshots of the results/plan until this is fixed.

There are also occasional graphical/functional issues with the control itself. Sometimes the export menu will show on mouseover but disappear when attempting to select an option. Sometimes the export choices won't do anything when clicked.

**Comment by oskarhane** [comment]
Fixed with https://github.com/neo4j/neo4j-browser/pull/611
