### ISSUE TITLE
Unable to connect to the browser from java.

### ISSUE THREAD

**Issue by csalexandre** [neo4j/neo4j-browser#582]
Hello. I'm learning how to use Neo4j (version 3.2) from java. I'm using this tutorial: http://neo4j.com/docs/java-reference/current/. I've managed (using neo4j-desktop-3.2.0.jar) to load an owl ontology to a graph database. Now I'm trying to visualize my embedded database (query results,...) in neo4j-browser and "4.14. Accessing Neo4j embedded via the Bolt protocol" explains how to enable a connector. However I found no information about the java instructions to programmatically  interact with the browser after enabling the connector. Is this information available anywhere?

I also added the driver jar (from https://mvnrepository.com/artifact/org.neo4j.driver/neo4j-java-driver/1.3.1) to my Eclipse Neon project's build path. Then I tried to test the connection with the HelloWorldExample from https://neo4j.com/docs/developer-manual/3.2/drivers/get-started/. I'm getting a few error messages. I attach the resulting console error messages and the java class (since I had to make some modifications to the manual's version to eliminate errors). I looked for solutions in slack and stackoverflow, found some similar error reports but no concrete solution. Any suggestions?

[HelloWorldExample.txt](https://github.com/neo4j/neo4j-browser/files/1057596/HelloWorldExample.txt)
[HelloWorldExample_JAVA.txt](https://github.com/neo4j/neo4j-browser/files/1057597/HelloWorldExample_JAVA.txt)

Eventually I tried to first start the neo4j browser and only then run the HelloWorldExample. Different errors occur, again I attach the resulting console error messages. Thanks for any help!

[HelloWorldExample_1.txt](https://github.com/neo4j/neo4j-browser/files/1057640/HelloWorldExample_1.txt)
<img width="960" alt="neo4j_ce" src="https://user-images.githubusercontent.com/19592151/26873145-b9c26b6e-4b70-11e7-80e5-b936bbafb37a.png">

**Comment by muk3shkumar** [comment]
Hi @csalexandre ,
Seeing from the error in file HelloWorldExample_1.txt, it appears it is expecting a parameter and your implementation of parameter method return null.
Can you please try replacing the CYPHER query to something more simple without the use of parameter ? 
**Something like this - 
StatementResult result = tx.run("CREATE (a:Greeting {message:'New message'})"+
				"RETURN a.message");**

Hope it helps

**Comment by csalexandre** [comment]
Hello Mukesh Kumar

Yes it helped, thank you!


Regards,
Carlos

**Comment by oskarhane** [comment]
Thanks @muk3shkumar. Since this seems to have been resolved, I'll close it @csalexandre.
