### ISSUE TITLE
Export CSV downloads only first 1000 rows of results in v3.2.1 unlike earlier versions in which they downloaded the whole result.

### ISSUE THREAD

**Issue by techguysid** [neo4j/neo4j-browser#583]

**Comment by Dcanzano** [comment]
Within the Browser, left frame, Gears Icon how have you configured Max Rows.   When I have defined as 1000 (the default) and run 

match (n:MyLabel) return n;

and for which I have 10k :MyLabels then export to CSV only returns the first 1000.  However if I change Max Rows to 5000 and run

match (n:MyLabel) return n limit 2000;

and export to CSV now results in all 2000 rows being exported

**Comment by InverseFalcon** [comment]
I can reproduce the issue. In versions < 3.2.x, even if max rows is set below the number of actual results, exporting to CSV provides the entire result set.

In 3.2.x, the number of rows in the exported CSV is limited by max rows.

Checking with the browser team to figure out what changed, if this is considered a bug or an expected consequence of an efficiency improvement with respect to `max rows`, and whether we expect to change this, or at the very least make it clearer that `max rows` affects CSV export.

**Comment by InverseFalcon** [comment]
Confirmed as a bug, a fix is planned for the next release.
