### ISSUE TITLE
Static port in GUI

### ISSUE THREAD

**Issue by nicho90** [neo4j/neo4j-browser#607]
Hi there,

I recognised in the GUI (in my case the macOS client), that the link always refers to `localhost:7474`. When I change it for example to port `7575` in the `.neo4j.config`, it will not be updated. It's not a big issue, but I often run multiple instances of Neo4j on my machine with different configurations, so it  would be helpful to have a valid link for quicker access 😉 Please find 2 screenshots below:

<img width="842" alt="edit" src="https://user-images.githubusercontent.com/5202984/27656337-e990a69c-5c48-11e7-8878-f6ce6a16687a.png">

<img width="668" alt="wrong-port" src="https://user-images.githubusercontent.com/5202984/27656341-ebe5d3a4-5c48-11e7-9b7a-8a437239a303.png">

**Comment by muk3shkumar** [comment]
Hi @nicho90 ,

You can try enabling this property - 
#dbms.connector.http.listen_address=:<PORT_NUM>

Let me know if it worked or not.

Thanks!

**Comment by nicho90** [comment]
Hey @muk3shkumar, many thanks for your quick support!! It worked perfectly ☺️
