### ISSUE TITLE
Multiple .neo4j.config files

### ISSUE THREAD

**Issue by nicho90** [neo4j/neo4j-browser#608]
Hi there,

I often work on multiple instances of Neo4j and change them over the GUI like this:

<img width="668" alt="choose" src="https://user-images.githubusercontent.com/5202984/27657808-23f1ebf2-5c4e-11e7-88fe-a7deb8ada68e.png">

Therefore, I have created a folder structure like this:

```
.
|-- Documents
     |-- Neo4j
          |-- .neo4j-community.vmoptions
          |-- .neo4j-server.properties
          |-- .neo4j.config
          |-- 1st-database-instance
               |-- certificates
               |-- data
               |-- index
               |-- logs
               |-- plugins
               |-- ...
          |-- 2nd-database-instance
               |-- ...
          |-- 3rd-database-instance
               |-- ...
          |-- ...
```

My problem is, every time, when I change my instance, I have to manually reconfigure the `.neo4j.config` file. Is there a way to have multiple `neo4j.config` files?

My suggestion would be a folder structure like this:
```
.
|-- Documents
     |-- Neo4j
          |-- .neo4j-community.vmoptions
          |-- .neo4j-server.properties
          |-- .neo4j.config
          |-- 1st-database-instance
               |-- neo4j.config
               |-- ...
          |-- 2nd-database-instance
               |-- neo4j.config
               |-- ...
          |-- 3rd-database-instance
               |-- neo4j.config
               |-- ...
          |-- ...
```

All instances can have now an own `neo4j.config` file, but in case the file is missing, there is also the `.neo4j.config` as a fallback. This would be super useful to switch between instances without a manually reconfiguration of the `.neo4j.config`.

Another option would be, that I can choose a config file inside the GUI the same way I can do it for instances. Currently there is only a button to edit the file:

<img width="842" alt="choose" src="https://user-images.githubusercontent.com/5202984/27657477-153aa1c2-5c4d-11e7-8ed5-cc3c20ddd7f2.png">

**Comment by oskarhane** [comment]
Thanks for the suggestions @nicho90!
Unfortunately I don't see us fixing this in the current desktop UI for Neo4j.
We'll take this in consideration for the next generation though.
