### ISSUE TITLE
Syntax checker does not like YIELD

### ISSUE THREAD

**Issue by endrec** [neo4j/neo4j-browser#614]
The query in the screenshot runs perfectly fine, but the syntax checker does not like it:

![screenshot from 2017-07-17 15-10-21](https://user-images.githubusercontent.com/101801/28289716-99d7b47c-6b3b-11e7-88f9-f3232b9c4bec.png)

**Comment by oskarhane** [comment]
This should now be fixed in recent versions of Neo4h Browser.
