### ISSUE TITLE
Need immutable IDs for objects in the DOM

### ISSUE THREAD

**Issue by nicomp42** [neo4j/neo4j-browser#625]
The DOM references obfuscated element names, which is fine, but it is problematic when trying to interact with a tool like Selenium. If immutable names can be added the browser will be more robust and developers will have an easier time adapting to it. 
No logic changes are necessary. The names don't have to mean anything, they just need to be constant across future versions.

**Comment by oskarhane** [comment]
We have started adding attributes named `data-test-id` that can be used for this purpose.
We will continue to add more as we assert on them.
