### ISSUE TITLE
Lint error when returning APOC function

### ISSUE THREAD

**Issue by peresbruno** [neo4j/neo4j-browser#638]
### Description

Neo4j Browser is showing a lint error ("extraneous input '('") when returning a call to ```apoc.coll.union``` function, as shown below:

![captura de tela 2017-08-30 as 15 20 05](https://user-images.githubusercontent.com/1018182/29888427-4a0a19b6-8d97-11e7-821a-8bb4f77a9915.png)

The query runs fine and returns the expected result.

### Reproduce Steps

1. Open Neo4j Browser
2. Copy & Paste the following query

```
WITH [1] AS a, [2] AS b
RETURN apoc.coll.union(a,b);
```
### Expected Behavior

No lint error should be displayed.

### Current Behavior

A lint error ("extraneous input '('") is shown.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  macOS Sierra 10.12.5  
| Web browser    |  Google Chrome Version 60.0.3112.113 64 bits
| Neo4j Browser  | 3.0.4
| Neo4j          | 3.2.1

### Additional Information

- I'm running Neo4j as a docker container
- Issue from [this StackOverflow question](https://stackoverflow.com/questions/45940075/neo4j-apoc-extraneous-input)

**Comment by FylmTM** [comment]
Hi @peresbruno ,

Thanks for the report! We will take look at this ASAP.

**Comment by querynaut** [comment]
Any progress on this one? Same thing happens when using apoc CALL in a query.

To me, the unrequested inline linting feels unnecessary. It often gets in my way when pasting a spring data neo4j query into it (multi-line with many  quotation marks). I'd like to have the linting in a separate box, not hovering over my query.

Otherwise I quite like the progress the browser is making. Thanks!

**Comment by OskarDamkjaer** [comment]
Hi! Sorry for the lack of updates on this. We've currently working to revitalize our language support and avoid issues like these in the future. It'll probably take a long time until it's done, but know we're working to solve these kinds of problems :)
