### ISSUE TITLE
Unable to set nested parameters through the neo4j browser 3.0.5

### ISSUE THREAD

**Issue by peresbruno** [neo4j/neo4j-browser#645]
### Description

When trying to set the following parameters in Neo4j Browser 3.0.5

`:params {"uidLeft": "asdf1", "uidRight": "asdf2", "type": "KNOWS", props:{uid:"rel1"}}`

I'm getting this error:

> Could not parse input. Usage: `:param "x": 2`. SyntaxError: Expected ",", "}" or key but "{" found.

### Reproduce Steps

1. Open Neo4j-Browser 3.0.5
2. Run the following command:
`:params {"uidLeft": "asdf1", "uidRight": "asdf2", "type": "KNOWS", props:{uid:"rel1"}}`

### Expected Behavior

Parameters should be set as specified in the above command.

### Current Behavior
Parameters are not set and an error message is shown.

![captura de tela 2017-09-15 as 16 14 31](https://user-images.githubusercontent.com/1018182/30499472-027067d0-9a31-11e7-8f5d-dae7f640bfef.png)

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  macOS Sierra 10.12.6
| Web browser    |  Google Chrome 60.0.3112.113 64 bits
| Neo4j Browser  | 3.0.5
| Neo4j          | 3.2.2 and 3.2.3

### Additional Information

- Running Neo4j into Docker containers
- Works fine in Neo4j 3.2.1 and Neo4j Browser 3.0.4
- Works in Neo4j Browser 3.0.5 when outer parenthesis are removed: `:params "uidLeft": "asdf1", "uidRight": "asdf2", "type": "KNOWS", props:{uid:"rel1"}`
- BUT the above command (without outer parenthesis) not work in Neo4j Browser 3.0.4 (parameter are not set without error message)
- Issue from [this SO question](https://stackoverflow.com/questions/46244571/unable-to-set-nested-parameters-through-the-neo4j-browser-with-version-3-2-2)

**Comment by oskarhane** [comment]
Thanks for the report. It sure sounds like a bug somewhere.

**Comment by DeltaBravo** [comment]
Still broken as of Neo4j Browser version 3.1.4.

What seems to work is:
`:params foobar: {"uidLeft": "asdf1", "uidRight": "asdf2", "type": "KNOWS", props:{uid:"rel1"}}`
Everything will be underlined in red and a giant error message will appear but it still seems to set the parameter correctly.

**Comment by harrypunk** [comment]
Same problem with version 3.0.11

**Comment by jacobgunnarsson** [comment]
And as of 3.3.3

**Comment by oskarhane** [comment]
Yes, we have a card for this and will get to it. The workaround is to skip the outer curly brackets.

```
:params "uidLeft": "asdf1", "uidRight": "asdf2", "type": "KNOWS", props:{uid:"rel1"}
```

**Comment by irwebuniq** [comment]
Still broken as of Neo4j Browser version 3.1.7

**Comment by irwebuniq** [comment]
it worked in 3.1.7
