### ISSUE TITLE
Restore per frame "Connect result nodes" toggle

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j-browser#648]
In the past I opened https://github.com/neo4j/neo4j-browser/issues/181 to suggest a way to set a default for "Connect result nodes" (previously called AUTO-COMPLETE). This feature renders all relationships between visualized nodes, even if those relationships were not returned by the Cypher query. My feelings on this feature are that:

1. it should be disabled by default (although this should be configurable)
2. users should be able to toggle this setting on a per frame basis. Oftimetimes, I'll want to switch back and forth between auto-connected and queried-only relationships many times on the same query frame. Unfortunately, the per frame option no longer exists (perhaps as a result of https://github.com/neo4j/neo4j-browser/pull/220).

In Neo4j 3.2.3, this setting is only accessible via the settings drawer. Source:

https://github.com/neo4j/neo4j-browser/blob/c4a257ef237dac297bb607faa737f16d63833199/src/browser/modules/Sidebar/Settings.jsx#L132-L137

Would it be possible to have the default specified in the settings drawer but still have the per frame toggle?

**Comment by oskarhane** [comment]
Thanks @dhimmel. This is hard UX wise.
Personally I like the feature since it shows you how the data is structured. 
But the problem is that it's not what the user asked for.

We removed the per-frame toggle because we thought it made more sense for it to be global.
Thanks for your input on this, we'll make sure to take it in consideration for next update but I don't see us changing this in the current version.

**Comment by MysterAitch** [comment]
I struggle to understand the resistance to having a per-frame toggle, and would like to add an additional voice in support of returning it. 

I see two use cases for using the neo4j browser: 

1. Exploring data and the relationships between them -- In this case it is helpful to autocomplete the relationships.
2. Being a visual REPL interface to make building / testing queries easier -- In this case it is harmful/misleading to autocomplete the relationships.

To not have a per-frame toggle would imply that anybody using the browser only uses it for one case or the other.

_(Personally I develop with it toggled "off" as I use the browser to develop queries, but sometimes I need to take a step back and get an overview of the data for one or two queries, but then immediately return to having it toggled off.)_
