### ISSUE TITLE
How to run neo4j inside java web server (e.g tomcat/undertow) as static content on embedded server

### ISSUE THREAD

**Issue by cforce** [neo4j/neo4j-browser#658]
### Can you propose a solution?

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  
| Web browser    |  
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  |
| Neo4j          |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.

**Comment by oskarhane** [comment]
Please provide more info. It sounds like you want to serve Neo4j Browser at a static web server?
If so:
1. clone this repo
1. `yarn install`
1. `yarn build`
1. Copy contents of `dist/` to a static web server and point your web browser to it.
