### ISSUE TITLE
Neo4j desktop won't display more than 200 records

### ISSUE THREAD

**Issue by nbosc** [neo4j/neo4j-browser#675]
In Neo4j Desktop, I try to display the result of a query that should return at maximum 300 records (LIMIT 300). However, it does not work.
It opens a result window in the interface but it stays empty. Cannot zoom in or out, the buttons are not displayed. There is simple no node.
After that, if I try to display just 1 node, it does not work. Need to reload the app to make it works again but this does not solve this ridiculous display limitation.

Interestingly, if I run the same query in the web browser, it works, I see my nodes (LIMIT 300).

OSX el capitan
Neo4j desktop with Neo4j 3.3.0

**Comment by oskarhane** [comment]
This should be fixed with https://github.com/neo4j/neo4j-browser/pull/677

**Comment by nbosc** [comment]
No it does not.

**Comment by oskarhane** [comment]
Did you build from master to try it out?
It's not in any release yet. 
We have a Browser release planned next week which will have this in.

**Comment by nbosc** [comment]
No I didn’t. I thought it was part of the update I had just installed (1.0.4.359). Will wait the next release.

Thanks.

**Comment by nbosc** [comment]
1.0.6.399 installed and problem solved. Thanks

**Comment by sunparkmos** [comment]
How do I get 1.0.6.399? I test with Neo4j 3.3.3, still 300 nodes returned

**Comment by formatq** [comment]
Neo4j Browser version: 4.0.1
Still 300 nodes..

**Comment by GaryFrewin** [comment]
Yup. Still only getting 300 nodes also. Has this been fixed?

**Comment by OskarDamkjaer** [comment]
@GaryFrewin Not sure I follow what issue you're running into. Are you trying to return more than 300 nodes and only seeing 300 regardless of the "Initial Node Display" setting in the sidebar?
