### ISSUE TITLE
Text is not visible in Dark theme in Neo4J Browser

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j-browser#681]
### Description

When you execute a Cypher query, the text results of the query is not at all visible if you are on the dark theme.

Screenshots -

Result of my Cypher query (table view) -

![screenshot 2017-11-23 03 51 49](https://user-images.githubusercontent.com/11348778/33194553-a81cb578-d09e-11e7-9b6f-239a877ad81a.png)

As you can see, the text result is displayed in what seems to be a gray color, that is not at all visible against the dark background.

I have to highlight the text to see what it actually is -

![screenshot 2017-11-23 03 51 55](https://user-images.githubusercontent.com/11348778/33194568-db5a33d4-d09e-11e7-84ca-37749799eed2.png)

This is the in-built browser on Neo4J Desktop, which uses Neo4J version 3.3.

### Reproduce Steps

Start Neo4J Desktop, create a database, or use an existing one. Start Neo4J Browser, execute a Cypher query that returns some results in table mode (example - `count(*)`), then see the results in the browser.

### Expected Behavior
Text should be clearly visible.

### Current Behavior
Text is not visible.

### Can you propose a solution?
When on dark theme, color of rendered text needs to be changed so that it can be visible against the dark background.
 

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |   Mac OSX High Sierra
| Web browser    |  
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  |
| Neo4j          | 3.3

**Comment by oskarhane** [comment]
Thanks, I'll add it to our backlog
