### ISSUE TITLE
Neo4j browser doesn't correctly handle inputted bolt address for connection

### ISSUE THREAD

**Issue by DFoxinator** [neo4j/neo4j-browser#683]
**Neo4j Version:** 3.3.0
**Operating System:** Mac OS/Chrome

### Steps to reproduce
1. Go to the Neo4j browser
2. Set up the connection for a database where the bolt host is different from the IP of the instance itself. This use-case occurs for me when I'm using an SSH tunnel to access a Neo4j instance, so the browser wants to use the private IP of the instance, but I need to to use 127.0.0.1:port
3. Use the browser. It will work correctly.
4. Refresh the page
5. Now, the browser ignores the previously entered bolt host, and starts using the private instance IP which is incorrect.

### Expected behavior
The browser should not override the previous saved value entered for the bolt host

### Actual behavior
The browser changes the previous saved bolt host URL to use the instance IP instead, which breaks the browser when you're using it with an SSH tunnel and need to 
route through 127.0.0.1 or some other IP. It works fine the first time you enter it - the issue only occurs when you reload the page.

**Comment by oskarhane** [comment]
The browser looks what the server advertises and takes that as the truth over last connection.
You can set what the server advertises with `dbms.connector.bolt.advertised_address=` in `neo4j.conf`.
Make sure it's something a web browser can connect to and it should work.
