### ISSUE TITLE
undo node expansion

### ISSUE THREAD

**Issue by kdwykleingeld** [neo4j/neo4j-browser#684]
Maybe its a feature request but it would be really great if you could "undo" the expansion of the retelationships of a node in the browser .. sometimes you expand the rels of a node but that results in a very large number of related nodes (thus not a good idea) cluttering the visualization (that you sometimes modelled somehow).. it would be great if you could undo such action (in stead of re-running the query)

thanks

**Comment by oskarhane** [comment]
Fixed with https://github.com/neo4j/neo4j-browser/pull/877
