### ISSUE TITLE
Neo4j desktop failed to create database 3.2.8

### ISSUE THREAD

**Issue by nbosc** [neo4j/neo4j-browser#686]
Hi,

Using Neo4j Desktop (1.0.6.399), I cannot create a database version 3.2.8.
Works with 3.3.0 or 3.3.1.

<img width="1434" alt="screen shot 2017-12-05 at 12 23 01" src="https://user-images.githubusercontent.com/26281131/33607364-cf68b3de-d9b8-11e7-82a5-65175c55c80f.png">

**Comment by oskarhane** [comment]
Thanks for the report @nbosc!
For some reason it seems like you have gotten a corrupted version of 3.2.8.
We will add integrity checks in the future, but for now please manually go and delete `/Users/<username>/Library/Application Support/Neo4j Desktop/Application/distributions/neo4j/neo4j-enterprise-3.2.8-unix.tar.gz` and try again.

**Comment by oskarhane** [comment]
Please report any neo4j-desktop issues on https://github.com/neo4j-apps/neo4j-desktop/issues instead.
Thanks

**Comment by nbosc** [comment]
Indeed there was a corruption, odd...

Thanks
