### ISSUE TITLE
Probem while invoking REST api from Neo4j Desktop

### ISSUE THREAD

**Issue by conker84** [neo4j/neo4j-browser#687]
### Description
Hi guys,
when i try to invoke a simple rest api from the Neo4j browser in the Neo4j Desktop i get the following message:
```
Could not fetch URL: "Failed to fetch". This could be due to the remote server policy. See your web browsers error console for more information.
```
While the same command works in the (normal) Chrome browser, by using the url `http://localhost:7474/browser/`

### Reproduce Steps
Starting from the Graph Platform, open the browser and execute this simple command:
`:GET /db/data/labels`

### Expected Behavior
The response of the REST invocation must be displayed

### Current Behavior
The response is the following message:
```
Could not fetch URL: "Failed to fetch". This could be due to the remote server policy. See your web browsers error console for more information.
```

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows 10
| Neo4j Desktop    |  1.0.8
| Neo4j          | 3.2.0 Enterprise

**Comment by oskarhane** [comment]
Thanks for the report @conker84! It's indeed a bug and I've added it to our backlog.
The workaround, if you don't have auth enabled, is to `:GET http://localhost:7474/db/data/labels`.

**Comment by oskarhane** [comment]
This is working now and we forgot to close this issue: https://github.com/neo4j/neo4j-browser/pull/689
