### ISSUE TITLE
Cannot connect to remote server from browser

### ISSUE THREAD

**Issue by nikeshkedlaya** [neo4j/neo4j-browser#688]
I have installed neo4j in my remote server. I have installed neo4j 3.3.1.

I was working on my localhost and i was able to connect from browser (localhost:7474/browser/).

But i cannot connect to my remote server (192.168.0.6:7474/browser)

I have made changes in neo4j.conf file.
i have updated dbms.connector.http.listen_address=:7474 in conf file to dbms.connector.http.listen_address=0.0.0.0:7474

And then restarted neo4j but stil i cannot access the web interface.

**Comment by jexp** [comment]
Did you do the same for the bolt port? Neo4j Browser needs the binary protocol.
You can also add the general listen address of 0.0.0.0

**Comment by nikeshkedlaya** [comment]
Yes i did. These are all the changes i have done in conf file.

`# Bolt connector
dbms.connector.bolt.enabled=true
#dbms.connector.bolt.tls_level=OPTIONAL
#dbms.connector.bolt.listen_address=:7687
dbms.connector.bolt.listen_address=0.0.0.0:7687

# HTTP Connector. There must be exactly one HTTP connector.
dbms.connector.http.enabled=true
#dbms.connector.http.listen_address=:7474
dbms.connector.http.listen_address=0.0.0.0:7474

# HTTPS Connector. There can be zero or one HTTPS connectors.
dbms.connector.https.enabled=true
#dbms.connector.https.listen_address=:7473
dbms.connector.https.listen_address=0.0.0.0:7473
`

**Comment by nikeshkedlaya** [comment]
@jexp Please help me out resolving this. I have turned off the firewall also. If i do netstat it says CLOSE_WAIT from my IP Address. Browser is not at all opening.

**Comment by nikeshkedlaya** [comment]
@jexp I can connect now. Browser is opening, but if i execute any query it says **Failed to construct 'WebSocket': The URL 'ws://:7687' is invalid.**

**Comment by nikeshkedlaya** [comment]
@jexp Happy to say everything worked. Thank you

**Comment by ramezsw** [comment]
@nikeshkedlaya Do you mind sharing how you fixed this? I am facing the exact same issue and I haven't been able to find a solution yet.

**Comment by nikeshkedlaya** [comment]
Please turn off the firewall for this port.

**Comment by chirag912** [comment]
@nikeshkedlaya  Hey im facing a similar issue. i have tried disabling the firewall. But it doesn't help. Could be please help.

I have done all the necessary settings in the conf file.

My neo4j installation is on openstack ubuntu server. and im running localhost on my mac through ssh channel. 

I can see the neo4j browser but as soon as i enter the password. I get this same error.

Any help will be really appreciated. Thanks

**Comment by ninjakx** [comment]
@nikeshkedlaya , @chirag912  : Are you ppl able to do this : https://stackoverflow.com/questions/27822440/curl-command-neo4j/27822642 ??
I am trying to use the rest api (localhost only) but not able to do it. Can you people help If things worked for you?
