### ISSUE TITLE
Cypress 0.2.1 fails to download on Windows but 0.2.3 OK

### ISSUE THREAD

**Issue by internetscooter** [neo4j/neo4j-browser#692]
### Description
Following basic steps to run on Windows 10 fails due to Cypress 0.2.1 download not being found.

### Reproduce Steps
Follow Readme steps and it fails at "Install project dependencies: yarn"

### Expected Behavior
Dependencies installed and ready to run

### Current Behavior
```
PS C:\code\neo4j-browser> yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning ...<snip>...
[4/4] Building fresh packages...
[1/4] ⢀ husky: done
[2/4] ⢀ preact:  > https://opencollective.com/preact/donate
[-/4] ⢀ waiting...
[4/4] ⠠ cypress:
error C:\code\neo4j-browser\node_modules\cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: C:\code\neo4j-browser\node_modules\cypress
Output:
Installing Cypress (version: 0.20.1)

[11:43:41]  Downloading Cypress     [started]
[11:43:43]  Downloading Cypress     [failed]
[11:43:43] → The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/0.20.1?os=win
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
----------

Platform: win32 (10.0.16299)
Cypress Version: 0.20.1
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/0.20.1?os=win
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
----------
```
### Can you propose a solution?
Cypress 0.2.3 used in package.json instead. I have not created a pull request as I am not able to verify e2e tests are working. Someone familiar with running these needs to verify if indeed 0.2.3 is only a minor change from 0.2.1.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows
| Web browser    |  
| node.js        |  v8.9.3
| npm            | 5.6.0
| yarn           |  1.3.2
| Neo4j Browser  | 3.1.4
| Neo4j          | 3.3.0

### Additional Information
When I attempt to run e2e it fails with no error

```
PS C:\code\neo4j-browser> yarn e2e
yarn run v1.3.2
$ cypress run
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by oskarhane** [comment]
This should be working no. Feel free to re-open if it isn't.
