### ISSUE TITLE
Feature Request: Add parameter input section

### ISSUE THREAD

**Issue by chrisregnier** [neo4j/neo4j-browser#693]
I often find myself copying queries into the browser that have parameter inputs, and then I have to go through the query and replace the inputs with some exact values to test out. I continue to replace the inputs with other test values to validate the queries as I change things, and then I eventually have to go back through and change all of the values back to input parameters before I copy the query back to code.

I would love having a separate panel to supply input parameters that I can change separately from the raw query. It wouldn't be much, but I think it might help the speed up some workflows.

Opinions?

**Comment by OskarDamkjaer** [comment]
It sounds to me like [cypher parameters](https://neo4j.com/docs/cypher-manual/current/syntax/parameters/) would solve your issue. They are usable in browser as well!

Adding a separate frame for setting parameters has been discussed, but it is unlikely to be implemented.
