### ISSUE TITLE
Editor error with multiple parameters using MERGE ON CREATE SET

### ISSUE THREAD

**Issue by matt-usurp** [neo4j/neo4j-browser#695]
### Description
When writing a `MERGE` query that sets multiple properties `ON CREATE SET` the editor prompts a syntax error where ignoring it and running the query will execute fine.

Note I don't know if the below query is "the correct way of doing things" but the important thing is that the documentation states the below in a few places and the editor doesn't appear to be consistent with it.

> If multiple properties should be set, simply separate them with commas.

### Reproduce Steps
Simply paste the following in to the query editor.

```
MERGE (e:Person {name: 'Jane Doe'})
ON MATCH SET e.version = '1.1'
ON CREATE SET e.version = '1.1', e.name = 'Jane Doe'
RETURN e
```

You will be prompted with the following error message just after the `,` on line 3:

```
extraneous input ' ' expecting {'(', '[', '{', '$', StringLiteral, HexInteger, 
DecimalInteger, OctalInteger, HexLetter, ExponentDecimalReal, RegularDecimalReal, 
CYPHER, EXPLAIN, PROFILE, USING, PERIODIC, COMMIT, UNION, ALL, CREATE, 
DROP, INDEX, ON, CONSTRAINT, ASSERT, IS, UNIQUE, EXISTS, LOAD, CSV, WITH, 
HEADERS, FROM, AS, FIELDTERMINATOR, OPTIONAL, MATCH, UNWIND, MERGE, 
SET, DETACH, DELETE, REMOVE, FOREACH, IN, DISTINCT, RETURN, ORDER, BY, 
L_SKIP, LIMIT, ASCENDING, ASC, DESCENDING, DESC, JOIN, SCAN, START, NODE, 
RELATIONSHIP, REL, WHERE, SHORTESTPATH, ALLSHORTESTPATHS, OR, XOR, AND, NOT, 
STARTS, ENDS, CONTAINS, NULL, COUNT, FILTER, EXTRACT, ANY, NONE, SINGLE, TRUE, 
FALSE, REDUCE, CASE, ELSE, END, WHEN, THEN, CALL, YIELD, KEY, 
UnescapedSymbolicName, NULL, TRUE, FALSE, EscapedSymbolicName}
```

### Expected Behavior
Expect that the error doesn't display as its misleading. For me I spent an hour doubting myself before actually running the query and seeing the result worked.

### Your Environment

| software name  | version
| ---------------|----------
| OS             |  `Mac High Sierra 10.13.2`
| Web browser    |  `Chrome 63`
| Neo4j Browser  | `3.1.4`
| Neo4j          | `3.3.0`
| Docker | `neo4j:3.3.0`

**Comment by OskarDamkjaer** [comment]
Hi! Thanks for reporting this issue and sorry about the late reponse! We're working to make sure our error reporting doesn't show misleading errors, this particular issue seems to have gone away over the years.
