### ISSUE TITLE
Remove unused property keys

### ISSUE THREAD

**Issue by dennisverspuij** [neo4j/neo4j-browser#701]
Hello,

I experience the same issue as described [here](https://stackoverflow.com/questions/33982639/neo4j-how-to-delete-unused-property-keys-from-browser), property keys remain listed in the left pane of the browser even when not used anywhere anymore. This is annoying when you are sure not to use them anymore, they distract.

Is there any way to refresh/rescan the list of "used" property keys? Clearing local storage of the browser does not help, it seems the keys remain somewhere indexed in the Neo4j database itself?

Many thanks for Neo4j and if this can be fixed!

**Comment by oskarhane** [comment]
Hi, thanks for the report!

Neo4j Browser is just displaying what Neo4j is providing, and all property keys are coming with the call to the `CALL db.propertyKeys()` procedure.

If you want this changed, you should create a feature request in the https://github.com/neo4j/neo4j repo.

**Comment by dennisverspuij** [comment]
Thanks, I will!
