### ISSUE TITLE
WebSocket connection failure, although able to connect through Java Bolt connection

### ISSUE THREAD

**Issue by Sankarb475** [neo4j/neo4j-browser#702]
I have been successfully able to install Neo4j 3.3.2 in my linux OS. 
I am able to start the server and also do the operations(like creating, updating and fetching the nodes) through my java class using bolt connection method.

But when I am trying to open the Neo4j browser from a remote pc with the IP which has been set up in the neo4j.conf file under `dbms.connectors.default_advertised_address` i am getting this following error:

>N/A: WebSocket connection failure. Due to security constraints in your web browser, the reason for the 
failure is not available to this Neo4j Driver. Please use your browsers development console to determine 
the root cause of the failure. Common reasons include the database being unavailable, using the wrong 
connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3

The neo4j.conf file:
`dbms.connectors.default_listen_address=0.0.0.0`
`dbms.connectors.default_advertised_address=xx.xx.xx.xx`
`dbms.connector.bolt.enabled=true`
`#dbms.connector.bolt.tls_level=OPTIONAL`
`dbms.connector.bolt.listen_address=:7687`

`# HTTP Connector. There must be exactly one HTTP connector.`
`dbms.connector.http.enabled=true`
`dbms.connector.http.listen_address=:7474`

`# HTTPS Connector. There can be zero or one HTTPS connectors.`
`dbms.connector.https.enabled=true`
`dbms.connector.https.listen_address=:7473`

I did all the three steps that has been mentioned by @ppdouble  in the following link:          
https://github.com/neo4j/neo4j-browser/issues/504

But still the error persists.

Hi @oskarhane 
i would really appreciate if you could point me to the right direction fixing this.

Thanks

**Comment by oskarhane** [comment]
Hi @Sankarb475.

Do you see that error message when going to http://xx.xx.xx.xx:7474 and trying to connect?
What's printed in the `Host` field that comes up when you go to the above address?
If it's the same as xx.xx.xx.xx, then you have some port configuration error and `7687` can be connected to.

**Comment by Sankarb475** [comment]
Yes @oskarhane  I am getting the same error message when trying to connect with this: http://xx.xx.xx.xx:7474

Host field is same as this xx.xx.xx.xx when trying to go the above address.

**Comment by oskarhane** [comment]
Do you have Neo4j (and your java classes) inside a VM in your linux machine?
If so, you need to open/forward the port 7687 as well as 7474 since the Neo4j Browser connects from the outside.

**Comment by oskarhane** [comment]
What web browser did you use?
Some people run into this when they have the wrong java version installed. What are you on?

**Comment by Sankarb475** [comment]
I am using Google Chrome, although i tried it on Firefox, getting the same error. But when I tried with Internet explorer I didnt even get the login page.

In my Linux machine I have the following Java version installed: 
Java: openjdk version "1.8.0_151"
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

And I dont think the Java version of my remote desktop has anything to do with this, anyway I have the following Java version installed in my remote desktop:
java version "1.8.0_141"

**Comment by Sankarb475** [comment]
Its my web browser which was causing the issue, there was nothing wrong with the config file.
I had to remove all the proxy setting from my web browser, and it was good to go.
And those of you who do not there's a wonderful group called "Neo4j users Slack", you might wanna join that if you have any issue with Neo4j, a lot of people to help over there.

thanks @oskarhane
