### ISSUE TITLE
Code question: URL parameters processed where?

### ISSUE THREAD

**Issue by JulianRein** [neo4j/neo4j-browser#728]
Can someone direct me to the source file/underlying lib that processes URL/get parameters like the following?
http://localhost:7474/browser/?cmd=play&arg=http://guides.neo4j.com/trumpworld

Reason: I need a Query-from-URL function like in the following issue and want to see if I can implement it myself.
https://github.com/neo4j/neo4j-browser/issues/133

**Comment by oskarhane** [comment]
Currently, this is what's available: https://github.com/neo4j/neo4j-browser/pull/153

**Comment by oskarhane** [comment]
Sorry, too fast in the last response. That's the "docs" for it, but for the old codebase. Here's the code for the current codebase: https://github.com/neo4j/neo4j-browser/blob/6579053b074f0c6750395c81253430df334fe4ba/src/shared/modules/editor/editorDuck.js#L42-L56
