### ISSUE TITLE
default graph (MATCH (n) RETURN n LIMIT 25)

### ISSUE THREAD

**Issue by victoriastuart** [neo4j/neo4j-browser#732]
Feature request: option to change the parameters for the default graph.

E.g. on creating a graph, to see all my nodes, I need to click the default query

    MATCH (n:TCA) RETURN n LIMIT 25

and lop off the last bit,

    MATCH (n:TCA) RETURN n

Thanks.

**Comment by oskarhane** [comment]
The clickable labels in the sidebar are there to show the user what's in the database.
We set the limit there to not fetch the whole database by a single click. If the database is large your web browser could break.

If you find yourself wanting to type the same query over and over again you can add it to you favorites: When you have typed the query in the editor, click the ⭐️ symbol to the right.
Now you can find your query under the Favorites sidebar.

**Comment by victoriastuart** [comment]
OK, that'll work.  Thank you, appreciated.  :-)
