### ISSUE TITLE
Make the query result window resizable and fix status bar

### ISSUE THREAD

**Issue by romshark** [neo4j/neo4j-browser#742]
### Description
There's a bug with the status bar where property values and node type visualization options are normally displayed, it's hidden when the upper panel of displayed node types is maximized.

### Reproduce Steps
![neo4j_browser_query_result_view_layout_bug](https://user-images.githubusercontent.com/9574743/39153919-db254438-474c-11e8-9aee-4e3e60875023.gif)

### Expected Behavior
The status bar should not become hidden obviously, I'd suggest to make the query result window resizable, at least horizontally.

### Your Environment
| software name  | version
| ---------------|----------
| OS             | Windows 10
| Google Chrome | 66.0.3359.117 (64-Bit)
| Microsoft Edge | 41.16299.15.0
| Neo4j Browser  | 3.1.4
| Neo4j          | 3.3.4

### Additional Information
The status bar bug didn't appear in Edge, seems like it's working there.

**Comment by oskarhane** [comment]
Thanks for the report. This is out in neo4j-browser 3.1.3.
