### ISSUE TITLE
Cypher error displayed for map projections with apoc

### ISSUE THREAD

**Issue by g3rd** [neo4j/neo4j-browser#755]
### Description
When collecting a map projection, with an apoc function, the browser shows the query as an error.

### Reproduce Steps
1. Open up the `/browser/`
2. Enter the following query:
   ```
   MATCH (u:User)-[:WRITE]->(s:Story)
   WITH u, COLLECT(DISTINCT s {.title, page_title: apoc.text.join([s.title, "| MySite"], " ")}) AS stories
   RETURN u AS user, stories;
   ```
   or

   ```
   MATCH (u:User)-[:WRITE]->(s:Story)
   RETURN u AS user, s {.title, page_title: apoc.text.join([s.title, "| MySite"], " ")}
   ```

### Expected Behavior

The browser, won't show the error

### Current Behavior
The browser underlines everything after the `DISTINCT`.  When hovering over the affected area, says `mismatched input 's' expecting ';'`
See attached image:

![Screenshot](https://user-images.githubusercontent.com/746731/39827700-bd406290-5386-11e8-8b91-e55679741bc2.png)

### Can you propose a solution?

Recognize when functions are within a map projection.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  MacOS 10.13
| Web browser    | Chrome 66 
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 3.1.4
| Neo4j          | 3.3.4 Enterprise

### Additional Information

N/A

**Comment by oskarhane** [comment]
This was a bug with the first version of our multi statement mode in the editor. 
This should now be fixed.
