### ISSUE TITLE
Adding a constraint causes browser spinner to keep running on Community Edition

### ISSUE THREAD

**Issue by noumaans** [neo4j/neo4j-browser#779]
### Reproduce Steps
Create a graph with 100 nodes.
All these 100 nodes have a structure e.g.:
(n:Foo) and have properties bar and baz (both of type string) which are both set to some random string values.

Write the following in browser:
```
CREATE CONSTRAINT ON (n:Foo) ASSERT exists(n.bar);
CREATE CONSTRAINT ON (n:Foo) ASSERT exists(n.baz);
```

You will get an error message indicating multiple queries cannot be created.

Then, issue:
```
CREATE CONSTRAINT ON (n:Foo) ASSERT exists(n.bar)
```
The spinner in query result frame keeps on spinning for 10 minutes...

### Expected Behavior
It should return the error message that Community Edition doesn't support Existence Constraints.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  MacOS
| Web browser    |  Chrome 66.0.3359.181 (Official Build) (64-bit)
| node.js        | 10.3.0
| npm            |
| yarn           |
| Neo4j Browser  | 3.1.12
| Neo4j          | 3.4.0 (running inside docker container - image: neo4j:3.4.0)

**Comment by oskarhane** [comment]
I cannot reproduce this with neo4j-browser v3.2.10 and Neo4j Community v3.4.10.
Feel free to re-open is the issue still exists for you @noumaans.

It fails (as it should) but the browser stays responsive.

<img width="826" alt="oskarhane-mbpt 2018-10-23 at 09 27 46" src="https://user-images.githubusercontent.com/570998/47343230-ef726680-d6a5-11e8-85f4-585b8515c5e5.png">
