### ISSUE TITLE
Neo4j browser causes 100% CPU from automated background query

### ISSUE THREAD

**Issue by kinetiz** [neo4j/neo4j-browser#783]
### Description
When I open Neo4j browser, the CPU usage always gets to 100% without performing any queries.

I've checked the background queries and found some auto-gen queries running as follows.

![image](https://user-images.githubusercontent.com/29846375/41502262-59e12d42-71ae-11e8-95f9-ae08ed7ae80a.png)

`CALL db.labels() YIELD label 
WITH COLLECT(label)[..1000] AS labels 
RETURN 'labels' as a, labels as result 
UNION 
CALL db.relationshipTypes() YIELD relationshipType
WITH COLLECT(relationshipType)[..1000] AS relationshipTypes 
RETURN 'relationshipTypes' as a, relationshipTypes as result 
UNION 
CALL db.propertyKeys() YIELD propertyKey 
WITH COLLECT(propertyKey)[..1000] AS propertyKeys 
RETURN 'propertyKeys' as a, propertyKeys as result 
UNION 
CALL dbms.functions() YIELD name, signature, description 
WITH collect({name: name, signature: signature, description: description}) as functions 
RETURN 'functions' as a, functions AS result 
UNION 
CALL dbms.procedures() YIELD name, signature, description 
WITH collect({name: name, signature: signature, description: description}) as procedures 
RETURN 'procedures' as a, procedures as result 
UNION 
MATCH (n) RETURN 'nodes' AS a, count(n) AS result 
UNION 
MATCH ()-[]->() RETURN 'relationships' `

I've already tried killing the queries but they come up again. 

Could you please let me know what are these query doing ? and how can I stop them?

### Environment
| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows 10
| Neo4j Browser  | 3.1.15
| Neo4j          | 3.35 Enterprise

**Comment by oskarhane** [comment]
Thanks for the report! This is now fixed in https://github.com/neo4j/neo4j-browser/pull/785 and will be in the next release.
