### ISSUE TITLE
Favorite queries are not consistently saved

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j-browser#796]
I'm trying to favorite (and save) a set of queries in Neo4J Browser under a named folder. However, the queries are not consistently saved. Some are saved, and some just disappear.

### Reproduce Steps

1. Create a new folder under "Saved Scripts"
2. Create a new query and favorite it
3. Drag and drop it to the created folder
4. Repeat steps 2 and 3 for a few times

### Expected Behavior

All queries should be saved.

### Current Behavior

Some favorite/saved queries are not saved.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Mac OS High Sierra
| Web browser    |  Chrome
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 3.2.5
| Neo4j          | 3.4.1

**Comment by OskarDamkjaer** [comment]
Thanks for reporting this issue and sorry for taking so long to respond. I'm unable to reproduce this the nine times I tried so I assume it's been fixed. If that's not the case, please re-open this issue and provide instructions on how to reproduce it in the [latest build](https://s3-eu-west-1.amazonaws.com/ux.neotechnology.com/assets/neo4j-browser-latest/index.html).
