### ISSUE TITLE
WebSocket connection failure#Neo4j

### ISSUE THREAD

**Issue by shalaka92** [neo4j/neo4j-browser#799]
OS - Ubuntu 16.04
Neo4j 3.4.1 desktop version 
Installed Graphaware and Apoch plugin. 

When I was running this query:
MATCH (t:Tweet { language: "en" })
CALL ga.nlp.annotate({text: t.text, id: id(t),pipeline:'customNER3'})
YIELD result
MERGE (t)-[:HAS_ANNOTATED_TEXT]->(result)
RETURN count(result);

Was getting Java memory problem, hence I increased the memory size to 3G as follows:
dbms.memory.heap.max_size=3G
dbms.memory.pagecache.size=3G
After solving memory issue getting this error - 
ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3

Tried solving it by uncommneting this line in neo4j.conf:
dbms.connector.bolt.listen_address=0.0.0.0:7687
Still getting the same error. Have the following java versions running
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

Please let me know how can I solve this problem?

### Can you propose a solution?

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  
| Web browser    |  
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  |
| Neo4j          |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.

**Comment by oskarhane** [comment]
This sounds unusual @shalaka92. Is this still an issue?

**Comment by huyenqbi** [comment]
Hi oskarhane, yes I still run into the same problem.

**Comment by stugorf** [comment]
I am running into the same issue when calling the annotate function. I have APOC installed as well and saw that earlier there was a conflict with having both APOC and GraphAware installed, is this issue related?
