### ISSUE TITLE
Login failure on neo4j server AND neo4j-driver issue

### ISSUE THREAD

**Issue by ishaanmadan19** [neo4j/neo4j-browser#803]
I am having a few issues, all stemming from my usage of the neo4j-java driver. I am using the following dependencies:

_libraryDependencies += "org.neo4j.driver" % "neo4j-java-driver" % "1.6.1" 
libraryDependencies += "neo4j-contrib" % "neo4j-spark-connector" % "2.2.1-M5"_

(Scala: 2.11.12, Spark:2.3.1, Neo4j server:3.4.4)

When I tried create a driver session as follows (with my_username and my_pwd filled with my actual credentials), I kept getting the following issue over and over again:  

_val driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("my_username", "my_pwd"))
val session = driver.session_

**_org.neo4j.driver.v1.exceptions.AuthenticationException: The client is unauthorized due to authentication failure._**

As a result of trying to run this code, I was then unable to log into neo4j server. In the past few weeks, I have had no issue logging in, and have successfully played around with Cypher commands on my account. As I was unable to login, I tried to change my password, and after submitting the relevant password-resubmit form through the URL sent to my email, I was given the same error message over and over again: "WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN." Screenshot below. Would appreciate any help on either of these matters (driver issue and/or login issue now).

**Comment by pe4cey** [comment]
@ishaanmadan19I made a small change with the sync auth provider. Can you please try logging in again. Thanks

**Comment by ishaanmadan19** [comment]
Ok, thank you. i was successfully able to log back in now! 

Still having issues with the script though. When I run it, I am logged out of the server temporarily and the exception below is shown:

_val driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("my_username", "my_pwd"))
val session = driver.session_ 

yields 

**Exception in thread "main" org.neo4j.driver.v1.exceptions.AuthenticationException: The client is unauthorized due to authentication failure.**

Any idea how to fix this?

**Comment by InverseFalcon** [comment]
You're connecting to localhost here, so it will be that neo4j instance's credentials.

Keep in mind that for the sandbox instance **only**, the db credentials == the browser sync credentials. In any other case the browser sync credentials are entirely independent for the db login.

**Comment by pe4cey** [comment]
The best way to get an answer for the `AuthenticationException` problem would be to join our public [slack group](http://neo4j.com/slack) or alternatively, raise an issue against the [neo4j-java-driver repo](https://github.com/neo4j/neo4j-java-driver).

Hope that helps.
