### ISSUE TITLE
AWS AMI will not let you connect via neo4j-browser out of the box

### ISSUE THREAD

**Issue by daidoji** [neo4j/neo4j-browser#808]
### Description
Neo4J AMI does not work out of the box through the neo4j-browser.  Cannot connect via the neo4j-browser (either the one that spins up with the AMI or via neo4j Desktop).  **Can connect via cypher-shell**

>  ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3

Wasn't sure if this was the right issue tracker, but seems the most appropriate.

### Reproduce Steps
Tried to follow the steps listed here https://neo4j.com/developer/neo4j-cloud-aws-ec2-ami/ for deploying to AWS.  AMI was neo4j-community-1-3.4.1 2018-06-14T04_59_55Z-42e71149-46df-4ee5-ae1b-34d134153fd6-ami-bb5516c4.4 (ami-74a7e90c)

Won't connect with error above when attempting to connect via the neo4j-browser ip (ie http://ec2-18-237-210-27.us-west-2.compute.amazonaws.com:7474/browser/).  Can connect via cypher-shell from a host client not on same server (ie from my house to AWS) but double checked security groups, host ip, etc...

Google Developer tools in Chrome give 
`WebSocket connection to 'wss://18.237.210.27:7687/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID
  | o | @ | vendor-f283354….js:1
-- | -- | -- | --
  | t | @ | vendor-f283354….js:1
  | s | @ | vendor-f283354….js:1
  | value | @ | vendor-f283354….js:1
  | value | @ | vendor-f283354….js:1
  | value | @ | vendor-f283354….js:1
  | value | @ | vendor-f283354….js:1
  | value | @ | vendor-f283354….js:1
  | value | @ | vendor-f283354….js:1
  | value | @ | vendor-f283354….js:1
  | j | @ | app-f283354….js:1
  | (anonymous) | @ | app-f283354….js:1
  | r | @ | app-f283354….js:1
  | (anonymous) | @ | app-f283354….js:1
  | r | @ | app-f283354….js:1
  | (anonymous) | @ | app-f283354….js:1
  | e._tryNext | @ | vendor-f283354….js:1
  | e._next | @ | vendor-f283354….js:1
  | e.next | @ | vendor-f283354….js:1
  | e._next | @ | vendor-f283354….js:1
  | e.next | @ | vendor-f283354….js:1
  | e.next | @ | vendor-f283354….js:1
  | (anonymous) | @ | vendor-f283354….js:1
  | (anonymous) | @ | vendor-f283354….js:1
  | (anonymous) | @ | app-f283354….js:1
  | (anonymous) | @ | vendor-f283354….js:1
  | i | @ | vendor-f283354….js:1
  | c | @ | vendor-f283354….js:1
  | h | @ | vendor-f283354….js:1
  | value | @ | app-f283354….js:1
  | (anonymous) | @ | app-f283354….js:1
  | R | @ | vendor-f283354….js:1
  | u | @ | vendor-f283354….js:1
`

Tried enabling http via `dbms.connector.http.enabled=true` and `dbms.connector.http.listen_address=:7474` in `neo4j.template` as comes up in a few issues and Stackoverflow thread.  

When trying to make the connection via http (which also fails) I get this in Google Chrome tools
`WebSocket is already in CLOSING or CLOSED state.`

Checked to make sure that the AMI does run Java8 as in https://github.com/neo4j/neo4j-browser/issues/671

Tried changing `neo4j.template` with config `dbms.connector.bolt.tls_level=OPTIONAL`.  No change in above.

### Expected Behavior
To be able to follow the instructions and log into the AWS AMI.

### Current Behavior
Can't make a bolt connection via neo4j-browser.  Can log in via cypher-shell

Ideally, instructions should change or AMI should be updated.

### Your Environment
This bug persists across several operating systems and browsers, seems to be an issue with the host.  For clarity my env consisted of

| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows 10
| Web browser    |  Google Chrome Version 68.0.3440.84 (Official Build) (64-bit)
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 
| Neo4j          | 3.4.1

**Comment by oskarhane** [comment]
Sorry for the late response @daidoji, but did you manually trust the certificate in your web browser?
The `ERR_CERT_AUTHORITY_INVALID` suggests that the web browser refuses to connect because the cert is untrusted/self signed.

**Comment by behemothdan** [comment]
That worked for me as well @adtodesco - thanks for sharing!
