### ISSUE TITLE
Customize color for labels containing a dot does not work

### ISSUE THREAD

**Issue by ncrocfer** [neo4j/neo4j-browser#809]
### Description

It's impossible to customize the label's color when the label contains a dot (example: `foo.bar`).

### Current Behavior

![selection_065](https://user-images.githubusercontent.com/1552526/43892146-79933f62-9bcb-11e8-9fad-192ca2e55dec.png)

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Debian GNU/Linux 8.11 (jessie)
| Web browser    |  Firefox 61.0.1
| Neo4j Browser  | 3.2.2
| Neo4j          | 3.4.4

### Additional Information

It seems to work with other characters (tested with _ and -).

**Comment by oskarhane** [comment]
It is, indeed. I'll create an internal ticket for this. Thanks for the report @ncrocfer
