### ISSUE TITLE
Node graph preview is barely usable

### ISSUE THREAD

**Issue by ivan-kleshnin** [neo4j/neo4j-browser#811]
### Description

Node data preview in graph mode breaks on long lines and newlines. Both are pretty standard after `JSON.stringify` as well as in HTML code. Also its height is super small and not expandable which makes the previous one a blocker.

### Reproduce Steps

Make any node containing reasonably long string:

![neo4j-browser-issue](https://user-images.githubusercontent.com/2128182/44202957-2da75300-a156-11e8-9f40-cff59a924daf.png)

### Expected Behavior

I dunno, cut long strings to `str: "foobar..." (see more)` like everyone else does?

---

Of course, I can use a table view but this UI problem kills a user experience.

**Comment by ivan-kleshnin** [comment]
Browser version is 3.2.5

**Comment by if6was9** [comment]
I just opened #927 which i believe may be the same issue.  I have more detail there.

It appears to affect Chrome far more than Safari or Firefox.

**Comment by OskarDamkjaer** [comment]
Long due update: There's plans in the works to fix this problem in an upcoming release this year. The team is quite small and there's a lot to improve, so I can't promise we'll get to it!
