### ISSUE TITLE
"Upgrade to this version" button is disabled

### ISSUE THREAD

**Issue by ivan-kleshnin** [neo4j/neo4j-browser#815]
### Description

![screen shot 2018-08-23 at 13 24 25](https://user-images.githubusercontent.com/2128182/44520240-06153500-a6d8-11e8-9467-ab7556ead90b.png)

Upgrade to this version button is disabled for no obvious reason. I remember it was enabled at 3.4.4 so I successfully switched to 3.4.5. Now it's permanently blocked for all versions: older and newer.
It's the same for all my databases and there's no clue about what should I do to unblock it. I tried to restart an app – no idea what to do next :(

**Comment by ivan-kleshnin** [comment]
I think I've got it: you can upgrade or downgrade only to the current version of browser app. But then there's a UI-UX issue. Disabled button implies you can do something **inside an app** to enable it (like input a serial or something). If there's nothing you can do except of reinstalling the app itself – it is confusing. I suggest to add a tooltip or replace a button with a static alert-like message.

**Comment by oskarhane** [comment]
Sorry for the slow response on this @ivan-kleshnin.
This is a Neo4j Desktop issue, could you please open it [in the neo4j-desktop repo](https://github.com/neo4j-apps/neo4j-desktop) instead?
