### ISSUE TITLE
Rendering nodes with NaN property values cause browser app to crash

### ISSUE THREAD

**Issue by tpanza** [neo4j/neo4j-browser#826]
### Description

Attempting to run even a simple Cypher query from the browser where a node containing a property whose value is `NaN` is attempted to be rendered causes the browser app to crash. It changes to a completely blank white page. 

Example query, where the node of id `10` happens to have a property whose value is `NaN`:

```
MATCH (n) WHERE id(n)=10 RETURN n
```

The following stack trace is shown in the Firefox console:

```
Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
Stack trace:
r@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:1420121
l@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:249494
$n@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:305665
enqueueSetState@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:338164
../../node_modules/react/cjs/react.production.min.js/o.prototype.setState@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:2754697
../../node_modules/styled-components/dist/styled-components.browser.es.js/</ne</o</e.prototype.componentWillReceiveProps@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:3118310
pn@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:282027
In@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:294061
Kn@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:303894
Yn@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:304202
dl@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:307584
il@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:307093
ul@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:306919
rl@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:306291
$n@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:305650
enqueueSetState@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:338164
../../node_modules/react/cjs/react.production.min.js/o.prototype.setState@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:2754697
a/</c</c.prototype.onStateChange@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:2739009
c@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:2792448
s/</</<@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:1827194
f/</<@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:2787116
../../node_modules/suber/lib/bus.js/e.createReduxMiddleware/</</<@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:3134418
dispatch@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:2788660
exec/<@http://remote-machine.mycompany.com:7474/browser/app-8e76f7dbd0cd6ce654d5.js:1:1813951
N/</<@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:679180
N/<@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:679048
a@http://remote-machine.mycompany.com:7474/browser/vendor-8e76f7dbd0cd6ce654d5.js:1:614643
```

### Reproduce Steps

Create a node in the graph with a property value of `NaN`. Since this cannot be done in the browser interface, instead use, for example, the Python and py2neo and connect to the graph via BOLT. This avoids having to encode `NaN` with JSON.

In my particular case, I populated node properties from a Pandas dataframe. The columns in the dataframe of interest are floating point values. There are missing values in the dataframe, so those rows are stored as `NaN`. I then, within the Python code, iterate over the dataframe, set node properties.

Example Python code for populating the graph with `NaN` property values:

```python
statement = """
UNWIND $parameters as row
MERGE (iui:ItemUsageInstance {instance_id: trim(row.USAGE_INSTANCE)})
  ON CREATE SET
    iui.usage_type = trim(row.USAGE_TYPE),
    iui.x1 = row.X_COOR
MERGE (nhiui:ItemUsageInstance {instance_id: trim(row.NEXT_HIGHER_USAGE_INST)})
  ON CREATE SET
    nhiui.usage_type = trim(row.NEXT_HIGHER_USAGE_TYPE)
"""
tx = graph.begin(autocommit=True)
params = []
# dataframe is indexed with numerical indexes
# X_COOR is a column of floats with missing values stored as NaN
for index, row in df.iterrows():
    params_dict = {
        'USAGE_INSTANCE': row['USAGE_INSTANCE'], 
        'USAGE_TYPE': row['USAGE_TYPE'],
        'X_COOR': row['X_COOR'],
        'NEXT_HIGHER_USAGE_INST': row['NEXT_HIGHER_USAGE_INST'],
        'NEXT_HIGHER_USAGE_TYPE': row['NEXT_HIGHER_USAGE_TYPE']
    }
    params.append(params_dict)
    if index % 20000 == 0 and index > 0:
        tx.evaluate(statement, parameters = {"parameters" : params})
        tx = graph.begin(autocommit=True)
        params = []
tx.evaluate(statement, parameters = {"parameters" : params})
```

If I attempt to view a node from the cypher-shell that has a `NaN` property, it displays successfully.

```
neo4j> MATCH (n) WHERE id(n)=10 RETURN n;
+----------------------------------------------------------------------------------------------------------------------------+
| n                                                                                                                          |
+----------------------------------------------------------------------------------------------------------------------------+
| (:Label3 {item_id: "000000012345678", usage_type: "thing", z1: NaN, z2: NaN, y1: NaN, y2: NaN, x1: NaN, x2: NaN})          |
+----------------------------------------------------------------------------------------------------------------------------+

1 row available after 7 ms, consumed after another 0 ms
```

However, if I try to run that same query from the Neo4J browser, the Firefox browser tab becomes a completely blank white page, with the above stack trace shown in the console.

### Expected Behavior

Expected the browser to successfully display and render node(s) containing `NaN` property values.

### Current Behavior

Browser fails to display and render any nodes that contain `NaN` property values. Browser tab becomes a completely blank white page and needs to be refreshed to get back to a working Neo4J browser session.

### Can you propose a solution?

Unfortunately I cannot. Do not know this codebase well at all.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  web browser client: Windows 10; neo4j server: RHEL 7.3
| Web browser    |  Firefox 60.1.0esr (32-bit)
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 3.2.5
| Neo4j          | 3.4.5

### Additional Information

This appears to be a regression. According to the [screenshot posted here](https://github.com/neo4j/neo4j/issues/696#issuecomment-239177592), around 2016 timeframe, the browser could display nodes with `NaN` property values.

From discussion [here ](https://community.neo4j.com/t/browser-tab-times-out-for-simple-limited-query-that-works-fine-in-cypher-shell/1591) on Neo4J community discussion boards.

**Comment by oskarhane** [comment]
Thanks for this detailed report @tpanza!
This sure sounds like a `NaN` bug. 
It's now tracked internally and we get on working on solving it.

**Comment by oskarhane** [comment]
Recent updates have fixed this issue and it will be out in the next release of neo4j-browser.

<img width="726" alt="oskarhane-mbpt 2018-10-22 at 11 42 37" src="https://user-images.githubusercontent.com/570998/47286680-08b8db80-d5f0-11e8-844d-ff26721d381e.png">

**Comment by oskarhane** [comment]
Recent updates have fixed this issue and it will be out in the next release of neo4j-browser.

<img width="726" alt="oskarhane-mbpt 2018-10-22 at 11 42 37" src="https://user-images.githubusercontent.com/570998/47286680-08b8db80-d5f0-11e8-844d-ff26721d381e.png">
