### ISSUE TITLE
Crash when clicking on warning triangle: `Something went wrong: "RangeError: Invalid array length" and the application can't recover.`

### ISSUE THREAD

**Issue by clozach** [neo4j/neo4j-browser#831]
### Description
This cypher query generates an orange warning triangle…

…as shown here:

![image](https://user-images.githubusercontent.com/124952/46451973-1811db00-c74e-11e8-92af-d4f499369137.png)

Clicking on that triangle causes the `Something went wrong: "RangeError: Invalid array length" and the application can't recover.` error to occur.

### Reproduce Steps
See above.

### Expected Behavior
It doesn't crash.

### Current Behavior
It crashes.

### Can you propose a solution?
Bug fix.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  macOS 10.13.6 (17G65)
| Web browser    |  Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
| Neo4j Browser  |  Neo4j Browser version: 3.2.6
| Neo4j          |  Neo4j Server version: 3.3.7 (community)

**Comment by oskarhane** [comment]
Thanks for this report @clozach. I've opened a PR with a fix now.
