### ISSUE TITLE
Ctrl-F search in browser window

### ISSUE THREAD

**Issue by ivan-kleshnin** [neo4j/neo4j-browser#842]
### Description

Ctrl-F / Cmd-F does not invoke any search window. 
Am I supposed to export CSV only to do some basic search? Or do I miss something obvious?

**Comment by oskarhane** [comment]
Hi, I assume this is in a Neo4j Desktop environment?
Could you please open a feature request over in https://github.com/neo4j-apps/neo4j-desktop instead, that graph applications should have search functionality?
