### ISSUE TITLE
Remote guide error: TypeError: NetworkError when attempting to fetch resource 

### ISSUE THREAD

**Issue by joaocarloscardoso** [neo4j/neo4j-browser#847]
Hi,

Just installed the new version (community edition 3.4.9) and I have this configuration at neo4j.conf:

`
browser.remote_content_hostname_whitelist=*
browser.post_connect_cmd=play http://127.0.0.1:80/egov-guide/introduction.html;
`
The idea is to run a specific guide introducing the database. with previous versions runs well, but with this one I get the following error:
Remote guide error: TypeError: NetworkError when attempting to fetch resource.
Just to complete: if I switch to 3.4.7 or 3.4.8 the educational guide is accessible. This last one is available through IIS and the web.config is like that:

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<system.webServer>
  <httpProtocol>
    <customHeaders>
      <add name="Access-Control-Allow-Origin" value="*" />
      <add name="Access-Control-Allow-Methods" value="GET, PUT, POST, DELETE, HEAD, OPTIONS" />
      <add name="Access-Control-Allow-Credentials" value="true" />
      <add name="Access-Control-Allow-Headers" value="X-Requested-With, origin, content-type, accept" />
    </customHeaders>
  </httpProtocol>
        <staticContent>
            <mimeMap fileExtension=".grass" mimeType="neo4j/style" />
        </staticContent>
</system.webServer>
</configuration>
`

**Comment by oskarhane** [comment]
Hi @joaocarloscardoso,

We are sending `Pragma` and `Cache-Control` headers with the requests since neo4j-browser 3.4.9.
Could you try and add them to the allowed headers, like:

```
<add name="Access-Control-Allow-Headers" value="X-Requested-With, origin, content-type, accept, Pragma, Cache-Control" />
```

and see if that fixes it?

**Comment by joaocarloscardoso** [comment]
Hi @oskarhane 

It worked! Thanks a lot.
