### ISSUE TITLE
Save and restore a visualization state

### ISSUE THREAD

**Issue by mehdibalouchi** [neo4j/neo4j-browser#858]
I want to save position of nodes in a visualization somehow and later restore those positions.
consider the user gets a visualization and starts to move nodes on screen, he can `Export PNG` of the visualization. I want to make the user able to save the visualization he made somehow (in a file or something) and when he restores that, all nodes are in the position he saved.
Is there any straight solution you guys can help me with?

**Comment by oskarhane** [comment]
Hi,
the position of elements in the viz is not something we track in neo4j-browser.
What is the user goal here, why do you want this feature?
It sounds like Neo4j Bloom is a better tool for you: https://neo4j.com/bloom/

**Comment by mehdibalouchi** [comment]
> the position of elements in the viz is not something we track in neo4j-browser.

How can I do this? Where is the code that adjusts node positions? I cant't find that. 
I'm trying to find that part of code that adjusts the initial position of nodes in the visualization, so that maybe I can do some hacks and solve my problem.

**Comment by oskarhane** [comment]
Thanks for the additional input here, and a use case @rsworden59!

@mehdibalouchi: The layout is using d3's force layout and happens in this file: https://github.com/neo4j/neo4j-browser/blob/master/src/browser/modules/D3Visualization/lib/visualization/components/layout.js

**Comment by steveyang331** [comment]
it seems don't sloved yet ?

**Comment by OskarDamkjaer** [comment]
This is an interesting idea, but I'm afraid it to be a quite complex feature and not something we can prioritize implementing. If anyone wants to give it a shot and hack together a demo, we could perhaps reconsider
