### ISSUE TITLE
Stuck at User is required to change their password

### ISSUE THREAD

**Issue by mdafer** [neo4j/neo4j-browser#865]
Connecting to the db for the first time using the browser over http, but can't do anything after entering default credentials

### Reproduce Steps

1- `:server connect` works with default username and password
2- Prompted to change password
3- Submitting new password results in error Neo.ClientError.Security.CredentialsExpired: User is required to change their password

### Expected Behavior

new password submitted, connection initiated 

### Current Behavior

Neo.ClientError.Security.CredentialsExpired: User is required to change their password.
### Can you propose a solution?

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Ubuntu 18.04
| Web browser    |  Chrome 70.0.3538.102 (Official Build) (64-bit), Firefox 63.0.1
| node.js        | v8.12.0
| npm            |6.4.1
| yarn           |
| Neo4j Browser  |Neo4j Browser version: 3.2.13
| Neo4j          |neo4j 3.4.10

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.

**Comment by oskarhane** [comment]
This is really unusual @mdafer. Is that just for a specific password or any password?

**Comment by mdafer** [comment]
Sorry for my late response, this is happening for any password.

**Comment by rire000** [comment]
Stuck at the same spot, same issue.  
Updated Ubuntu server with Neo4j release 3.5.1.

**Comment by rire000** [comment]
<or>
just turn authentication off

https://neo4j.com/docs/operations-manual/current/authentication-authorization/enable/

dumb workaround, but mine is a closed network, and is just for training purposes anyway, so...

**Comment by taesiri** [comment]
Had same issue connecting to neo4j for the first time using `HTTP` protocol. Try connecting via `bolt` (``bolt://localhost:7687``)

**Comment by oskarhane** [comment]
Does @taesiri's solution work for you @mdafer and @rire000?
If not, please provide more information about your environment and setup. Exactly what info you enter etc.

**Comment by mdafer** [comment]
@oskarhane using `bolt://localhost:7687` results in: 

> not a WebSocket handshake request: missing upgrade

I don't know what more to provide regarding my setup...

It's a fresh install of Ubuntu 18.04 (check my first comment), I've tried both Oracle Java and Open JDK, but same result.

**Comment by oskarhane** [comment]
Thanks @mdafer. And Neo4j isn't running inside a container or VM or something?
On what URL are you loading Neo4j Browser?

**Comment by mdafer** [comment]
Not running inside a container nor VM, running directly from AWS EC2 instance;
Using my pc's browser to connect to Neo4j hosted on the server.

**Comment by taesiri** [comment]
I should clarify that you should use ``bolt://localhost:7687`` address in Neo4J Browser while connecting to the interface via this address ``http://localhost:7474``.

Like this:

![screen shot 2019-01-06 at 8 43 23 pm](https://user-images.githubusercontent.com/588431/50739351-46430300-11f4-11e9-8cdd-60ad17da419c.png)


Accessing ``bolt://localhost:7687`` with a browser will result in ``not a WebSocket handshake request: missing upgrade`` error message.

**Comment by OskarDamkjaer** [comment]
Did this issue get resolved in the end?

**Comment by WebberLiu7** [comment]
> Did this issue get resolved in the end?
I solved it by deleting the "#" in front of "dbms.connector.bolt.listen_address=:7687" and "dbms.connector.http.listen_address=:7474" in the neo4j.conf file.
