### ISSUE TITLE
Feature Request: Neo4j Browser - Add option to collapse child relationships

### ISSUE THREAD

**Issue by billscheidel** [neo4j/neo4j-browser#867]
Currently when you click on a node in the browser there is an option to expand the children which is incredibly helpful.  This allows you to start with a simple base query (one that I can memorize) and then navigate down relationships as needed.

The problem comes if you expand the wrong node by accident (opening hundreds of nodes in the process) there is no way to undo it.  The screen is now full of unwanted nodes and going to each one and removing them is too time consuming.  You basically have to re-run your query and navigate from scratch.  It would be great if there was an option to collapse immediate child relationships of a node which would be equivalent to visiting each directly connected node and clicking on the 'Remove node from visualization' option.

**Comment by merlinr68** [comment]
+1
