### ISSUE TITLE
text overlays icon at narrow width

### ISSUE THREAD

**Issue by micahstubbs** [neo4j/neo4j-browser#870]
### Expected behavior
text does not overlay icon

### Actual behavior
text overlays icon

an opportunity to make the neo4j ui more responsive at narrow screen widths 😄 
![neo4j_bolt___localhost_7687_-_neo4j_browser](https://user-images.githubusercontent.com/2119400/39731316-dd03fb3a-521b-11e8-8039-ccbf7512bccf.png)

**Comment by oskarhane** [comment]
Sorry @micahstubbs, we (as min team browser) did not see this issue.
I've transferred it to the neo4j-browser repo now so we can track it.

**Comment by micahstubbs** [comment]
@oskarhane thanks for putting the issue on the right repo!

**Comment by OskarDamkjaer** [comment]
This issue is no longer present in the latest update of `:play start` as we don't have any icons. Than
