### ISSUE TITLE
Multi statement in Desktop - problem with backticks

### ISSUE THREAD

**Issue by ThomasFrisendal** [neo4j/neo4j-browser#881]
### Description
I am using apoc.xml.import, which generates property names containing hyphens. For that reason it is necessary to surround those names with backticks. It works fine in Desktop for single statements, but it causes syntax errors, when the same statement is used in a multi statement script in Desktop.

### Reproduce Steps
Example statement that works fine as a single statement, but fails when included in a multi statement script:

MATCH (x2:XmlTag) WHERE x2._name = "connection" 
WITH x2.`to-id` AS target, x2.`from-id` AS linkid
MATCH (c2:Concept) WHERE c2.xmlid = target
MATCH (l:XmlTag) WHERE l._name = "linking-phrase" AND l.id = linkid
WITH target AS target, l.label AS linkphrase, linkid AS linkid
MATCH (xm:XmlTag) WHERE xm._name = "connection" AND xm.`to-id` = linkid
MATCH (c1:Concept) WHERE c1.xmlid = xm.`from-id`
MATCH (c2:Concept) WHERE c2.xmlid = target
MERGE (c1)-[:RELATED_FROM]->(cr:ConceptRelationship {Name: linkphrase, LinkingPhrase: linkphrase, linkid: linkid, GDM_Level: "Business", GDM_Type: "Model"})
MERGE (c2)-[:RELATED_TO]->(cr)
WITH cr AS rels
MATCH (cm:ConceptModel {Name: $ModelName})
MERGE (cm)-[:STRUCTURED_BY]->(rels)
;

### Expected Behavior
It should work in all scenarios - single as well as multi statement.

### Current Behavior
In a multi statement scenario the statement above causes this error message:
------
Neo.ClientError.Statement.SyntaxError: Invalid input ':': expected whitespace, a variable, RelationshipsPattern, an expression or ']' (line 8, column 55 (offset: 448))
"MATCH (c2:Concept) WHERE c2.xmlid = targetMERGE (c1)-[:RELATED_FROM]->(cr:ConceptRelationship {Name: linkphrase, LinkingPhrase: linkphrase, linkid: linkid, GDM_Level: "Business", GDM_Type: "Model"})"
------
Note that the line preceding "MATCH (c2:Concept) WHERE c2.xmlid = target" ends with a backtick.

### Can you propose a solution?
No

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| MAC OS X            | 10.11.6 
| Web browser    |  Safari 11.1.2
| node.js        | ?
| npm            | ?
| yarn           | ?
| Neo4j Browser  | 3.2.14
| Neo4j          | 3.4.0 e

**Comment by gbranson** [comment]
Does it work if you try the following:

"MATCH (c2:Concept) WHERE c2.xmlid = targetMERGE (c1)-[:RELATED_FROM]->(cr:ConceptRelationship {Name:"linkphrase", LinkingPhrase" linkphrase", linkid:"linkid", GDM_Level: "Business", GDM_Type: "Model"})"

I added "" around the attribute values you were trying to reference. I think it was simply confused about where the attribute name vs the attribute value began/ended.

**Comment by ThomasFrisendal** [comment]
link phrase and linked are variables coming out of the WITH in the 5th line.
