### ISSUE TITLE
Unable to set the correct bolt websocket url in UI

### ISSUE THREAD

**Issue by moafred** [neo4j/neo4j-browser#883]
The browser rewrite the url of the bolt websocket by removing the path and always set the port 7687.

- Neo4j version: 3.4.9
- Operating system: Kubernetes

### Steps to reproduce
1. Open the UI
2. Set the url to `bolt://neo4j.domain.com/bold`

### Expected behavior
The browser should connect to `bolt://neo4j.domain.com/bold `

### Actual behavior
The browser try to connect to `bolt://neo4j.domain.com:7687 `

**Comment by OskarDamkjaer** [comment]
It seems to me your issue is resolved? Feel free to add more details and re-open if that's not the case
