### ISSUE TITLE
yarn jar doesn't prepare the jar package

### ISSUE THREAD

**Issue by direbearform** [neo4j/neo4j-browser#886]
### Description
To get the neo4j-browser jar file, one need to call prepare-jar action first before calling jar action. However, jar action is the one does the build and mvn package. I'd recommend either move the build step into the prepare-jar, or do all 3 in jar action.

### Proposed Fix
/package.json, line 30:
```diff
    "e2e-local": "CYPRESS_E2E_TEST_ENV=\"local\" cypress run",
    "e2e-local-open": "CYPRESS_E2E_TEST_ENV=\"local\" cypress open",
    "format": "prettier-eslint 'src/**/!(*.min).js' 'src/**/*.jsx' --write",
-   "jar": "yarn build && mvn package",
+   "jar": "yarn build && yarn prepare-jar && mvn package",
    "jest": "jest --coverage",
    "lint": "eslint --fix --ext .js --ext .jsx ./",
    "precommit": "lint-staged",
```
### Your Environment
Linux. I think this issue is environment agnostic.

**Comment by oskarhane** [comment]
Thanks @direbearform.
Actually, we don't use the `jar` command at all, so I'm leaning towards removing it completely.
The packaging is better off being a job for the CI rather than a npm script imo.

**Comment by Nulleye** [comment]
Hi, sorry for my ignorance, I finally managed to build the jar using the change above, however, the Jar it builds is about 19Mb, when the original one is about 4Mb. What I'm missing here?
Sorry to post this here but I can't find a clue about this anywhere.
