### ISSUE TITLE
`:help keys` unreadable with Dark Theme

### ISSUE THREAD

**Issue by rickhg12hs** [neo4j/neo4j-browser#889]
### Description
Using Dark Theme, text unreadable in `:help keys`.

### Reproduce Steps

1. Select `Dark Theme`
2. Execute `:help keys`
3. Observe Output

### Expected Behavior

Readable text.

### Current Behavior

Unreadable text.  Text color same as background color?

### Can you propose a solution?

Use suitable text colors for a dark theme.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| Fedora Linux             |  4.18.19-100.fc27.x86_64
| Google Chrome    |  71.0.3578.98 (Official Build) (64-bit)
| Neo4j Browser  | 3.2.13
| Neo4j          | 3.5.0 (community)

### Additional Information

neo4j was installed from [yum repo](http://yum.neo4j.org/stable/).

I'm also wondering why the repo neo4j browser version is not current.

**Comment by oskarhane** [comment]
Thanks for this report @rickhg12hs. We'll get on it!
