### ISSUE TITLE
After expand if we first dismiss a node then re-expand it throws error

### ISSUE THREAD

**Issue by ams1** [neo4j/neo4j-browser#905]
After expanding the child relationships of **the node** if we dismiss (remove from graph) any of the children, then double click on **the node** will reveal the dismissed child, BUT when double-clicking AGAIN on **the node** it will throw an error.

### Reproduce Steps

(given)
1. Display a single node that has child relationships (aka the node)
2. Expand the child relationships of the grandfather (to get the children)
3. Pick ANY node from the children (aka the child)
4. Dismiss (remove from graph) the child

(when)
5. Double click on the node -> it will reveal the dismissed child
6. Double click AGAIN on the node -> ERROR

### Expected Behavior

![image](https://user-images.githubusercontent.com/10154357/53415389-cfe3a580-39d9-11e9-94c4-8c948957be9c.png)

### Can you propose a solution?

As i see it, the expandedNodeMap contains duplicates after first removing the child and then expanding the node, possibly because the removeNode doesn't remove the node from the expandedNodeMap.
![image](https://user-images.githubusercontent.com/10154357/53415551-39fc4a80-39da-11e9-9533-23e4a350d677.png)

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows
| Web browser    |  Chrome
| node.js        | v10.15.1
| npm            |6.4.1
| yarn           |1.13.0
| Neo4j Browser  | downloaded today 3.2.17?
| Neo4j          |

### Additional Information

**P.S.: BIG, BIG Thank you for Neo4j (!) and keep up the GREAT work you're doing!**

**Comment by oskarhane** [comment]
Thanks for this report @ams1, we'll have a look at it!
