### ISSUE TITLE
Question: is it possible to only the graph component in my own project?

### ISSUE THREAD

**Issue by elie222** [neo4j/neo4j-browser#906]
I'd like to display the graph that the Neo4j browser uses. Is this available as a separate package or not at this time?

**Comment by Dcanzano** [comment]
@elie222   you might want to consider  https://github.com/neo4j-contrib/neovis.js, which isnt the exact package that Browser uses, but might satisfy your needs

**Comment by oskarhane** [comment]
Since this is open source, you have the code available and it's somewhat detached from the rest of the application.
But it's not separated into its own package.
