### ISSUE TITLE
Graph view doesn't display node/relationships from lists across multiple rows

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j-browser#912]
### Description
Under some cases, when returning multiple rows with lists of nodes and relationships on each, the browser only shows the results of one row and not all.

Looking at the data itself, the results are correct, and a modified query can display all the expected nodes, so this seems to be a problem in how the browser displays returned data.

This is in reference to [this post on the community site](https://community.neo4j.com/t/help-re-writing-query/5589).

### Reproduce Steps
We can create a sample graph, where there are purposefully multiple nodes with the same properties, like this:

```
unwind range(1,4) as index
create (a:MyNode { `value`: 9 })-[:LIKES]->(t:Thing{name:'B'})
```

We can then use `apoc.path.subgraphAll()` to get the subgraphs from each of the :MyNodes we created, and each one will be a separate independent subgraph. 

```
MATCH (a:MyNode { `value`: 9 })
CALL apoc.path.subgraphAll(a, {maxLevel:1}) YIELD nodes, relationships
RETURN nodes, relationships, [node in nodes | id(node)] as nodeIds, [rel in relationships | id(rel)] as relIds
```

### Expected Behavior
We should see 8 nodes in the graph view: 4 sets of node pairs with a relationship between each pair.

### Current Behavior
However when returning, the browser displays a graphical view for the nodes and relationships returned from only one of the rows, and not all, so we only see one pair of nodes and a single relationship. 

We can see in ids list of the table view that each row should be returning a different sent of nodes and a different relationship for each, so the data is correct, only the graphical display is incorrect.

### Your Environment
Reproduced on 
Neo4j 3.5.3
Neo4j Desktop 1.1.17
Neo4j Browser 3.2.16
APOC 3.5.0.2

**Comment by oskarhane** [comment]
Thank you for a great description @InverseFalcon. I've opened a PR that should fix this.
