### ISSUE TITLE
When playing snake the up and down arrows cause the screen to scroll

### ISSUE THREAD

**Issue by eastlondoner** [neo4j/neo4j-browser#916]
### Description
When I play snake in the browser it is very frustrating because pressing the up and down arrows to direct the snake causes the game to be scrolled up and down out of view - which is obviously annoying

### Reproduce Steps
open browser
`:snake`
play 

### Expected Behavior
screen should not scroll while playing snake

### Current Behavior
screen scrolls while playing snake

### Can you propose a solution?
Switch to using asdw for steering the snake instead of the arrow keys.

### Your Environment
neo4j cloud

**Comment by unterstein** [comment]
It happens only to me when there is something to scroll. So if you have a login screen and maybe an existing cypher result. If I have the chrome window fullscreen and no other thing shown in the browser, it works just fine for me. But I agree, that this is annoying otherwise :(

**Comment by oskarhane** [comment]
Thanks, fixed with: https://github.com/neo4j/neo4j-browser/commit/6145c9985220a60011947a8e4d95039d885682b9
Will be in next release.

**Comment by unterstein** [comment]
@oskarhane  Thank you <3
