### ISSUE TITLE
Embedding Neo4j Browser query result frame in external webapp?

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j-browser#921]
We are currently making a webapp at https://search.het.io (not fully functional yet) that helps users detect important paths in our Hetionet database, which is stored via Neo4j at https://neo4j.het.io.

We would like to embed query result frames from our Neo4j Browser in the webapp at https://search.het.io. The Python backend will generate the query. Is there an easy way to embed / extract result frames from the Neo4j Browser?

Alternatively, given the raw result code response JSON, is there a straightforward way to produce the d3 visualization used by the Neo4j Browser? In short, we'd like our visual result frame to resemble the Neo4j browser frame as much as possible.

This question is similar to [this StackOverflow question](https://stackoverflow.com/questions/46078100/how-to-embed-neo4j-browser-result-visualisation-in-web-application "How to embed neo4j browser result visualisation in web application"). CCing @vincerubinetti from our team and OP of the SO question @fiedl.

**Comment by oskarhane** [comment]
Hi @dhimmel ,
Unfortunately there's nothing new on this front. The viz code still lives inside the neo4j-browser project (but now in js instead of coffeescript) and there's no easy way to re-use it in third party apps without copying it.
We might offer this as part of a code library going forward, but I can't give you any timeline on that.

And embedding single result frames is not possible at the moment, but this is something we're thinking about and want offer in the future I think.

**Comment by dhimmel** [comment]
Thanks @oskarhane for the update, which will help with our planning. We'll update this issue with the solution we end up using.

**Comment by oskarhane** [comment]
Thanks @dhimmel, sounds good.

**Comment by m00dy** [comment]
@dhimmel I'm curious as well.

**Comment by dhimmel** [comment]
Possibly relevant is cy2neo by @jexp:

+ https://github.com/jexp/cy2neo
+ https://github.com/jexp/cy2neo/blob/neod3/scripts/neod3.js

**Comment by Sudo-Swapnil** [comment]
I was also facing the same problem. You may try using [popotojs](https://www.npmjs.com/package/popoto)

**Comment by ceisserer** [comment]
since this report is quite old, is there any news regarding neo4j browser embedding / re-use as component?

**Comment by OskarDamkjaer** [comment]
As for using the whole of browser as a component, iframing it or cloning the project and hacking it to fit your needs would be the way to go. We don't have any plans to make it embeddable

**Comment by amartinez-forrester** [comment]
@OskarDamkjaer could you share some script that uses the neo4j-arc lib after query something from the graph?
