### ISSUE TITLE
very slow ui response if caption is set to property containing long string values

### ISSUE THREAD

**Issue by if6was9** [neo4j/neo4j-browser#927]
### Description

When the browser happens to choose a property for the caption that have large string values,
the performance of the UI becomes nearly unusable.

### Reproduce Steps

Set the caption for a given label to a property that will contain  long string values.  (1k)  
Select some nodes with that large string value.

### Expected Behavior

UI should perform reasonably.

### Current Behavior

UI becomes exceptionally slow and CPU usage spikes.

### Can you propose a solution?

I don't know precisely what is going on internally.  But captions are useless beyond a very small 
number of characters anyway.  So perhaps the values could be trimmed off and this problem would go away.

Note that "Don't do that" would be a semi-acceptable solution except that Neo4j chooses these captions initially, so users can have this end up happening to them.

### Your Environment

Mac + Chrome 

Mac Safari and Mac Firefox *do not* exhibit the problem.

### Additional Information

This was a tricky problem to track down.  I had "solved" it previously by nuking the Local Storage in chrome.  But I believe this ended up being an accidental fix because it reset the browser preferences and the caption labels reset to other properties.

**Comment by oskarhane** [comment]
Thanks for reporting this @if6was9! I'll make sure we look into this soon.

**Comment by OskarDamkjaer** [comment]
Not "soon" per se but we should have sorted this issue out with #1429 🎉
