### ISSUE TITLE
2 string query highlighting bugs

### ISSUE THREAD

**Issue by wis** [neo4j/neo4j-browser#934]
paste these queries in the query text box
1. ``` match (p:Person) where p.name='marry' match (m:Person) where m.name='harry' create (p)-[:`doesnt like`]->(m) ```
2. ``` match (p:Person) where p.name='marry' match (m:Person) where m.name='harry' create (p)-[:`doesn't like`]->(m) ```

### Expected Behavior
1. strings in back ticks (`) should be highlighted in green like any other type of typing strings
2. all of the string should be highlighted, by ignoring the single quote (`'`) in the string

### Current Behavior
1. it's not highlighted in green
2. "doesn" is in black and the rest, including the back tick (`'`) is in green like any other string 

### Can you propose a solution?
would fixing this require fixing the highlighter's client-side parser, do you have one?

### Your Environment
neo4j sandbox started today

### Additional Information
not needed

**Comment by OskarDamkjaer** [comment]
Thanks for reporting this syntax highlighting issue! 

You're right that we have a client side parser. We're currently planning to move to the monaco editor in the next couple of months, it will require a rewrite of the syntax highlighting, so we're not planning to fix the older parser. I will write down this example and make sure we have a unit test for it in the new version!
