### ISSUE TITLE
navigating to a previously selected history entry - then modifying, and navigating away, causes you to lose the latest updates to the query

### ISSUE THREAD

**Issue by borick** [neo4j/neo4j-browser#935]
### Description
When you navigate to a previous entry in the neo4j history, and begin edit that previous entry, then accidentally navigate away, you lose the edits made to that history entry.

### Reproduce Steps
- Navigate to a previous made entry in neo4j browser history
- Make a new edit to that history entry
- Navigate back again in the history, and then back to your "edit" entry - your edits have reverted back to the previous state

### Expected Behavior
- The changed query should also be kept in the history in addition to the previously edit entry - when switching back should allow you to recover all queries entered, including the new one as as a result of the previous-history entry

### Current Behavior
- Switching back from an "edited" previous history entry, causes you to lose that edited change

### Can you propose a solution?
- Maintain the new edited previous history entry, in addition to the original ones

What needs to be done to address this issue? Ideally, provide a pull request with a fix.
- Needs a PR still

### Your Environment
- Neo4j 3.5.4 Enterprise
- Mac OSX
- Chrome

### Additional Information

- N/A

**Comment by OskarDamkjaer** [comment]
This is intended behaviour since we want to preserve history as the commands that were run.
