### ISSUE TITLE
How does Neo4j Browser listen to data changes

### ISSUE THREAD

**Issue by liiri** [neo4j/neo4j-browser#959]
I observed that the browser is connecting to ws://localhost:7687/.

I tried to listen on this websocket using the simple client example at https://www.npmjs.com/package/websocket , but did not get any messages logged, though changes were made by my app and the browser got live updates.

Client code for reference:

```
var WebSocketClient = require('websocket').client;

var client = new WebSocketClient();

client.on('connectFailed', function(error) {
    console.log('Connect Error: ' + error.toString());
});

client.on('connect', function(connection) {
    console.log('WebSocket Client Connected');
    connection.on('error', function(error) {
        console.log("Connection Error: " + error.toString());
    });
    connection.on('close', function() {
        console.log('echo-protocol Connection Closed');
    });
    connection.on('message', function(message) {
        console.log(message);
    });
});

client.connect('ws://localhost:7687/');
```

**Comment by oskarhane** [comment]
@liiri You connect using the neo4j-driver: https://github.com/neo4j/neo4j-javascript-driver
Neo4j speaks Bolt (binary protocol) on that websocket, so you'll need a driver if you want to use it.
