### ISSUE TITLE
Change location of the refresh button in :queries

### ISSUE THREAD

**Issue by tomswinkels** [neo4j/neo4j-browser#963]
The refresh button in te :queries list are now downsite the result. 

Is you refresh the list sometimes the list is small and sometimes big, but than you always need to move you're curser to the refresh button.

I think it is better to place the button above between the other buttons.

**Comment by OskarDamkjaer** [comment]
Hi! Could you provide a screen shot of the button you're referring to so I'm sure I've understood you correctly?

**Comment by tomswinkels** [comment]
@OskarDamkjaer i think this is already fixed with an upgrade to a newer version :)

**Comment by OskarDamkjaer** [comment]
Lovely! Sorry about the late-ish reply! :)
