### ISSUE TITLE
EXPLAIN/PROFILE does not return query plan

### ISSUE THREAD

**Issue by OpenCoderX** [neo4j/neo4j-browser#983]
Plans section of query results not shown when executing EXPLAIN or PROFILE

### Reproduce Steps

Execute query ```explain MATCH (n:Client) RETURN n.id LIMIT 25``` nothing is returned, no Plans section on left side of result view
### Can you propose a solution?

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows 10
| Web browser    |  Firefox
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 3.2.20
| Neo4j          | 3.5.12

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.

**Comment by OskarDamkjaer** [comment]
When I run your query I get a query plan. If this is still an issue, please do provide reproduction-steps and re-open!
