### ISSUE TITLE
Left brace ( "{") appears on node next to nodeName in Chrome browsers

### ISSUE THREAD

**Issue by seangrant82** [neo4j/neo4j-browser#989]
## Description
When creating node in the Neo4j browser in Chrome on Windows 10 , a left brace appears next to the label when viewing them. This only appears in Chrome and not in FireFox, Edge or the desktop application

### Reproduce Steps

1. Open the Neo4j Browser on Chrome (My version was Chrome Version 78.0.3904.97 (Official Build) (64-bit) )
2. Enter in following cypher:  `CREATE (actf:aircraft {model:'DC-89'})`
3. View your nodes: `MATCH (n:aircraft) RETURN n LIMIT 25`
You will see in Chrome there is a left brace:
![image](https://user-images.githubusercontent.com/11846453/69096282-f682ba00-0a08-11ea-9df9-a60a6c0e2bfe.png)

### Expected Behavior
It should behave in the same way as in all other browsers where no left brace appears

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Windows 10 Pro 1903
| Web browser    |  Chrome Version 78.0.3904.97 (Official Build) (64-bit)
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 3.2.20
| Neo4j          |3.5.12

**Comment by ZhekaAl** [comment]
software name | version
-- | --
  |  
OS | Windows 10 Pro 1809
Web browser | Chrome 79.0.3945.117 (Official Build) (64-bit)
Neo4j Browser | 4.0.1
Neo4j | 3.5.5

There wasn't left brace

**Comment by OskarDamkjaer** [comment]
I can't see the left brace either, closing this. Tried in chrome on mac. Feel free to re-open if you find a way to reproduce
